import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const bellezaMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  salon_belleza: {
    vertical: 'salon_belleza',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Salon de Belleza',
    software: [
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes+IVA', description: 'Lider LATAM booking' },
      { name: 'Fresha', price: 'Gratis base', description: '20% comision nuevos clientes marketplace' },
      { name: 'Booksy', price: '$520 MXN/mes', description: 'Single user + $350/staff extra' },
    ],
    apis: [
      'AgendaPro REST API (plan Pro)',
      'Fresha limited',
      'Booksy limited',
      'Google Calendar sync',
    ],
    topFaqs: [
      'Cuanto cuesta un corte/tinte/mechas?',
      'Tienen cita disponible hoy?',
      'Aceptan walk-ins?',
      'Cuanto tiempo tarda un servicio de color?',
      'Aceptan tarjeta/meses sin intereses?',
      'Tienen promociones?',
      'Puedo pedir un estilista especifico?',
      'Politica de cancelacion?',
      'Venden productos profesionales?',
      'Tienen paquete de novia?',
    ],
    neverHallucinate: [
      'PRECIOS — varian por estilista, largo de cabello, producto. ERROR = confrontacion',
      'DISPONIBILIDAD de estilista — agenda en tiempo real',
      'PROMOCIONES — solo las vigentes',
      'DURACION de servicio — color completo puede ser 3-4h, no inventar',
      'PRODUCTOS/MARCAS — si no esta en contexto, no inventar',
    ],
    crisisProtocols: [
      'REACCION ALERGICA a tinte: Enjuagar inmediatamente. Si hay dificultad respiratoria, 911. Documentar producto/lote.',
      'QUEMADURA quimica: Enjuagar, documentar, referir a medico si es severa.',
      'RESULTADO insatisfactorio: Escuchar, ofrecer correccion con estilista senior. No admitir culpa por escrito.',
    ],
    fallbackPhrase,
  },

  barberia: {
    vertical: 'barberia',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Barberia',
    software: [
      { name: 'Booksy', price: '$520+ MXN/mes', description: 'Fuerte en barberias' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS' },
      { name: 'Fresha', price: 'Gratis base', description: 'Marketplace' },
      { name: 'Citalo', price: 'Custom MX', description: '250+ barberias LATAM' },
    ],
    apis: [
      'Booksy API limited',
      'AgendaPro REST API (Pro)',
      'Fresha limited',
    ],
    topFaqs: [
      'Cuanto cuesta el corte/degradado?',
      'Tienen espacio ahorita?',
      'Tienen membresia?',
      'Cuanto tarda un corte con barba?',
      'Con cual barbero me agendo?',
      'Que incluye el paquete especial?',
      'Venden pomada/aceite de barba?',
      'Aceptan tarjeta?',
      'A que hora cierran?',
      'Servicio a domicilio/eventos?',
    ],
    neverHallucinate: [
      'PRECIOS — sensibilidad alta en ticket bajo',
      'TIEMPO DE ESPERA — varia por hora, no inventar',
      'MEMBRESIAS — terminos exactos, que incluye y que no',
      'DISPONIBILIDAD de barbero — agenda real',
      'PRODUCTOS — marcas y precios verificados',
    ],
    crisisProtocols: [
      'CORTE/HERIDA con navaja: Primeros auxilios, documentar. Si requiere sutura, referir a medico.',
      'RESULTADO insatisfactorio: Ofrecer correccion. Escalar a barbero principal.',
    ],
    fallbackPhrase,
  },

  spa: {
    vertical: 'spa',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Spa',
    software: [
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS' },
      { name: 'Zenoti', price: 'Enterprise pricing', description: 'All-in-one spa mgmt' },
      { name: 'Book4Time', price: 'Custom', description: 'Spa de hotel/resort' },
      { name: 'Fresha', price: 'Gratis base', description: 'Marketplace' },
    ],
    apis: [
      'Zenoti REST API + Zapier',
      'AgendaPro REST API',
      'Book4Time API',
    ],
    topFaqs: [
      'Que tratamientos ofrecen y precios?',
      'Tienen paquetes para parejas?',
      'Cuanto dura cada tratamiento?',
      'Que debo traer/como prepararme?',
      'Tienen paquetes wellness/dia de spa?',
      'Venden tarjetas de regalo?',
      'Politica de cancelacion?',
      'Contraindicaciones para embarazadas?',
      'Metodos de pago/meses sin intereses?',
      'Necesito cita previa?',
    ],
    neverHallucinate: [
      'PRECIOS — varian por tipo de sala, promocion, temporada',
      'CONTRAINDICACIONES — error aqui puede ser danino (embarazo, corazon)',
      'DISPONIBILIDAD de terapeuta — tiempo real',
      'PRODUCTOS usados — alergias criticas',
      'PAQUETES — contenido exacto y vigencia',
    ],
    crisisProtocols: [
      'REACCION ALERGICA: Detener tratamiento. Si dificultad respiratoria: 911. Documentar producto.',
      'QUEMADURA (hot stones, cera): Primeros auxilios, documentar, referir a medico.',
      'DESMAYO/EVENTO CARDIACO: 911, DEA si disponible. Documentar todo.',
      'CLIENTE INCOMODO con terapeuta: Detener inmediatamente. Escalar a gerente. No minimizar.',
    ],
    fallbackPhrase,
  },

  gimnasio: {
    vertical: 'gimnasio',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Gimnasio',
    software: [
      { name: 'Trainingym', price: '$4,065 MXN/mes', description: '1 de cada 5 gyms MX — reconocimiento facial' },
      { name: 'XCORE', price: 'Custom', description: '598+ LATAM — WhatsApp nativo' },
      { name: 'Mindbody', price: '$3,380+ MXN/mes', description: 'Enterprise' },
      { name: 'Glofox', price: '$2,000+ MXN/mes', description: 'Mid-market' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Small gyms' },
    ],
    apis: [
      'Mindbody API (via APIANT AppConnect)',
      'Glofox API',
      'Trainingym integracion propietaria',
      'XCORE WhatsApp nativo',
    ],
    topFaqs: [
      'Cuanto cuesta la membresia y que planes tienen?',
      'Horarios?',
      'Tienen clases grupales/horario?',
      'Entrenamiento personal y costo?',
      'Pase por dia/clase de prueba?',
      'Politica de cancelacion/congelamiento?',
      'Que incluye cada membresia?',
      'Regaderas, vestidores, estacionamiento?',
      'Restricciones de edad?',
      'Metodos de pago/MSI?',
    ],
    neverHallucinate: [
      'PRECIOS DE MEMBRESIA — el dato mas critico, rango $325-3,000+ MXN',
      'HORARIO DE CLASES — cambia semanal/estacionalmente',
      'ENTRENADORES — nombres, horarios, precios individuales',
      'QUE INCLUYE cada plan — pool, clases, sauna varian',
      'CANCELACION — deadlines y penalizaciones exactas',
      'TRIAL/PASE — disponibilidad y precio real',
    ],
    crisisProtocols: [
      'LESION en el gym: Primeros auxilios, documentar. 911 si es grave. Seguro del gym aplica.',
      'EMERGENCIA CARDIACA: DEA (obligatorio en gyms grandes), 911, RCP si entrenado.',
      'ACOSO: Expulsar inmediatamente. Documentar. Ofrecer soporte a victima.',
    ],
    fallbackPhrase,
  },

  nail_salon: {
    vertical: 'nail_salon',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Salon de Unas (Nail Salon)',
    software: [
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS' },
      { name: 'Booksy', price: '$520+ MXN/mes', description: 'Booking' },
      { name: 'Fresha', price: 'Gratis base', description: 'Marketplace' },
      { name: 'Citacun', price: 'Custom MX', description: 'Especifico para unas' },
    ],
    apis: [
      'AgendaPro REST API',
      'Booksy limited',
      'Google Calendar sync',
    ],
    topFaqs: [
      'Cuanto cuesta gel/acrilico/polygel?',
      'Cuanto tiempo dura el servicio?',
      'Puedo ver disenos/galeria?',
      'Disponibilidad hoy/manana?',
      'Diferencia entre gel, acrilico y polygel?',
      'Cuanto duran antes de relleno?',
      'Que productos/marcas usan?',
      'Protocolos de higiene/esterilizacion?',
      'Aceptan walk-in?',
      'Politica de cancelacion?',
    ],
    neverHallucinate: [
      'PRECIOS por tamano (S/M/L) — las clientes son MUY especificas',
      'DISENOS — referenciar portafolio real, nunca inventar',
      'PRODUCTOS — alergias criticas (acrilatos)',
      'NAIL TECH disponible — agenda real',
      'DURACION — no subestimar, genera expectativa incorrecta',
    ],
    crisisProtocols: [
      'REACCION ALERGICA a acrilatos: Retirar producto. Si severa, referir a medico.',
      'INFECCION (hongos): No atender unas infectadas. Referir a dermatologo.',
      'LESION durante servicio: Primeros auxilios, documentar.',
    ],
    fallbackPhrase,
  },

  estetica: {
    vertical: 'estetica',
    category: 'BELLEZA_Y_LIFESTYLE',
    displayName: 'Estetica (Clinica Estetica)',
    software: [
      { name: 'Doctocliq', price: 'Custom MX', description: 'Clinica estetica con expedientes' },
      { name: 'Medilink', price: 'Custom', description: 'Tracking facial/corporal' },
      { name: 'WOOW Photo', price: 'Custom', description: 'Antes/despues con consentimiento' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS' },
    ],
    apis: [
      'AgendaPro REST API',
      'Doctocliq limited',
    ],
    topFaqs: [
      'Cuanto cuesta hydrafacial/botox/acido hialuronico?',
      'Cuantas sesiones necesito?',
      'Contraindicaciones para embarazo/medicacion?',
      'Fotos de antes y despues?',
      'Paquetes de tratamientos?',
      'Como prepararme?',
      'Efectos secundarios/recuperacion?',
      'Meses sin intereses?',
      'Quien realiza el tratamiento? Certificaciones?',
      'Duracion de sesion y cuando vere resultados?',
    ],
    neverHallucinate: [
      'CONTRAINDICACIONES — error aqui puede causar dano severo. Han muerto personas en clinicas esteticas mexicanas.',
      'RESULTADOS — NUNCA prometer resultados especificos',
      'CREDENCIALES del medico — solo las verificadas',
      'PRECIOS — por zona, unidad, sesion. Muy variable.',
      'PRODUCTOS inyectables — marca y origen deben ser verificados',
    ],
    crisisProtocols: [
      'REACCION ADVERSA post-procedimiento: Contactar medico INMEDIATAMENTE. 911 si dificultad respiratoria. Documentar producto/lote.',
      'RESULTADO INSATISFACTORIO: Escuchar, documentar con fotos, agendar revision con medico.',
      'QUEJA COFEPRIS/CONAMED: Escalar a direccion y asesor legal inmediatamente.',
      'FOTOS no autorizadas en redes: Retirar INMEDIATAMENTE. Disculpa formal. Riesgo de sancion INAI.',
    ],
    fallbackPhrase,
  },
};
