import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const gastronomiaMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  restaurante: {
    vertical: 'restaurante',
    category: 'GASTRONOMIA',
    displayName: 'Restaurante',
    software: [
      { name: 'SoftRestaurant 12', price: '$699-999 MXN/mes+IVA', description: 'POS lider en Mexico, delivery hub, CFDI' },
      { name: 'Poster POS', price: '$530-1,260 MXN/mes', description: 'Cloud POS con IA predictiva' },
      { name: 'Parrot Software', price: '$1,800-2,800 MXN/mes+IVA', description: 'Mejor integracion delivery (UberEats, Rappi)' },
      { name: 'OpenTable Mexico', price: '$2,695-4,495 MXN/mes', description: 'Reservaciones + $12/comensal red' },
    ],
    apis: [
      'SoftRestaurant REST API',
      'Poster POS API publica',
      'OpenTable API partners',
      'Clip Developer API',
      'Facturapi REST API',
    ],
    topFaqs: [
      'Cual es su horario?',
      'Tienen mesa disponible para X personas?',
      'Pueden compartir el menu?',
      'Cuanto cuesta [platillo]?',
      'Hacen entregas a domicilio?',
      'Tienen opciones vegetarianas/veganas/sin gluten?',
      'Que formas de pago aceptan?',
      'Pueden facturar?',
      'Tienen estacionamiento?',
      'Tienen paquetes para eventos?',
    ],
    neverHallucinate: [
      'PRECIOS de platillos — cualquier error genera confrontacion inmediata',
      'EXISTENCIA de platillos — nunca inventar que tienen algo que no esta en menu',
      'ALERGENOS/INGREDIENTES — error aqui puede ser letal',
      'DISPONIBILIDAD de mesas — consultar sistema real',
      'HORARIO (especialmente festivos) — nunca inventar',
      'ZONAS DE ENTREGA — un envio a zona no cubierta genera enojo',
      'PROMOCIONES — si no estan vigentes, no mencionarlas',
      'METODOS DE PAGO — decir que aceptan MSI cuando no, causa problemas',
    ],
    crisisProtocols: [
      'REACCION ALERGICA en restaurante: 911 INMEDIATAMENTE. Preservar muestra del platillo.',
      'INTOXICACION ALIMENTARIA: Documentar platillo, hora, sintomas. Escalar a gerente. Si son multiples casos, COFEPRIS.',
      'OBJETO EXTRANO en comida: Disculpa inmediata, retirar platillo, documentar, compensar. NUNCA negar.',
      'FALLA DE LUZ: POS offline mode. Monitorear cadena frio (NOM-251). Cash only.',
      'INSPECCION COFEPRIS: Dos testigos requeridos. Verificar DC-3 de manipuladores. Bitacoras de temperatura.',
    ],
    fallbackPhrase,
  },

  taqueria: {
    vertical: 'taqueria',
    category: 'GASTRONOMIA',
    displayName: 'Taqueria',
    software: [
      { name: 'SoftRestaurant Lite', price: '$699 MXN/mes+IVA', description: '2 terminales, delivery' },
      { name: 'Alegra POS', price: '$199 MXN/mes', description: 'POS basico con CFDI' },
      { name: 'Poster POS', price: '$325 MXN/mes', description: 'Inventario por ingrediente' },
      { name: 'Loyverse', price: 'Gratis', description: 'POS basico para micro-operaciones' },
      { name: 'Clip Plus 2', price: '$199-449 MXN', description: 'Terminal de pago sin mensualidad' },
    ],
    apis: [
      'Poster POS API',
      'Clip Developer API',
      'Parrot Software API (delivery)',
    ],
    topFaqs: [
      'Que tacos tienen y a como?',
      'Tienen [suadero/tripa/cabeza/lengua]?',
      'Hasta que hora estan abiertos?',
      'Hacen entregas?',
      'Aceptan tarjeta o solo efectivo?',
      'Venden por kilo?',
      'Tienen salsas picosas?',
      'Me pueden facturar?',
      'Tienen cerveza?',
      'Donde estan ubicados?',
    ],
    neverHallucinate: [
      'PRECIOS — los clientes son hipersensibles, hasta $1 MXN importa',
      'DISPONIBILIDAD DE CARNES — el pastor se acaba TODAS las noches',
      'TIPO DE TORTILLA — maiz vs. harina es critico para el mexicano',
      'SALSAS — no inventar variedad de salsas',
      'CERVEZA — requiere licencia, si no la tienen y dices que si, problema legal',
      'HORARIO — muchos cierran cuando se acaba, no a hora fija',
      'PRECIO POR KILO — es negociable y variable',
    ],
    crisisProtocols: [
      'ROBO de caja: Auditorias POS, procedimiento de cierre, caja fuerte.',
      'INTOXICACION: Documentar. COFEPRIS si multiples casos.',
      'INCIDENTE nocturno (taquerias abren tarde): Protocolo de seguridad, boton de panico.',
    ],
    fallbackPhrase,
  },

  cafeteria: {
    vertical: 'cafeteria',
    category: 'GASTRONOMIA',
    displayName: 'Cafeteria',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  panaderia: {
    vertical: 'panaderia',
    category: 'GASTRONOMIA',
    displayName: 'Panaderia',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  bar_cantina: {
    vertical: 'bar_cantina',
    category: 'GASTRONOMIA',
    displayName: 'Bar / Cantina',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  food_truck: {
    vertical: 'food_truck',
    category: 'GASTRONOMIA',
    displayName: 'Food Truck',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },
};
