import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const hospedajeMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  hotel: {
    vertical: 'hotel',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'Hotel',
    software: [
      { name: 'Oracle Opera Cloud', price: '$10-20 USD/room/mes', description: 'PMS lider 100+ rooms' },
      { name: 'Cloudbeds', price: '$108+ USD/mes', description: 'Cloud PMS + channel manager + AI' },
      { name: 'Hotelogix', price: '$7.99 USD/room/mes', description: 'Mid-size' },
      { name: 'SiteMinder', price: '56+ EUR/mes', description: 'Channel manager 450+ OTAs' },
    ],
    apis: [
      'Oracle Opera REST API',
      'Cloudbeds API + webhooks',
      'Hotelogix API',
      'SiteMinder API',
      'Booking.com Connectivity API',
      'Expedia Partner API',
    ],
    topFaqs: [
      'Horario de check-in y check-out?',
      'Tienen habitacion disponible para [fechas]?',
      'Desayuno/estacionamiento/WiFi esta incluido?',
      'Como llego desde el aeropuerto?',
      'Cual es la contrasena del WiFi?',
      'Horario de alberca/spa/gym?',
      'Puedo solicitar late check-out?',
      'Que restaurantes tienen?',
      'Estacionamiento disponible? Costo?',
      'Politica de cancelacion?',
    ],
    neverHallucinate: [
      'TARIFAS — cambian por temporada, demanda, canal. NUNCA inventar un precio',
      'DISPONIBILIDAD — debe consultar PMS en tiempo real',
      'AMENIDADES por tipo de habitacion — no todas las habitaciones tienen lo mismo',
      'PRECIOS de transfer — varian por vehiculo, distancia, horario',
      'SEGURIDAD de vecindario — nunca opinar',
      'PAQUETES all-inclusive — que incluye y que no es critico',
    ],
    crisisProtocols: [
      'HURACAN (costa mexicana): 72h previas: permitir cancelaciones sin penalizacion. 36h: ofrecer reubicacion. Durante: refugio en zonas interiores.',
      'SISMO: Evacuacion por rutas marcadas. Verificar danos estructurales antes de reocupar.',
      'OVERBOOKING: Asegurar hotel comparable cercano, pagar primera noche, transporte gratuito, compensacion.',
    ],
    fallbackPhrase,
  },

  hotel_boutique: {
    vertical: 'hotel_boutique',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'Hotel Boutique',
    software: [
      { name: 'Cloudbeds', price: '$108+ USD/mes', description: 'All-in-one PMS + channel manager' },
      { name: 'Little Hotelier', price: '89+ EUR/mes', description: 'Para <30 rooms' },
      { name: 'RoomRaccoon', price: '$5,250-13,808 MXN/mes', description: 'Revenue management AI' },
      { name: 'Visito AI', price: 'Custom', description: 'WhatsApp AI booking para hoteles' },
    ],
    apis: [
      'Cloudbeds API',
      'Little Hotelier API',
      'Visito AI WhatsApp integration',
    ],
    topFaqs: [
      'Tienen disponibilidad para [fechas]?',
      'Que incluye la tarifa?',
      'Cual es la habitacion mas [romantica/grande/con vista]?',
      'Tienen paquetes especiales?',
      'Como llegar?',
      'Que actividades hay cerca?',
      'Aceptan mascotas?',
      'Es adecuado para ninos?',
      'Tienen spa?',
      'Politica de cancelacion?',
    ],
    neverHallucinate: [
      'TARIFAS — nunca inventar, deben venir del PMS',
      'DESCRIPCION de habitaciones — cada una es unica, no generalizar',
      'RECOMENDACIONES locales — solo las pre-aprobadas',
      'PAQUETES — contenido exacto y vigencia',
      'DISPONIBILIDAD — siempre del sistema real',
    ],
    crisisProtocols: [
      'HUESPED INSATISFECHO: En boutique, la queja se siente personal. Escalar a dueno inmediatamente.',
      'RESENA NEGATIVA en proceso: Intentar resolver ANTES de que publiquen. Ofrecer compensacion personalizada.',
    ],
    fallbackPhrase,
  },

  motel: {
    vertical: 'motel',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'Motel',
    software: [
      { name: 'SoftwareParaMoteles.com', price: '$999.99 MXN/mes/PC', description: 'PMS unico para moteles mexicanos — domotica, anti-robo, tarifas por hora' },
      { name: 'Saturn App', price: 'Custom', description: 'QR room service + housekeeping' },
    ],
    apis: [
      'SoftwareParaMoteles.com — integracion domotica propietaria, limited API',
    ],
    topFaqs: [
      'Cuanto cuesta por hora/tiempo?',
      'Que tipos de habitacion tienen?',
      'Que amenidades incluye?',
      'El estacionamiento es privado/cubierto?',
      'Que metodos de pago aceptan?',
      'Hay disponibilidad ahorita?',
      'Como es el proceso de check-in?',
      'Tienen habitacion con jacuzzi?',
      'Es discreto?',
      'Tienen programa de cliente frecuente?',
    ],
    neverHallucinate: [
      'TARIFAS — varian por dia, hora, tipo de habitacion',
      'DISPONIBILIDAD — debe consultar sistema real',
      'AMENIDADES por habitacion — no todas son iguales',
      'PRIVACIDAD — nunca comprometer discrecion del cliente',
    ],
    crisisProtocols: [
      'EMERGENCIA MEDICA en habitacion: 911. Personal debe poder acceder.',
      'SITUACION DE VIOLENCIA: 911. Protocolo de seguridad. CCTV de areas comunes (NO habitaciones).',
      'ROBO hormiga por personal: Sistema domotico anti-robo con camaras en accesos.',
    ],
    fallbackPhrase,
  },

  glamping: {
    vertical: 'glamping',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'Glamping',
    software: [
      { name: 'ResNexus', price: 'Per-unit pricing', description: 'PMS outdoor hospitality + Glamping Hub' },
      { name: 'Cloudbeds', price: '$108+ USD/mes', description: 'Para multi-property' },
    ],
    apis: [
      'ResNexus API',
      'Cloudbeds API',
      'Glamping Hub partner portal',
    ],
    topFaqs: [
      'Cuanto cuesta por noche?',
      'Que incluye?',
      'Como llego?',
      'Tienen WiFi/senal?',
      'Que pasa si llueve?',
      'Que actividades ofrecen?',
      'Es seguro para ninos?',
      'Aceptan mascotas?',
      'Cuantas personas caben?',
      'Tienen bano privado?',
    ],
    neverHallucinate: [
      'CLIMA — NUNCA garantizar condiciones climaticas',
      'AVISTAMIENTOS de fauna — no prometer',
      'ACTIVIDADES estacionales — verificar disponibilidad real',
      'CONECTIVIDAD — muchos son intencionalmente remotos',
      'ACCESO por carretera — condiciones cambian por temporada',
    ],
    crisisProtocols: [
      'TORMENTA ELECTRICA: Evacuacion a zona segura. Comunicar protocolo de seguridad.',
      'PICADURA/MORDEDURA animal: Primeros auxilios, hospital mas cercano. Documentar especie.',
      'LESION en actividad outdoor: Primeros auxilios, 911, IMSS mas cercano.',
    ],
    fallbackPhrase,
  },

  bb_hostal: {
    vertical: 'bb_hostal',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'B&B / Hostal',
    software: [
      { name: 'Beds24', price: '~$302 MXN/mes', description: 'PMS + channel manager mas barato' },
      { name: 'HostelSnap', price: '$0.15/guest night', description: 'Especifico hostales' },
      { name: 'Cloudbeds', price: '$108+ USD/mes', description: 'Con gestion de dormitorios' },
    ],
    apis: [
      'Beds24 API',
      'Cloudbeds API',
      'Hostelworld Connectivity API',
    ],
    topFaqs: [
      'Tienen camas disponibles para esta noche?',
      'Cual es la diferencia entre dorm y privada?',
      'Tienen lockers? Necesito mi propio candado?',
      'Hay cocina?',
      'Tienen area comun/eventos?',
      'Pueden ayudar a reservar tours?',
      'Hay lavanderia?',
      'El WiFi es rapido para trabajar?',
      'Horario de checkout? Puedo guardar maleta?',
      'Descuentos por grupo?',
    ],
    neverHallucinate: [
      'DISPONIBILIDAD de camas — cambiar por hora en temporada alta',
      'EVENTOS — no inventar actividades que no existen',
      'PRECIOS — low-budget travelers son hipersensibles a centavos',
      'WIFI speed — no prometer mbps sin verificar',
    ],
    crisisProtocols: [
      'ROBO en dormitorio: CCTV en comunes, reporte policial, documentar.',
      'BED BUGS: Cuarentena inmediata, fumigacion, compensar afectados.',
      'CONFLICTO entre huespedes: Staff de-escalation, reasignar cuarto, quiet hours.',
    ],
    fallbackPhrase,
  },

  resort: {
    vertical: 'resort',
    category: 'HOSPEDAJE_Y_TURISMO',
    displayName: 'Resort All-Inclusive',
    software: [
      { name: 'Oracle MICROS Simphony', price: 'Enterprise pricing', description: 'Multi-outlet POS' },
      { name: 'Oracle Opera Cloud', price: 'Enterprise pricing', description: 'PMS' },
      { name: 'Book4Time', price: 'Custom', description: 'Spa booking + revenue mgmt' },
      { name: 'Agilysys InfoGenesis', price: 'Enterprise', description: 'POS aprobado por IHG y Marriott' },
    ],
    apis: [
      'Oracle Opera REST API',
      'MICROS Simphony API',
      'Book4Time API',
      'Event Temple API',
    ],
    topFaqs: [
      'Que incluye el all-inclusive?',
      'Tienen disponibilidad para [fechas]?',
      'Como llego desde el aeropuerto?',
      'Que restaurantes tienen? Necesito reservacion?',
      'Que actividades hay?',
      'Tienen spa? Cuanto cuesta?',
      'Hay kids club?',
      'Pueden ayudar a planear una boda?',
      'Politica de cancelacion?',
      'Que moneda aceptan? Tipo de cambio?',
    ],
    neverHallucinate: [
      'QUE INCLUYE EL AI — el error mas comun y costoso. Si no esta claro, referir.',
      'TARIFAS — jamas inventar, varian por canal/temporada/demanda',
      'AMENIDADES por habitacion — no todas tienen jacuzzi/vista al mar',
      'SPA precios — no estan incluidos y son premium',
      'ACTIVIDADES — horarios cambian por temporada/clima',
    ],
    crisisProtocols: [
      'HURACAN: Protocolo completo 72h-36h-durante-post. Cancelaciones sin penalizacion. Reubicacion a property hermana.',
      'INTOXICACION MASIVA: COFEPRIS. Aislamiento de buffet. Comunicacion de crisis.',
      'OVERBOOKING: Reubicacion a hotel comparable, noche gratis, transporte, compensacion.',
    ],
    fallbackPhrase,
  },
};
