import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const saludMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  dental: {
    vertical: 'dental',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Consultorio Dental',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda + teleconsulta' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'Expediente clinico electronico + agenda' },
      { name: 'Dentrix', price: '$3,000-8,000 MXN/mes', description: 'PMS dental completo con radiografias' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS + recordatorios WhatsApp' },
      { name: 'Clip', price: '$299-4,999 MXN hardware', description: 'Terminal de pago 3.6%+IVA' },
      { name: 'Facturapi', price: '$199-999 MXN/mes', description: 'CFDI 4.0 via API REST' },
    ],
    apis: [
      'Doctoralia API (partners)',
      'Huli REST API (Pro+)',
      'AgendaPro REST API (Pro $4,500/mes)',
      'Google Calendar API',
      'Facturapi REST API',
      'Clip Developer API',
    ],
    topFaqs: [
      'Cuanto cuesta una limpieza dental?',
      'Tienen cita disponible para hoy/manana?',
      'Cuanto cuesta la ortodoncia y cuanto dura?',
      'Aceptan mi seguro dental?',
      'Me duele una muela, que hago?',
      'Cuanto cuesta un implante dental?',
      'Se puede pagar a meses sin intereses?',
      'Cuanto dura un blanqueamiento?',
      'Pueden facturar?',
      'Donde estan ubicados y tienen estacionamiento?',
    ],
    neverHallucinate: [
      'PRECIOS de tratamientos — varian por caso, material, complejidad',
      'DISPONIBILIDAD de citas — debe consultar agenda real',
      'DIAGNOSTICOS — nunca diagnosticar por chat, siempre valoracion presencial',
      'DURACION de tratamientos de ortodoncia — depende 100% del caso',
      'MATERIALES O MARCAS — si no esta en el contexto, no inventar',
      'CONTRAINDICACIONES medicas — embarazo, anticoagulantes, diabetes',
      'COBERTURA de seguros dentales — varia por plan y poliza',
      'RESULTADOS esteticos — nunca prometer resultados especificos',
    ],
    crisisProtocols: [
      'EMERGENCIA DENTAL (dolor severo, traumatismo): Dar numero de urgencias directo. Si no hay, referir a urgencias hospitalarias.',
      'REACCION ALERGICA post-tratamiento: Indicar llamar 911 si hay dificultad para respirar. Registrar producto/lote usado.',
      'QUEJA POR MAL TRATAMIENTO: Escuchar, documentar, escalar a titular. Nunca admitir culpa ni argumentar.',
      'COFEPRIS/CONAMED: Si mencionan queja formal, escalar inmediatamente a titular con todos los detalles.',
    ],
    fallbackPhrase,
  },

  medico: {
    vertical: 'medico',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Consultorio Medico',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  nutriologa: {
    vertical: 'nutriologa',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Nutriologa',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  psicologo: {
    vertical: 'psicologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Psicologo',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  dermatologo: {
    vertical: 'dermatologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Dermatologo',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  ginecologo: {
    vertical: 'ginecologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Ginecologo',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  pediatra: {
    vertical: 'pediatra',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Pediatra',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  oftalmologo: {
    vertical: 'oftalmologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Oftalmologo',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  farmacia: {
    vertical: 'farmacia',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Farmacia',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },

  veterinaria: {
    vertical: 'veterinaria',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Veterinaria',
    software: [],
    apis: [],
    topFaqs: [],
    neverHallucinate: [],
    crisisProtocols: [],
    fallbackPhrase,
  },
};
