import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const saludMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  dental: {
    vertical: 'dental',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Consultorio Dental',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda + teleconsulta' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'Expediente clinico electronico + agenda' },
      { name: 'Dentrix', price: '$3,000-8,000 MXN/mes', description: 'PMS dental completo con radiografias' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS + recordatorios WhatsApp' },
      { name: 'Clip', price: '$299-4,999 MXN hardware', description: 'Terminal de pago 3.6%+IVA' },
      { name: 'Facturapi', price: '$199-999 MXN/mes', description: 'CFDI 4.0 via API REST' },
    ],
    apis: [
      'Doctoralia API (partners)',
      'Huli REST API (Pro+)',
      'AgendaPro REST API (Pro $4,500/mes)',
      'Google Calendar API',
      'Facturapi REST API',
      'Clip Developer API',
    ],
    topFaqs: [
      'Cuanto cuesta una limpieza dental?',
      'Tienen cita disponible para hoy/manana?',
      'Cuanto cuesta la ortodoncia y cuanto dura?',
      'Aceptan mi seguro dental?',
      'Me duele una muela, que hago?',
      'Cuanto cuesta un implante dental?',
      'Se puede pagar a meses sin intereses?',
      'Cuanto dura un blanqueamiento?',
      'Pueden facturar?',
      'Donde estan ubicados y tienen estacionamiento?',
    ],
    neverHallucinate: [
      'PRECIOS de tratamientos — varian por caso, material, complejidad',
      'DISPONIBILIDAD de citas — debe consultar agenda real',
      'DIAGNOSTICOS — nunca diagnosticar por chat, siempre valoracion presencial',
      'DURACION de tratamientos de ortodoncia — depende 100% del caso',
      'MATERIALES O MARCAS — si no esta en el contexto, no inventar',
      'CONTRAINDICACIONES medicas — embarazo, anticoagulantes, diabetes',
      'COBERTURA de seguros dentales — varia por plan y poliza',
      'RESULTADOS esteticos — nunca prometer resultados especificos',
    ],
    crisisProtocols: [
      'EMERGENCIA DENTAL (dolor severo, traumatismo): Dar numero de urgencias directo. Si no hay, referir a urgencias hospitalarias.',
      'REACCION ALERGICA post-tratamiento: Indicar llamar 911 si hay dificultad para respirar. Registrar producto/lote usado.',
      'QUEJA POR MAL TRATAMIENTO: Escuchar, documentar, escalar a titular. Nunca admitir culpa ni argumentar.',
      'COFEPRIS/CONAMED: Si mencionan queja formal, escalar inmediatamente a titular con todos los detalles.',
    ],
    fallbackPhrase,
  },

  medico: {
    vertical: 'medico',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Consultorio Medico General',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda + teleconsulta + recetas digitales' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'EHR + agenda + teleconsulta' },
      { name: 'Luna Salud', price: '$599-1,899 MXN/mes', description: 'Expediente + recetas + laboratorios' },
      { name: 'iDoctor', price: '$499-1,999 MXN/mes', description: 'Gestion medica integral' },
      { name: 'Clip/Zettle', price: '$299-4,999 MXN', description: 'Terminal de pago' },
    ],
    apis: [
      'Doctoralia API',
      'Huli REST API',
      'Google Calendar API',
      'Facturapi REST API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta?',
      'Tienen cita disponible?',
      'Atienden por teleconsulta?',
      'Que debo llevar a la primera cita?',
      'Aceptan mi seguro?',
      'Hacen certificados medicos? Cuanto cuestan?',
      'Cuales son sus horarios?',
      'Pueden facturar?',
      'Atienden urgencias?',
      'Donde estan ubicados?',
    ],
    neverHallucinate: [
      'DIAGNOSTICOS — absolutamente prohibido diagnosticar por chat',
      'DOSIS de medicamentos — nunca recetar ni ajustar dosis',
      'PRECIOS — siempre del contexto verificado',
      'DISPONIBILIDAD — consultar agenda real',
      'COBERTURA de seguros — depende de cada poliza',
      'RESULTADOS de estudios — nunca interpretar laboratorios por chat',
      'INTERACCIONES medicamentosas — referir siempre al medico',
    ],
    crisisProtocols: [
      'EMERGENCIA MEDICA: Si el paciente reporta dolor en pecho, dificultad para respirar, perdida de conciencia, hemorragia — INDICAR LLAMAR 911 INMEDIATAMENTE. No intentar diagnosticar.',
      'IDEACION SUICIDA: Si detecta senales, responder con empatia, proporcionar Linea de la Vida 800-911-2000, escalar a humano.',
      'QUEJA POR ATENCION: Documentar, escalar a medico titular. No argumentar ni minimizar.',
      'CONAMED: Si mencionan queja formal ante CONAMED, escalar inmediatamente.',
    ],
    fallbackPhrase,
  },

  nutriologa: {
    vertical: 'nutriologa',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Nutriologa',
    software: [
      { name: 'Nutrimind', price: '$899-2,499 MXN/mes', description: 'Planes alimentarios + antropometria' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + recordatorios' },
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + teleconsulta' },
      { name: 'Canva Pro', price: '$190 MXN/mes', description: 'Planes alimentarios visuales' },
    ],
    apis: [
      'AgendaPro REST API',
      'Google Calendar API',
      'Doctoralia API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta de nutricion?',
      'Que incluye la primera consulta?',
      'En cuanto tiempo vere resultados?',
      'Atienden por teleconsulta?',
      'Necesito llevar analisis de sangre?',
      'Hacen dietas para diabeticos/hipertensos?',
      'Atienden a ninos?',
      'Trabajan con planes veganos/vegetarianos?',
      'Tienen paquetes?',
      'Me van a hacer pasar hambre?',
    ],
    neverHallucinate: [
      'PLANES ALIMENTARIOS — nunca dar menus o recomendaciones dieteticas especificas por chat',
      'CALORIAS o MACROS — no calcular sin valoracion',
      'SUPLEMENTOS — no recomendar sin evaluacion',
      'PERDIDA DE PESO estimada — no prometer kilos ni tiempos',
      'DIAGNOSTICOS nutricionales — requieren valoracion presencial',
      'PRECIOS — del contexto verificado unicamente',
    ],
    crisisProtocols: [
      'TCA DETECTADO: Si el paciente describe purgas, restriccion extrema, atracones — responder con empatia, NO juzgar, escalar a nutriologa inmediatamente.',
      'DESHIDRATACION/DESMAYO: Referir a urgencias medicas, 911.',
      'REACCION ALERGICA a alimento: 911 si hay dificultad respiratoria. Documentar alimento.',
    ],
    fallbackPhrase,
  },

  psicologo: {
    vertical: 'psicologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Psicologo',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + teleconsulta' },
      { name: 'SimplePractice', price: '$29-99 USD/mes', description: 'EHR + teletherapy + notas' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + recordatorios' },
      { name: 'Zoom Pro', price: '$219 MXN/mes', description: 'Teleconsulta con encriptacion' },
    ],
    apis: [
      'AgendaPro REST API',
      'Google Calendar API',
      'Zoom API',
    ],
    topFaqs: [
      'Cuanto cuesta la sesion de terapia?',
      'Como se si necesito terapia?',
      'Es presencial o en linea?',
      'Cuanto dura el proceso terapeutico?',
      'Todo lo que diga es confidencial?',
      'Atienden parejas/adolescentes/ninos?',
      'Que enfoque terapeutico manejan?',
      'Aceptan seguro de gastos medicos?',
      'Tienen cita disponible esta semana?',
      'Cual es la diferencia entre psicologo y psiquiatra?',
    ],
    neverHallucinate: [
      'DIAGNOSTICOS — prohibido diagnosticar por chat (depresion, ansiedad, etc.)',
      'MEDICACION — nunca recomendar, ajustar ni opinar sobre psicotropicos',
      'TECNICAS TERAPEUTICAS — no aplicar ejercicios sin contexto clinico',
      'PREDICCIONES de duracion del tratamiento — cada caso es unico',
      'PRECIOS — solo del contexto verificado',
      'DISPONIBILIDAD — consultar agenda real',
    ],
    crisisProtocols: [
      'IDEACION SUICIDA: Responder con empatia genuina. \'Entiendo que estas pasando por un momento muy dificil. Tu vida importa.\' Proporcionar Linea de la Vida: 800-911-2000 (24/7). Si hay plan concreto e inmediato: 911. Escalar a psicologo INMEDIATAMENTE.',
      'AUTOLESION: No juzgar. Escalar a psicologo. Proporcionar recursos de crisis.',
      'VIOLENCIA DOMESTICA: Proporcionar linea SAPTEL 55-5259-8121. No presionar a denunciar. Escalar.',
      'ABUSO A MENORES: Obligacion legal de reporte. Escalar INMEDIATAMENTE a psicologo y autoridades.',
    ],
    fallbackPhrase,
  },

  dermatologo: {
    vertical: 'dermatologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Dermatologo',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'EHR + fotos clinicas' },
      { name: 'DermaVault', price: 'Quote-based', description: 'Dermatology-specific EHR' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + POS' },
    ],
    apis: [
      'Doctoralia API',
      'Huli REST API',
      'AgendaPro REST API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta dermatologica?',
      'Atienden acne? Que tratamientos tienen?',
      'Cuanto cuesta quitar una verruga/lunar?',
      'Tienen laser? Para que sirve?',
      'Cuanto cuesta el botox/rellenos?',
      'Atienden caida de cabello?',
      'Es necesario ir presencial o pueden atender por video?',
      'Cuantas sesiones necesito de [tratamiento]?',
      'Aceptan seguro de gastos medicos?',
      'Tienen cita disponible?',
    ],
    neverHallucinate: [
      'DIAGNOSTICOS dermatologicos — nunca diagnosticar lesiones por foto/chat',
      'PRECIOS de procedimientos — varian enormemente por extension/sesiones',
      'RESULTADOS esteticos — nunca prometer resultados',
      'NUMERO DE SESIONES — depende de cada caso',
      'PRODUCTOS/RECETAS — no recomendar sin valoracion',
      'CANCER DE PIEL — si preguntan por lunar sospechoso, urgir consulta presencial',
    ],
    crisisProtocols: [
      'REACCION ALERGICA severa (angioedema, anafilaxia): 911 inmediatamente.',
      'LUNAR SOSPECHOSO: Urgir cita presencial prioritaria. No tranquilizar ni alarmar.',
      'REACCION ADVERSA post-procedimiento: Contactar al dermatologo directamente. No dar indicaciones medicas.',
    ],
    fallbackPhrase,
  },

  ginecologo: {
    vertical: 'ginecologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Ginecologo',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda + teleconsulta' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'EHR con modulo ginecologico' },
      { name: 'SaludTotal', price: '$999-3,499 MXN/mes', description: 'Gestion integral gineco-obstetrica' },
    ],
    apis: [
      'Doctoralia API',
      'Huli REST API',
      'Google Calendar API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta ginecologica?',
      'El ultrasonido esta incluido en la consulta?',
      'Cuanto cuesta el paquete de control prenatal?',
      'Cuanto cuesta un parto/cesarea con ustedes?',
      'Que metodos anticonceptivos manejan y cuanto cuestan?',
      'Atienden urgencias obstetricas?',
      'Aceptan mi seguro para el parto?',
      'Cuanto cuesta el Papanicolaou?',
      'Pueden atender por teleconsulta?',
      'Donde estan ubicados / en que hospital operan?',
    ],
    neverHallucinate: [
      'PRECIOS de parto/cesarea — varian enormemente por hospital, complicaciones',
      'COBERTURA de seguros para parto — verificar con aseguradora',
      'SEMANAS DE EMBARAZO o fechas — nunca calcular sin datos medicos',
      'DIAGNOSTICOS — nunca diagnosticar por chat',
      'URGENCIAS OBSTETRICAS — siempre referir a atencion presencial inmediata',
      'MEDICACION en embarazo — absolutamente prohibido recomendar',
    ],
    crisisProtocols: [
      'SANGRADO EN EMBARAZO: \'Acuda INMEDIATAMENTE a urgencias. Llame al 911 o dirijase al hospital mas cercano.\' + dar numero de urgencias del doctor.',
      'CONTRACCIONES PREMATURAS: Urgir atencion inmediata. No tranquilizar.',
      'PERDIDA GESTACIONAL: Maxima empatia. No usar frases hechas. Escalar a humano.',
      'VIOLENCIA OBSTETRICA: Documentar, escalar. Informar de derechos ante CONAMED.',
    ],
    fallbackPhrase,
  },

  pediatra: {
    vertical: 'pediatra',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Pediatra',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'EHR pediatrico con curvas de crecimiento' },
      { name: 'PediatricsEHR', price: 'Custom pricing', description: 'Especifico para pediatria' },
    ],
    apis: [
      'Doctoralia API',
      'Huli REST API',
      'Google Calendar API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta pediatrica?',
      'Mi bebe tiene fiebre, que hago?',
      'Tienen vacunas? Cuales y cuanto cuestan?',
      'A que edad corresponde la siguiente vacuna?',
      'Mi hijo tiene diarrea/vomito, debo llevarlo?',
      'Atienden urgencias?',
      'A partir de que edad atienden?',
      'Hacen control del nino sano?',
      'Aceptan seguro de gastos medicos?',
      'Pueden atender por teleconsulta?',
    ],
    neverHallucinate: [
      'DOSIS de medicamentos pediatricos — NUNCA, varian por peso/edad',
      'DIAGNOSTICOS — prohibido diagnosticar por chat',
      'VACUNAS — no inventar esquemas, precios ni disponibilidad',
      'URGENCIA vs. no urgencia — si hay duda, SIEMPRE referir presencial',
      'EDAD GESTACIONAL / PESO / TALLA normales — no interpretar sin datos',
      'ALIMENTACION infantil — no dar indicaciones especificas sin valoracion',
    ],
    crisisProtocols: [
      'FIEBRE ALTA en lactante (<3 meses): URGENCIA REAL. \'Lleve a su bebe a urgencias INMEDIATAMENTE. Llame al 911.\' + numero de pediatra.',
      'DIFICULTAD RESPIRATORIA: 911 inmediatamente. No intentar orientar.',
      'CONVULSIONES: 911. Instrucciones basicas: poner de lado, no introducir nada en boca.',
      'INTOXICACION/INGESTA DE SUSTANCIA: 911 + Centro de Informacion Toxicologica UNAM.',
      'SOSPECHA DE MALTRATO INFANTIL: Obligacion legal de reporte. Escalar inmediatamente.',
    ],
    fallbackPhrase,
  },

  oftalmologo: {
    vertical: 'oftalmologo',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Oftalmologo',
    software: [
      { name: 'Doctoralia', price: '$1,500-4,500 MXN/mes', description: 'Marketplace + agenda' },
      { name: 'Huli', price: '$799-2,499 MXN/mes', description: 'EHR + agenda' },
      { name: 'OphthalmicEHR', price: 'Custom pricing', description: 'Especifico para oftalmologia' },
    ],
    apis: [
      'Doctoralia API',
      'Huli REST API',
      'Google Calendar API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta con el oftalmologo?',
      'Cuanto cuesta la cirugia de cataratas?',
      'Cuanto cuesta la cirugia LASIK?',
      'La graduacion esta incluida en la consulta?',
      'Venden lentes/armazones?',
      'Atienden ninos?',
      'Que estudios hacen en la primera consulta?',
      'Aceptan seguro de gastos medicos?',
      'Se puede pagar a meses sin intereses?',
      'Atienden urgencias?',
    ],
    neverHallucinate: [
      'PRECIOS de cirugias — varian enormemente por tecnica, lente intraocular, complejidad',
      'GRADUACION — nunca dar resultados de graduacion sin examen',
      'DIAGNOSTICOS — prohibido diagnosticar por chat',
      'CANDIDATURA para LASIK — requiere estudios presenciales',
      'URGENCIAS — perdida de vision siempre es urgencia real, referir inmediatamente',
    ],
    crisisProtocols: [
      'PERDIDA SUBITA DE VISION: URGENCIA REAL. \'Acuda a urgencias INMEDIATAMENTE.\' + numero de oftalmologo.',
      'TRAUMATISMO OCULAR: 911. No tocar el ojo, no enjuagar con quimicos. Cubrir sin presionar.',
      'QUEMADURA QUIMICA EN OJO: Enjuagar con agua limpia 15-20 minutos MIENTRAS va a urgencias.',
    ],
    fallbackPhrase,
  },

  farmacia: {
    vertical: 'farmacia',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Farmacia',
    software: [
      { name: 'SICAR', price: '$4,940 MXN unica vez', description: 'POS + inventario con caducidades' },
      { name: 'Eleventa', price: '$1,499 MXN licencia', description: 'POS con productos precargados' },
      { name: 'FarmaciaPOS', price: 'Custom', description: 'Especifico para farmacias' },
      { name: 'Clip', price: '$299+ MXN', description: 'Terminal de pago' },
    ],
    apis: [
      'SICAR limited',
      'Eleventa limited',
      'Clip Developer API',
    ],
    topFaqs: [
      'Tienen [medicamento]?',
      'Cuanto cuesta [medicamento]?',
      'Necesito receta para [medicamento]?',
      'Tienen servicio a domicilio?',
      'Que horario tienen?',
      'Aplican inyecciones?',
      'Tienen generico de [marca]?',
      'Aceptan tarjeta/vales?',
      'Pueden facturar?',
      'Tienen prueba rapida de COVID/embarazo?',
    ],
    neverHallucinate: [
      'PRECIOS de medicamentos — cambian frecuentemente',
      'DISPONIBILIDAD de medicamentos — inventario cambia constantemente',
      'INDICACIONES medicas — NUNCA recomendar medicamentos, dosis, o usos',
      'INTERACCIONES medicamentosas — referir al medico',
      'CLASIFICACION de receta — si necesita o no receta medica',
    ],
    crisisProtocols: [
      'INTOXICACION: Referir a 911 + Centro Toxicologico. No dar indicaciones de lavado gastrico.',
      'MEDICAMENTO EQUIVOCADO dispensado: Escalar inmediatamente a farmaceutico. Documentar lote.',
      'REACCION ADVERSA a medicamento: Referir a urgencias. Documentar medicamento y lote.',
    ],
    fallbackPhrase,
  },

  veterinaria: {
    vertical: 'veterinaria',
    category: 'SALUD_Y_BIENESTAR',
    displayName: 'Veterinaria',
    software: [
      { name: 'Veterinaria Digital', price: '$599-2,499 MXN/mes', description: 'Expediente + agenda + inventario' },
      { name: 'DoggiePad', price: '$399-1,499 MXN/mes', description: 'Gestion veterinaria integral' },
      { name: 'AgendaPro', price: '$299-4,500 MXN/mes', description: 'Agenda + recordatorios' },
      { name: 'SICAR', price: '$4,940 MXN unica vez', description: 'POS + inventario para petshop' },
    ],
    apis: [
      'AgendaPro REST API',
      'Google Calendar API',
    ],
    topFaqs: [
      'Cuanto cuesta la consulta veterinaria?',
      'Que vacunas necesita mi cachorro/gatito?',
      'Cuanto cuesta esterilizar?',
      'Atienden urgencias?',
      'Tienen servicio de bano/estetica? Cuanto cuesta?',
      'Cuanto cuesta el hospedaje para mi mascota?',
      'Atienden animales exoticos?',
      'Que debo llevar a la primera consulta?',
      'Tienen servicio a domicilio?',
      'Venden alimento/accesorios?',
    ],
    neverHallucinate: [
      'DIAGNOSTICOS — prohibido diagnosticar por chat',
      'MEDICACION — nunca recomendar medicamentos ni dosis para animales',
      'PRECIOS de cirugias — varian por peso, edad, complejidad',
      'URGENCIA vs. no urgencia — si hay duda, referir presencial',
      'VACUNAS — no inventar esquemas ni disponibilidad',
      'RAZAS de riesgo — no hacer generalizaciones',
    ],
    crisisProtocols: [
      'ENVENENAMIENTO: \'Lleve a su mascota INMEDIATAMENTE a la clinica. No induzca el vomito a menos que un veterinario lo indique.\' + numero urgencias.',
      'ATROPELLO: Mover al animal con cuidado (puede morder por dolor). Acudir a urgencias. Documentar.',
      'MORDEDURA de serpiente/alacran: Urgencia inmediata. No aplicar torniquete. Acudir a clinica.',
      'EUTANASIA: Tema extremadamente sensible. Maxima empatia. Escalar a veterinario para asesoria.',
    ],
    fallbackPhrase,
  },
};
