import type { VerticalEnum, VerticalMetadata } from '../types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const serviciosMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  contable_legal: {
    vertical: 'contable_legal',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Contable / Legal',
    software: [
      { name: 'CONTPAQi', price: '$2,690-10,090 MXN/ano+IVA', description: 'Lider contabilidad MX — SDK + API Cloud' },
      { name: 'Siigo Aspel', price: '$243-688 MXN/mes', description: '1M+ usuarios — COI, SAE, NOI' },
      { name: 'Bind ERP', price: '$700-1,700 MXN/mes', description: 'Cloud-native + API + Zapier' },
      { name: 'Clientify', price: '$680-1,370 MXN/mes', description: 'CRM WhatsApp-native' },
    ],
    apis: [
      'CONTPAQi REST API (developers.contpaqinube.com) + .NET SDK',
      'Aspel/Siigo Nube API',
      'Bind ERP REST API + Zapier',
      'Clientify REST API + webhooks',
    ],
    topFaqs: [
      'Cuando debo presentar mi declaracion mensual/anual?',
      'Como emito o cancelo una factura CFDI?',
      'Que regimen fiscal me conviene?',
      'Como tramito mi RFC?',
      'Cuanto debo pagar de ISR/IVA este mes?',
      'Necesito complemento de pago?',
      'Que deducciones puedo aplicar?',
      'Recibi carta invitacion del SAT — que hago?',
      'Cuanto cobran y que incluyen?',
      'Pueden regularizar ejercicios anteriores?',
    ],
    neverHallucinate: [
      'TASAS DE ISR (1.92-35%) — NUNCA inventar',
      'PLAZOS FISCALES — dia 17 mensual, marzo PF anual, abril PM',
      'ARTICULOS DEL CFF — no citar si no esta seguro',
      'MONTOS DE MULTAS — verificar',
      'CALCULO DE IMPUESTOS — jamas calcular sin datos del cliente',
      'RESICO thresholds — cambian con reformas fiscales',
    ],
    crisisProtocols: [
      'AUDITORIA SAT: \'NO responda al SAT sin asesoria. Un especialista le contactara en [X] horas.\' Escalar en 15 minutos.',
      'DEADLINE FISCAL manana: Evaluar si es posible presentar, calcular recargos, priorizar.',
      'e.FIRMA/CSD comprometida: REVOCAR CSD INMEDIATAMENTE en sat.gob.mx. Notificar socio en 30 min.',
      'EMBARGO/CONGELAMIENTO de cuentas: Escalar a socio URGENTE. Referir a abogado fiscal si no son abogados.',
    ],
    fallbackPhrase,
  },

  seguros: {
    vertical: 'seguros',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Agente de Seguros',
    software: [
      { name: 'SICAS Online', price: 'Custom pricing', description: 'Lider gestion polizas 20+ anos' },
      { name: 'SIGA Seguros', price: 'Tiered plans', description: 'CRM cloud + AI PDF reader' },
      { name: 'MOVI Digital', price: 'Custom', description: 'Multicotizador #1 Mexico' },
      { name: 'Segutrends', price: 'Custom', description: 'Multicotizador 20+ anos — REST API' },
      { name: 'HubSpot', price: 'Gratis-$2,000 MXN/user/mes', description: 'CRM general' },
    ],
    apis: [
      'Segutrends REST API/Web Services (mejor opcion programatica)',
      'HubSpot REST API',
      'Zoho CRM REST API',
      'Salesforce API',
    ],
    topFaqs: [
      'Cuanto cuesta mi seguro de auto?',
      'Que cubre mi poliza?',
      'Como reporto un siniestro?',
      'Que es el deducible y cuanto pago?',
      'Como renuevo mi poliza?',
      'Como cancelo?',
      'Cuanto tarda el pago del siniestro?',
      'El seguro de auto es obligatorio?',
      'Como presento queja ante CONDUSEF?',
      'Que documentos necesito?',
    ],
    neverHallucinate: [
      'COBERTURAS — cada poliza es unica. NUNCA inventar que cubre o no cubre.',
      'DEDUCIBLES — varian por plan y endorso',
      'PRIMAS — dependen de 10+ variables de riesgo',
      'EXCLUSIONES y periodos de espera — cada producto es diferente',
      'STATUS DE RECLAMACION — no inventar',
      'COMISIONES — confidenciales',
      'COMPARATIVAS entre aseguradoras — datos verificados unicamente',
    ],
    crisisProtocols: [
      'SINIESTRO MAYOR (choque, hospitalizacion): Proporcionar numero de emergencia de la aseguradora INMEDIATAMENTE. Guiar FNOL (datos basicos del siniestro).',
      'QUEJA CONDUSEF: Orientar sobre proceso. NUNCA obstruir. Plazo de 2 anos para presentar. Aseguradora tiene 30 dias habiles.',
      'FALLECIMIENTO del asegurado (vida): Maxima empatia. Guiar a beneficiarios sobre documentos. Escalar a agente.',
      'FRAUDE detectado: Documentar, no proceder, escalar a compliance.',
    ],
    fallbackPhrase,
  },

  taller_mecanico: {
    vertical: 'taller_mecanico',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Taller Mecanico',
    software: [
      { name: 'Mecanica.mx', price: '$649-2,390 MXN/mes', description: 'Lider con 600+ talleres MX — WhatsApp nativo' },
      { name: 'Kordata', price: '$630-741 MXN/mes+IVA', description: 'POS + CFDI + contrato PROFECO' },
      { name: 'AutoSoft Taller', price: '$320-620 MXN/mes', description: 'CFDI 4.0 integrado' },
    ],
    apis: [
      'Orderry REST API + webhooks (opcion con API)',
      'Mecanica.mx WhatsApp nativo (custom integrations)',
      'AutoSoft limited',
    ],
    topFaqs: [
      'Cuanto cuesta la reparacion de [X]?',
      'Cuanto tiempo tardara?',
      'Usan refacciones originales o genericas?',
      'Cual es la garantia?',
      'Necesito cita?',
      'Puedo llevar mis propias refacciones?',
      'Que metodos de pago aceptan?',
      'Cuando toca el proximo servicio?',
      'Hacen diagnostico con escaner?',
      'Emiten factura?',
    ],
    neverHallucinate: [
      'PRECIOS de reparacion — varian por vehiculo, refacciones, complejidad',
      'DIAGNOSTICOS — NUNCA diagnosticar por chat sin ver el vehiculo',
      'TIEMPO de reparacion — depende de disponibilidad de refacciones',
      'ESPECIFICACIONES TECNICAS — error puede causar dano al vehiculo',
      'GARANTIA — terminos exactos per PROFECO',
      'DISPONIBILIDAD de refacciones — verificar con proveedor',
    ],
    crisisProtocols: [
      'DANO AL VEHICULO durante reparacion: Documentar con fotos. Seguro de RC del taller. NUNCA admitir por chat. Escalar a dueno.',
      'QUEJA PROFECO: PROFECO sanciono 197 de 409 talleres inspeccionados. Verificar contrato registrado, lista de precios visible, garantia documentada.',
      'VEHICULO NO ARRANCA despues de servicio: Prioridad maxima. Grua si necesario. Revision inmediata sin costo.',
      'DISPUTA DE PRECIO: Referir a presupuesto firmado. Per PROFECO, NO pueden cobrar mas sin autorizacion escrita.',
    ],
    fallbackPhrase,
  },

  escuela: {
    vertical: 'escuela',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Escuela Privada',
    software: [
      { name: 'GES Educativo', price: 'Custom', description: 'Lider MX — control escolar + LMS + CFDI' },
      { name: 'Grado Escolar', price: 'Custom', description: 'Boletas + cobranza + QR access' },
      { name: 'Phidias', price: 'Custom (AWS)', description: 'RESTful API — academico + tesoreria + comunicacion' },
      { name: 'GestiEscolar', price: 'Per-student', description: 'Cloud' },
    ],
    apis: [
      'Phidias RESTful API (mejor opcion)',
      'Conekta REST API (cobro de colegiaturas)',
      'Openpay REST API (BBVA)',
      'Moodle REST/SOAP API',
      'Google Classroom API',
    ],
    topFaqs: [
      'Cuales son los requisitos y fechas de inscripcion?',
      'Cuanto cuesta la colegiatura?',
      'Cuando son las vacaciones y puentes?',
      'Como consulto calificaciones?',
      'Donde compro el uniforme y lista de utiles?',
      'Hay servicio de transporte?',
      'Que actividades extracurriculares ofrecen?',
      'La escuela tiene RVOE?',
      'Politica de faltas?',
      'Puedo pagar con tarjeta/MSI? Que pasa si me atraso?',
    ],
    neverHallucinate: [
      'COLEGIATURAS — monto exacto, periodo, recargos',
      'RVOE — numero especifico alfanumerico. INVENTAR UNO ES POTENCIALMENTE ILEGAL.',
      'CALENDARIO SEP — fechas oficiales',
      'CALIFICACIONES/BOLETAS — documentos legales',
      'PERSONAL DOCENTE — no asignar maestros sin verificar',
      'BECAS — porcentajes y disponibilidad exactos',
      'POLITICAS disciplinarias — terminos exactos',
    ],
    crisisProtocols: [
      'EMERGENCIA de seguridad de alumno: Escalar INMEDIATAMENTE. 911 si hay riesgo fisico. Protocolo de reunion de padres.',
      'CIERRE POR EMERGENCIA (sismo, pandemia, inundacion): Modo broadcast con mensajes pre-aprobados. Instrucciones de recoger alumnos.',
      'DISPUTA DE PAGO: PROFECO: escuelas NO pueden retener boletas/constancias por adeudo. Deben entregar en 15 dias sin costo.',
      'BULLYING reportado: Reconocer con empatia. Escalar a orientacion educativa. Ley de NNA obliga protocolos anti-bullying. NUNCA investigar por chat.',
      'QUEJA PROFECO: Las 9 obligaciones de escuelas privadas per PROFECO deben cumplirse. Escalar a direccion.',
    ],
    fallbackPhrase,
  },

  agencia_digital: {
    vertical: 'agencia_digital',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Agencia Digital',
    software: [
      { name: 'Monday.com', price: '$171-361 MXN/user/mes', description: 'Project management' },
      { name: 'ClickUp', price: '$133-228 MXN/user/mes', description: 'PM all-in-one' },
      { name: 'Metricool', price: '$380-2,641 MXN/mes', description: 'Social media LATAM' },
      { name: 'Clientify', price: '$798 MXN/mes', description: 'CRM WhatsApp-native LATAM' },
      { name: 'Pipedrive', price: '$266-931 MXN/user/mes', description: 'Sales CRM' },
      { name: 'Semrush', price: '$2,229 MXN/mes', description: 'SEO' },
      { name: 'AgencyAnalytics', price: '$1,501-3,401 MXN/mes', description: 'Client reporting' },
    ],
    apis: [
      'Monday.com GraphQL API',
      'HubSpot REST API',
      'Pipedrive REST API',
      'Metricool API',
      'AgencyAnalytics API',
      'Google Analytics API',
      'Meta Marketing API',
      'PandaDoc API (contratos)',
      'Figma REST API + webhooks',
    ],
    topFaqs: [
      'Cuanto cuesta contratar una agencia?',
      'En cuanto tiempo vere resultados?',
      'Que metricas usan?',
      'Quien sera mi punto de contacto?',
      'Que incluye exactamente el paquete?',
      'Pueden mostrar casos de exito?',
      'Quien es dueno de las cuentas?',
      'Compromiso minimo?',
      'Como manejan una crisis en redes?',
      'Emiten factura CFDI?',
    ],
    neverHallucinate: [
      'METRICAS de campanas — clicks, CTR, ROAS, conversiones deben ser de datos reales',
      'TIMELINES de proyecto — no prometer sin verificar',
      'PRESUPUESTOS/COTIZACIONES — siempre requieren discovery',
      'SEO rankings — no prometer posiciones',
      'DATOS de competencia — solo verificados',
      'TERMINOS DE CONTRATO — cada cliente es diferente',
    ],
    crisisProtocols: [
      'CAMPANA CON ROAS < 1:1 por 7+ dias: Notificar performance manager. Call de emergencia con cliente en <24h. Plan de accion documentado.',
      'CRISIS EN REDES del cliente: Pausar TODOS los posts programados. Alertar agencia y cliente. Preparar holding statement.',
      'CAIDA DE PLATAFORMA (Meta, Google): Verificar status oficial. Tranquilizar cliente — es global, no es su cuenta.',
      'CLIENTE AMENAZA CON DEMANDAR: Escalar a director + asesor legal. No discutir terminos por chat.',
    ],
    fallbackPhrase,
  },

  fotografo: {
    vertical: 'fotografo',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Fotografo',
    software: [
      { name: 'Dubsado', price: '$630-990 MXN/mes', description: 'CRM + contratos + invoicing' },
      { name: 'Studio Ninja', price: '$448-657 MXN/mes', description: 'Photographer-specific CRM' },
      { name: 'Pixieset', price: 'Gratis-$720 MXN/mes', description: 'Galerias + website' },
      { name: 'ShootProof', price: 'Gratis-$540 MXN/mes', description: 'Galerias por # fotos' },
      { name: 'Calendly', price: 'Gratis-$360 MXN/user/mes', description: 'Scheduling con API' },
    ],
    apis: [
      'Calendly REST API (700+ integrations)',
      'Dubsado via Zapier (Premier)',
      'PandaDoc REST API (contratos)',
      'Google Calendar API',
    ],
    topFaqs: [
      'Cuanto cuestan tus paquetes?',
      'Tienes disponibilidad para [fecha]?',
      'Cuantas fotos editadas se entregan?',
      'En cuanto tiempo entregan la galeria?',
      'En que ubicaciones trabajan?',
      'Que debo usar / como me preparo?',
      'Ofrecen albumes impresos?',
      'Politica de cancelacion?',
      'Como funciona para bodas?',
      'Formas de pago?',
    ],
    neverHallucinate: [
      'PRECIOS — cada sesion se cotiza segun tipo, duracion, ubicacion, extras',
      'DISPONIBILIDAD — verificar calendario real. Doble booking = catastrofe',
      'FOTOS INCLUIDAS — numero exacto por paquete',
      'TIEMPO DE ENTREGA — no prometer menos del establecido',
      'ESTILO — no describir un estilo que no practican',
      'EQUIPO/SEGUNDO FOTOGRAFO — confirmar disponibilidad',
    ],
    crisisProtocols: [
      'FALLA DE EQUIPO durante evento: Backup obligatorio. Comunicar con transparencia si afecta resultado. Compensar si necesario.',
      'DOBLE BOOKING: NUNCA confirmar sin verificar calendario. Si sucede, referir a colega de confianza.',
      'CLIENTE INSATISFECHO con fotos: Empatizar. Ofrecer re-edicion o sesion complementaria. NUNCA prometer reembolso sin autorizacion del fotografo.',
      'CLIMA adverso en sesion outdoor: Plan B predefinido (indoor, reprogramar). Comunicar opciones proactivamente.',
      'QUEJA PROFECO: Cumplir contrato firmado. PROFECO sostiene precios y entregables contratados.',
    ],
    fallbackPhrase,
  },

  condominio: {
    vertical: 'condominio',
    category: 'SERVICIOS_PROFESIONALES',
    displayName: 'Administracion de Condominios',
    software: [
      { name: 'Admincondominio.com', price: 'Desde $399 MXN/mes', description: 'Plataforma de administracion de condominios — cuotas, bitacora y comunicados' },
      { name: 'Aspel AdminPaq', price: '$2,690-10,090 MXN/ano+IVA', description: 'Gestion de propiedades + cobranza + facturacion CFDI' },
      { name: 'Bitacora Digital', price: 'Custom pricing', description: 'App de bitacora y reportes para administradores' },
      { name: 'Sierraware', price: 'Custom pricing', description: 'ERP para fraccionamientos y condominios — residentes, cobranza, accesos' },
    ],
    apis: [
      'Conekta REST API (cobro de cuotas en linea — tarjeta, OXXO, SPEI)',
      'OpenPay REST API (pagos en linea + domiciliacion)',
      'Admincondominio.com API (estados de cuenta, solicitudes)',
      'Twilio API (notificaciones SMS / WhatsApp masivas a residentes)',
    ],
    topFaqs: [
      'Cuando vence mi cuota de mantenimiento?',
      'Como pago por transferencia? Cual es la CLABE?',
      'Cuanto es la penalizacion por pago tardio?',
      'Como reporto una fuga de agua o una falla?',
      'Puedo rentar mi departamento / casa?',
      'Puedo tener mascotas? Hay restricciones de raza o tamano?',
      'Cuando es la proxima asamblea de copropietarios?',
      'Hay servicio de vigilancia nocturna?',
      'Puedo hacer una remodelacion o obra?',
      'Cuando hay mantenimiento de la alberca / areas comunes?',
    ],
    neverHallucinate: [
      'ESTADO DE CUENTA INDIVIDUAL — no dar saldos ni adeudos sin consultar el sistema real',
      'FECHA EXACTA DE PROXIMA ASAMBLEA — verificar con la administracion',
      'DECISIONES DE JUNTA DIRECTIVA — solo informar lo que este en comunicados oficiales',
      'MONTOS DE CUOTAS EXTRAORDINARIAS — requieren aprobacion en asamblea',
      'ADEUDOS DE TERCEROS — nunca revelar informacion de otros condominios',
      'CAMBIOS AL REGLAMENTO — solo los oficialmente aprobados y vigentes',
    ],
    crisisProtocols: [
      'INCENDIO: Dar numero de Bomberos (911) de inmediato. Alertar al administrador urgente. NO dar instrucciones de apagado si no hay protocolo definido.',
      'FUGA DE GAS: Indicar: evacuar el area, NO encender luces ni aparatos electricos, llamar a la empresa de gas y al 911. Notificar al administrador.',
      'ROBO / INTRUSION: Dar numero de seguridad privada del condominio y 911 de inmediato. Escalar al administrador urgente.',
      'INUNDACION / FUGA DE AGUA MAYOR: Reportar al administrador INMEDIATAMENTE. Dar ubicacion de llaves de paso si esta documentada. Llamar a plomero autorizado.',
      'PERSONA BLOQUEADA / ACCIDENTE: 911 y ambulancia. Escalar a seguridad y administrador urgente.',
    ],
    fallbackPhrase,
  },
};
