// Preguntas que CADA industria DEBE responder
// Cada respuesta se convierte en conocimiento del bot
// Sin estas respuestas, el bot inventa informacion

export interface Question {
  key: string;
  type: 'text' | 'textarea' | 'list' | 'boolean' | 'multi_select' | 'number';
  label: string;
  placeholder?: string;
  help?: string;
  required: boolean;
  options?: string[];
  followUp?: string;
}

export const QUESTIONS: Record<string, Question[]> = {
  dental: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Lista TODOS tus servicios con precio',
      placeholder: 'Limpieza dental - $800\nBlanqueamiento - $3,500\nBrackets desde - $18,000\nImplante - $15,000\nExtraccion - $1,500\nEndodoncia - $4,000\nConsulta - $500',
      help: 'El bot usara estos precios EXACTOS. Si no los pones, el bot dira "consulte precios directamente"' },
    { key: 'doctors', type: 'textarea', required: true,
      label: 'Doctores y sus especialidades',
      placeholder: 'Dr. Martinez - Ortodoncia - Lunes a Viernes\nDra. Lopez - Endodoncia - Lun, Mie, Vie' },
    { key: 'insurances', type: 'text', required: false,
      label: 'Seguros que aceptan',
      placeholder: 'GNP, Metlife, MAPFRE, Seguros Monterrey' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago aceptadas',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI (meses sin intereses)','Plan de pagos'] },
    { key: 'first_visit', type: 'textarea', required: true,
      label: 'Que debe traer el paciente a su primera cita?',
      placeholder: 'Identificacion oficial, radiografias previas si tiene, lista de medicamentos que toma' },
    { key: 'cancellation', type: 'text', required: true,
      label: 'Politica de cancelacion',
      placeholder: 'Cancelar con 24 horas de anticipacion. Sin cargo.' },
    { key: 'emergency', type: 'boolean', required: true,
      label: 'Atienden emergencias dentales?',
      followUp: 'En que horario? Tiene costo adicional?' },
    { key: 'parking', type: 'text', required: false,
      label: 'Informacion de estacionamiento',
      placeholder: 'Estacionamiento gratuito / En la calle / No hay' },
    { key: 'financing', type: 'boolean', required: false,
      label: 'Manejan financiamiento o plan de pagos?' },
    { key: 'min_age', type: 'text', required: false,
      label: 'Edad minima que atienden',
      placeholder: 'Desde 3 anos con acompanante' },
  ],

  restaurant: [
    { key: 'menu', type: 'textarea', required: true,
      label: 'Menu COMPLETO con precios',
      placeholder: 'Hamburguesa clasica - $145\nPasta alfredo - $165\nEnsalada cesar - $120\nSopa del dia - $85\nAgua fresca - $45\nRefresco - $35',
      help: 'CRITICO: El bot NO puede inventar platillos ni precios' },
    { key: 'delivery', type: 'boolean', required: true,
      label: 'Hacen delivery?',
      followUp: 'Zona de cobertura? Costo de envio? Pedido minimo?' },
    { key: 'delivery_platforms', type: 'multi_select', required: false,
      label: 'Plataformas de delivery',
      options: ['Rappi','UberEats','DiDi Food','Delivery propio','No delivery'] },
    { key: 'reservations', type: 'boolean', required: true,
      label: 'Aceptan reservaciones?',
      followUp: 'Capacidad maxima de personas?' },
    { key: 'vegetarian', type: 'boolean', required: true,
      label: 'Tienen opciones vegetarianas/veganas?' },
    { key: 'allergens', type: 'textarea', required: false,
      label: 'Informacion de alergenos principales',
      placeholder: 'Hamburguesa: gluten, lacteos. Ensalada: nueces.' },
    { key: 'kids_menu', type: 'boolean', required: false,
      label: 'Menu infantil?' },
    { key: 'happy_hour', type: 'text', required: false,
      label: 'Happy hour o promociones',
      placeholder: '2x1 en cockteles de 5-7 PM de lunes a jueves' },
    { key: 'pets', type: 'boolean', required: false,
      label: 'Pet friendly?' },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento', placeholder: 'Valet parking / Libre / No' },
  ],

  psychologist: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con duracion y precio',
      placeholder: 'Terapia individual (50 min) - $800\nTerapia de pareja (75 min) - $1,200\nTerapia en linea (50 min) - $700\nEvaluacion psicologica - $2,500' },
    { key: 'therapy_types', type: 'multi_select', required: true,
      label: 'Tipos de terapia que ofrece',
      options: ['Individual adultos','Pareja','Familiar','Adolescentes','Infantil','En linea','Grupal'] },
    { key: 'specialties', type: 'textarea', required: true,
      label: 'Areas que atiende',
      placeholder: 'Ansiedad, depresion, estres laboral, duelo, problemas de pareja, autoestima, TCA, TDAH' },
    { key: 'approach', type: 'text', required: true,
      label: 'Enfoque terapeutico',
      placeholder: 'Cognitivo-conductual, humanista, gestalt...' },
    { key: 'online', type: 'boolean', required: true,
      label: 'Ofrece sesiones en linea (videollamada)?' },
    { key: 'confidentiality', type: 'textarea', required: true,
      label: 'Mensaje sobre confidencialidad',
      placeholder: 'Todas las sesiones son completamente confidenciales...' },
    { key: 'first_session', type: 'textarea', required: true,
      label: 'Como es la primera sesion?',
      placeholder: 'La primera sesion es para conocernos, hablar de lo que le trae...' },
  ],

  salon: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Corte dama - $350\nCorte caballero - $200\nTinte raiz - $800\nMechas/Balayage - $1,800\nKeratina - $2,500\nManicure - $250\nPedicure - $300' },
    { key: 'stylists', type: 'textarea', required: true,
      label: 'Estilistas y sus especialidades',
      placeholder: 'Sofia - Color y mechas - Lun a Sab\nCarla - Corte y peinado - Mar a Sab' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
    { key: 'bridal', type: 'boolean', required: false,
      label: 'Manejan paquetes para novias?' },
    { key: 'products', type: 'text', required: false,
      label: 'Marcas de productos que usan',
      placeholder: 'L Oreal Professionnel, Schwarzkopf, Kerastase' },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento' },
  ],

  real_estate: [
    { key: 'property_types', type: 'multi_select', required: true,
      label: 'Tipos de propiedades',
      options: ['Casas venta','Casas renta','Departamentos','Terrenos','Locales comerciales','Oficinas'] },
    { key: 'zones', type: 'textarea', required: true,
      label: 'Zonas que cubren',
      placeholder: 'Norte de Merida: Temozon, Cholul, Conkal\nCentro historico\nRiviera Maya' },
    { key: 'price_range', type: 'text', required: true,
      label: 'Rango de precios tipico',
      placeholder: 'Casas: $1.5M - $8M MXN. Rentas: $8K - $25K MXN/mes' },
    { key: 'credit_types', type: 'multi_select', required: true,
      label: 'Tipos de credito aceptados',
      options: ['Infonavit','Bancario','Fovissste','Contado','Mixto Infonavit+Bancario'] },
    { key: 'mortgage_help', type: 'boolean', required: false,
      label: 'Tienen asesores hipotecarios?' },
    { key: 'visit_process', type: 'text', required: true,
      label: 'Como funciona el proceso de visita?',
      placeholder: 'Agendamos visita, un asesor le acompana...' },
  ],

  hotel: [
    { key: 'rooms', type: 'textarea', required: true,
      label: 'Tipos de habitacion con precios por noche',
      placeholder: 'Standard - $1,200 MXN/noche\nDeluxe - $1,800\nSuite - $3,500\nSuite Presidencial - $6,000' },
    { key: 'amenities', type: 'multi_select', required: true,
      label: 'Amenidades',
      options: ['Alberca','Spa','Restaurante','Bar','Gym','Wifi','Estacionamiento','Room service','Concierge'] },
    { key: 'breakfast', type: 'boolean', required: true,
      label: 'Incluye desayuno?' },
    { key: 'airport_transfer', type: 'boolean', required: false,
      label: 'Transporte al aeropuerto?',
      followUp: 'Costo?' },
    { key: 'cancellation', type: 'text', required: true,
      label: 'Politica de cancelacion',
      placeholder: 'Cancelacion gratuita hasta 48h antes...' },
    { key: 'checkin_out', type: 'text', required: true,
      label: 'Horarios de check-in y check-out',
      placeholder: 'Check-in: 3 PM. Check-out: 12 PM' },
    { key: 'languages', type: 'multi_select', required: true,
      label: 'Idiomas del servicio',
      options: ['Espanol','Ingles','Frances','Aleman','Italiano'] },
    { key: 'pets', type: 'boolean', required: false,
      label: 'Pet friendly?' },
  ],

  veterinary: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Consulta - $500\nVacuna multiple - $800\nEsterilizacion gato - $1,500\nEsterilizacion perro - $2,000\nEstetica canina - $350\nUrgencia - $800' },
    { key: 'species', type: 'multi_select', required: true,
      label: 'Especies que atienden',
      options: ['Perros','Gatos','Aves','Reptiles','Roedores','Exoticos'] },
    { key: 'emergency_24h', type: 'boolean', required: true,
      label: 'Emergencias 24 horas?',
      followUp: 'Telefono de emergencias?' },
    { key: 'hospitalization', type: 'boolean', required: false,
      label: 'Tienen hospitalizacion?' },
    { key: 'grooming', type: 'boolean', required: false,
      label: 'Servicio de estetica/grooming?' },
    { key: 'pharmacy', type: 'boolean', required: false,
      label: 'Farmacia veterinaria?' },
  ],

  gym: [
    { key: 'memberships', type: 'textarea', required: true,
      label: 'Membresias con precios',
      placeholder: 'Mensual - $899\nTrimestral - $2,399\nSemestral - $4,499\nAnual - $7,999' },
    { key: 'classes', type: 'textarea', required: true,
      label: 'Clases disponibles con horarios',
      placeholder: 'CrossFit - L,M,V 7am y 6pm\nYoga - M,J 8am\nSpinning - L-V 7pm' },
    { key: 'free_trial', type: 'boolean', required: true,
      label: 'Ofrecen clase de prueba gratuita?' },
    { key: 'trainers', type: 'boolean', required: false,
      label: 'Entrenamiento personal?',
      followUp: 'Precio por sesion?' },
    { key: 'facilities', type: 'multi_select', required: true,
      label: 'Instalaciones',
      options: ['Pesas','Cardio','Funcional','Crossfit','Alberca','Regaderas','Estacionamiento','Lockers'] },
  ],
};

// Para industrias sin preguntas especificas, usar generico
export const DEFAULT_QUESTIONS: Question[] = [
  { key: 'services_prices', type: 'textarea', required: true,
    label: 'Lista de servicios con precios',
    placeholder: 'Servicio 1 - $XXX\nServicio 2 - $XXX' },
  { key: 'payment_methods', type: 'multi_select', required: true,
    label: 'Formas de pago',
    options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
  { key: 'parking', type: 'text', required: false,
    label: 'Estacionamiento' },
  { key: 'extra_info', type: 'textarea', required: false,
    label: 'Informacion adicional que quieras que tu bot sepa',
    placeholder: 'Cualquier dato relevante...' },
];

export function getQuestions(businessType: string): Question[] {
  return QUESTIONS[businessType] || DEFAULT_QUESTIONS;
}
