// Preguntas que CADA industria DEBE responder
// Cada respuesta se convierte en conocimiento del bot
// Sin estas respuestas, el bot inventa informacion

export interface Question {
  key: string;
  type: 'text' | 'textarea' | 'list' | 'boolean' | 'multi_select' | 'number';
  label: string;
  placeholder?: string;
  help?: string;
  required: boolean;
  options?: string[];
  followUp?: string;
}

export const QUESTIONS: Record<string, Question[]> = {
  dental: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Lista TODOS tus servicios con precio',
      placeholder: 'Limpieza dental - $800\nBlanqueamiento - $3,500\nBrackets desde - $18,000\nImplante - $15,000\nExtraccion - $1,500\nEndodoncia - $4,000\nConsulta - $500',
      help: 'El bot usara estos precios EXACTOS. Si no los pones, el bot dira "consulte precios directamente"' },
    { key: 'doctors', type: 'textarea', required: true,
      label: 'Doctores y sus especialidades',
      placeholder: 'Dr. Martinez - Ortodoncia - Lunes a Viernes\nDra. Lopez - Endodoncia - Lun, Mie, Vie' },
    { key: 'insurances', type: 'text', required: false,
      label: 'Seguros que aceptan',
      placeholder: 'GNP, Metlife, MAPFRE, Seguros Monterrey' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago aceptadas',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI (meses sin intereses)','Plan de pagos'] },
    { key: 'first_visit', type: 'textarea', required: true,
      label: 'Que debe traer el paciente a su primera cita?',
      placeholder: 'Identificacion oficial, radiografias previas si tiene, lista de medicamentos que toma' },
    { key: 'cancellation', type: 'text', required: true,
      label: 'Politica de cancelacion',
      placeholder: 'Cancelar con 24 horas de anticipacion. Sin cargo.' },
    { key: 'emergency', type: 'boolean', required: true,
      label: 'Atienden emergencias dentales?',
      followUp: 'En que horario? Tiene costo adicional?' },
    { key: 'parking', type: 'text', required: false,
      label: 'Informacion de estacionamiento',
      placeholder: 'Estacionamiento gratuito / En la calle / No hay' },
    { key: 'financing', type: 'boolean', required: false,
      label: 'Manejan financiamiento o plan de pagos?' },
    { key: 'min_age', type: 'text', required: false,
      label: 'Edad minima que atienden',
      placeholder: 'Desde 3 anos con acompanante' },
  ],

  restaurant: [
    { key: 'menu', type: 'textarea', required: true,
      label: 'Menu COMPLETO con precios',
      placeholder: 'Hamburguesa clasica - $145\nPasta alfredo - $165\nEnsalada cesar - $120\nSopa del dia - $85\nAgua fresca - $45\nRefresco - $35',
      help: 'CRITICO: El bot NO puede inventar platillos ni precios' },
    { key: 'delivery', type: 'boolean', required: true,
      label: 'Hacen delivery?',
      followUp: 'Zona de cobertura? Costo de envio? Pedido minimo?' },
    { key: 'delivery_platforms', type: 'multi_select', required: false,
      label: 'Plataformas de delivery',
      options: ['Rappi','UberEats','DiDi Food','Delivery propio','No delivery'] },
    { key: 'reservations', type: 'boolean', required: true,
      label: 'Aceptan reservaciones?',
      followUp: 'Capacidad maxima de personas?' },
    { key: 'vegetarian', type: 'boolean', required: true,
      label: 'Tienen opciones vegetarianas/veganas?' },
    { key: 'allergens', type: 'textarea', required: false,
      label: 'Informacion de alergenos principales',
      placeholder: 'Hamburguesa: gluten, lacteos. Ensalada: nueces.' },
    { key: 'kids_menu', type: 'boolean', required: false,
      label: 'Menu infantil?' },
    { key: 'happy_hour', type: 'text', required: false,
      label: 'Happy hour o promociones',
      placeholder: '2x1 en cockteles de 5-7 PM de lunes a jueves' },
    { key: 'pets', type: 'boolean', required: false,
      label: 'Pet friendly?' },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento', placeholder: 'Valet parking / Libre / No' },
  ],

  psychologist: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con duracion y precio',
      placeholder: 'Terapia individual (50 min) - $800\nTerapia de pareja (75 min) - $1,200\nTerapia en linea (50 min) - $700\nEvaluacion psicologica - $2,500' },
    { key: 'therapy_types', type: 'multi_select', required: true,
      label: 'Tipos de terapia que ofrece',
      options: ['Individual adultos','Pareja','Familiar','Adolescentes','Infantil','En linea','Grupal'] },
    { key: 'specialties', type: 'textarea', required: true,
      label: 'Areas que atiende',
      placeholder: 'Ansiedad, depresion, estres laboral, duelo, problemas de pareja, autoestima, TCA, TDAH' },
    { key: 'approach', type: 'text', required: true,
      label: 'Enfoque terapeutico',
      placeholder: 'Cognitivo-conductual, humanista, gestalt...' },
    { key: 'online', type: 'boolean', required: true,
      label: 'Ofrece sesiones en linea (videollamada)?' },
    { key: 'confidentiality', type: 'textarea', required: true,
      label: 'Mensaje sobre confidencialidad',
      placeholder: 'Todas las sesiones son completamente confidenciales...' },
    { key: 'first_session', type: 'textarea', required: true,
      label: 'Como es la primera sesion?',
      placeholder: 'La primera sesion es para conocernos, hablar de lo que le trae...' },
  ],

  salon: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Corte dama - $350\nCorte caballero - $200\nTinte raiz - $800\nMechas/Balayage - $1,800\nKeratina - $2,500\nManicure - $250\nPedicure - $300' },
    { key: 'stylists', type: 'textarea', required: true,
      label: 'Estilistas y sus especialidades',
      placeholder: 'Sofia - Color y mechas - Lun a Sab\nCarla - Corte y peinado - Mar a Sab' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
    { key: 'bridal', type: 'boolean', required: false,
      label: 'Manejan paquetes para novias?' },
    { key: 'products', type: 'text', required: false,
      label: 'Marcas de productos que usan',
      placeholder: 'L Oreal Professionnel, Schwarzkopf, Kerastase' },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento' },
  ],

  real_estate: [
    { key: 'property_types', type: 'multi_select', required: true,
      label: 'Tipos de propiedades',
      options: ['Casas venta','Casas renta','Departamentos','Terrenos','Locales comerciales','Oficinas'] },
    { key: 'zones', type: 'textarea', required: true,
      label: 'Zonas que cubren',
      placeholder: 'Norte de Merida: Temozon, Cholul, Conkal\nCentro historico\nRiviera Maya' },
    { key: 'price_range', type: 'text', required: true,
      label: 'Rango de precios tipico',
      placeholder: 'Casas: $1.5M - $8M MXN. Rentas: $8K - $25K MXN/mes' },
    { key: 'credit_types', type: 'multi_select', required: true,
      label: 'Tipos de credito aceptados',
      options: ['Infonavit','Bancario','Fovissste','Contado','Mixto Infonavit+Bancario'] },
    { key: 'mortgage_help', type: 'boolean', required: false,
      label: 'Tienen asesores hipotecarios?' },
    { key: 'visit_process', type: 'text', required: true,
      label: 'Como funciona el proceso de visita?',
      placeholder: 'Agendamos visita, un asesor le acompana...' },
  ],

  hotel: [
    { key: 'rooms', type: 'textarea', required: true,
      label: 'Tipos de habitacion con precios por noche',
      placeholder: 'Standard - $1,200 MXN/noche\nDeluxe - $1,800\nSuite - $3,500\nSuite Presidencial - $6,000' },
    { key: 'amenities', type: 'multi_select', required: true,
      label: 'Amenidades',
      options: ['Alberca','Spa','Restaurante','Bar','Gym','Wifi','Estacionamiento','Room service','Concierge'] },
    { key: 'breakfast', type: 'boolean', required: true,
      label: 'Incluye desayuno?' },
    { key: 'airport_transfer', type: 'boolean', required: false,
      label: 'Transporte al aeropuerto?',
      followUp: 'Costo?' },
    { key: 'cancellation', type: 'text', required: true,
      label: 'Politica de cancelacion',
      placeholder: 'Cancelacion gratuita hasta 48h antes...' },
    { key: 'checkin_out', type: 'text', required: true,
      label: 'Horarios de check-in y check-out',
      placeholder: 'Check-in: 3 PM. Check-out: 12 PM' },
    { key: 'languages', type: 'multi_select', required: true,
      label: 'Idiomas del servicio',
      options: ['Espanol','Ingles','Frances','Aleman','Italiano'] },
    { key: 'pets', type: 'boolean', required: false,
      label: 'Pet friendly?' },
  ],

  veterinary: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Consulta - $500\nVacuna multiple - $800\nEsterilizacion gato - $1,500\nEsterilizacion perro - $2,000\nEstetica canina - $350\nUrgencia - $800' },
    { key: 'species', type: 'multi_select', required: true,
      label: 'Especies que atienden',
      options: ['Perros','Gatos','Aves','Reptiles','Roedores','Exoticos'] },
    { key: 'emergency_24h', type: 'boolean', required: true,
      label: 'Emergencias 24 horas?',
      followUp: 'Telefono de emergencias?' },
    { key: 'hospitalization', type: 'boolean', required: false,
      label: 'Tienen hospitalizacion?' },
    { key: 'grooming', type: 'boolean', required: false,
      label: 'Servicio de estetica/grooming?' },
    { key: 'pharmacy', type: 'boolean', required: false,
      label: 'Farmacia veterinaria?' },
  ],

  medical: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Lista de servicios con precios',
      placeholder: 'Consulta general - $600\nConsulta especialista - $900\nCheckup completo - $3,500\nElectrocardiograma - $800',
      help: 'El bot usara estos precios EXACTOS' },
    { key: 'specialties', type: 'multi_select', required: true,
      label: 'Especialidades disponibles',
      options: ['Medicina general','Cardiologia','Dermatologia','Endocrinologia','Gastroenterologia','Neurologia','Traumatologia','Medicina interna','Neumologia','Urologia'] },
    { key: 'insurances', type: 'textarea', required: true,
      label: 'Seguros y convenios que aceptan',
      placeholder: 'GNP, MAPFRE, Metlife, AXA, Seguros Monterrey, IMSS (subrogacion)' },
    { key: 'emergency_protocol', type: 'boolean', required: true,
      label: 'Atienden urgencias?',
      followUp: 'En que horario? Tiene costo adicional?' },
    { key: 'first_visit', type: 'textarea', required: true,
      label: 'Requisitos para primera consulta',
      placeholder: 'Identificacion oficial, poliza de seguro, estudios previos si tiene' },
    { key: 'telemedicine', type: 'boolean', required: true,
      label: 'Ofrecen consultas por telemedicina (videollamada)?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI (meses sin intereses)'] },
    { key: 'parking', type: 'text', required: false,
      label: 'Informacion de estacionamiento',
      placeholder: 'Estacionamiento gratuito / En la calle / No hay' },
  ],

  nutritionist: [
    { key: 'specialties', type: 'multi_select', required: true,
      label: 'Areas de especialidad',
      options: ['Nutricion clinica','Nutricion deportiva','Nutricion pediatrica','Control de peso','Nutricion oncologica','Nutricion renal','Trastornos alimenticios','Nutricion vegetariana/vegana'] },
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Primera consulta (60 min) - $800\nConsulta seguimiento (40 min) - $600\nPlan alimenticio personalizado - $1,200\nPaquete 4 consultas - $2,800' },
    { key: 'consultation_duration', type: 'text', required: true,
      label: 'Duracion de consultas',
      placeholder: 'Primera consulta 60 min, seguimiento 40 min' },
    { key: 'meal_plans', type: 'boolean', required: true,
      label: 'Incluye plan de alimentacion personalizado?' },
    { key: 'online_sessions', type: 'boolean', required: true,
      label: 'Ofrece consultas en linea?' },
    { key: 'tools', type: 'multi_select', required: false,
      label: 'Herramientas y estudios que utiliza',
      options: ['Bioimpedancia','Antropometria','Analisis de sangre','App de seguimiento','Calorimetria'] },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
  ],

  dermatologist: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios (consulta y procedimientos)',
      placeholder: 'Consulta dermatologica - $900\nTratamiento acne - $1,200\nBotox (zona) - $3,500\nLaser CO2 - $5,000\nPeeling quimico - $2,000\nMicrodermoabrasion - $1,500' },
    { key: 'procedures', type: 'multi_select', required: true,
      label: 'Procedimientos que realizan',
      options: ['Tratamiento acne','Botox','Rellenos faciales','Laser','Peeling quimico','Microdermoabrasion','Eliminacion de verrugas/lunares','Depilacion laser','Tratamiento manchas','Mesoterapia'] },
    { key: 'consultation_vs_procedure', type: 'textarea', required: true,
      label: 'Diferencia entre consulta y procedimiento',
      placeholder: 'La consulta es de valoracion ($900). Los procedimientos se cotizan aparte segun el caso.' },
    { key: 'post_care', type: 'textarea', required: true,
      label: 'Instrucciones generales de post-cuidado',
      placeholder: 'Evitar sol directo 48h, usar bloqueador SPF50, no maquillaje 24h...' },
    { key: 'brands', type: 'text', required: false,
      label: 'Marcas de productos que manejan',
      placeholder: 'Allergan, Galderma, SkinCeuticals, La Roche-Posay' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI (meses sin intereses)'] },
  ],

  gynecologist: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Consulta ginecologica - $900\nPapanicolaou - $600\nUltrasonido obstetrico - $1,200\nColposcopia - $1,500\nControl prenatal (paquete) - $15,000' },
    { key: 'ultrasound', type: 'boolean', required: true,
      label: 'Cuentan con equipo de ultrasonido en consultorio?' },
    { key: 'prenatal_care', type: 'boolean', required: true,
      label: 'Ofrecen seguimiento prenatal completo?',
      followUp: 'Incluye parto? En que hospital?' },
    { key: 'services_offered', type: 'multi_select', required: true,
      label: 'Servicios que ofrecen',
      options: ['Consulta general','Papanicolaou','Colposcopia','Ultrasonido','Control prenatal','Planificacion familiar','Menopausia','Cirugia ginecologica','Fertilidad'] },
    { key: 'scheduling_preferences', type: 'text', required: true,
      label: 'Preferencias de agenda',
      placeholder: 'Citas cada 30 min. Consulta prenatal requiere 45 min.' },
    { key: 'insurances', type: 'text', required: false,
      label: 'Seguros que aceptan',
      placeholder: 'GNP, AXA, Metlife, MAPFRE' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI'] },
  ],

  pediatrician: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Consulta pediatrica - $800\nControl nino sano - $700\nUrgencia pediatrica - $1,000\nVacunas (varia segun vacuna)\nCertificado medico - $500' },
    { key: 'age_range', type: 'text', required: true,
      label: 'Rango de edad que atienden',
      placeholder: 'Recien nacidos hasta 16 anos' },
    { key: 'vaccines', type: 'boolean', required: true,
      label: 'Aplican vacunas en consultorio?',
      followUp: 'Cuales vacunas manejan? Tienen esquema completo?' },
    { key: 'emergency_protocol', type: 'boolean', required: true,
      label: 'Atienden urgencias pediatricas?',
      followUp: 'En que horario? Numero de emergencias?' },
    { key: 'parent_communication', type: 'multi_select', required: true,
      label: 'Canales de comunicacion con padres',
      options: ['WhatsApp','Telefono','App propia','Correo electronico','Portal web'] },
    { key: 'insurances', type: 'text', required: false,
      label: 'Seguros que aceptan',
      placeholder: 'GNP, AXA, Metlife, MAPFRE' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
  ],

  ophthalmologist: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Examen de la vista - $500\nConsulta oftalmologica - $900\nCirugia LASIK (por ojo) - $15,000\nCirugia cataratas - $25,000\nLentes de contacto (adaptacion) - $800' },
    { key: 'services_offered', type: 'multi_select', required: true,
      label: 'Servicios que ofrecen',
      options: ['Examen de la vista','Graduacion de lentes','Cirugia LASIK','Cirugia cataratas','Glaucoma','Retina','Lentes de contacto','Oftalmologia pediatrica','Cirugia de parpados'] },
    { key: 'equipment', type: 'textarea', required: false,
      label: 'Equipo especializado con el que cuentan',
      placeholder: 'Topografo corneal, OCT, campimetro, laser excimer' },
    { key: 'insurances', type: 'text', required: false,
      label: 'Seguros que aceptan',
      placeholder: 'GNP, AXA, Metlife, MAPFRE' },
    { key: 'scheduling', type: 'text', required: true,
      label: 'Como funciona la agenda',
      placeholder: 'Citas cada 30 min. Cirugias se programan por separado.' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia SPEI','MSI (meses sin intereses)'] },
  ],

  taqueria: [
    { key: 'menu', type: 'textarea', required: true,
      label: 'Menu COMPLETO con precios',
      placeholder: 'Taco pastor - $18\nTaco bistec - $22\nTaco suadero - $20\nGringa - $45\nQuesadilla - $35\nTorta - $55\nRefresco - $25\nAgua fresca - $30',
      help: 'CRITICO: El bot NO puede inventar platillos ni precios' },
    { key: 'delivery', type: 'boolean', required: true,
      label: 'Hacen entregas a domicilio?',
      followUp: 'Zona de cobertura? Costo de envio? Pedido minimo?' },
    { key: 'salsas', type: 'textarea', required: false,
      label: 'Salsas disponibles',
      placeholder: 'Verde, roja, habanero, guacamole ($15 extra), chipotle' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','Rappi','UberEats','DiDi Food'] },
    { key: 'catering', type: 'boolean', required: false,
      label: 'Hacen servicio de taquiza para eventos?',
      followUp: 'Precio por persona? Minimo de personas?' },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento',
      placeholder: 'En la calle / Estacionamiento propio / No hay' },
  ],

  cafe: [
    { key: 'beverages', type: 'textarea', required: true,
      label: 'Menu de bebidas con precios',
      placeholder: 'Americano - $45\nCapuchino - $55\nLatte - $60\nMocha - $65\nTe - $40\nFrappe - $70\nJugo natural - $50',
      help: 'El bot usara estos precios EXACTOS' },
    { key: 'food_menu', type: 'textarea', required: true,
      label: 'Menu de alimentos con precios',
      placeholder: 'Croissant - $55\nPanini - $95\nEnsalada - $110\nPastel del dia - $75\nGalleta - $35' },
    { key: 'wifi', type: 'boolean', required: true,
      label: 'Tienen WiFi para clientes?',
      followUp: 'Es gratis? Contrasena?' },
    { key: 'events', type: 'boolean', required: false,
      label: 'Tienen eventos o musica en vivo?',
      followUp: 'Que dias? Que tipo de eventos?' },
    { key: 'loyalty', type: 'boolean', required: false,
      label: 'Manejan programa de lealtad o tarjeta de puntos?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','Rappi','UberEats'] },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento' },
  ],

  barbershop: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Corte clasico - $150\nCorte + barba - $250\nAfeitado navaja - $120\nTinte - $300\nDiseno de barba - $100\nCorte nino - $100' },
    { key: 'appointment_type', type: 'multi_select', required: true,
      label: 'Tipo de atencion',
      options: ['Solo con cita','Sin cita (walk-in)','Ambos (cita y walk-in)'] },
    { key: 'barbers', type: 'textarea', required: false,
      label: 'Barberos y sus especialidades',
      placeholder: 'Carlos - Fade y disenos - Lun a Sab\nMiguel - Clasico y barba - Mar a Dom' },
    { key: 'products', type: 'text', required: false,
      label: 'Productos a la venta',
      placeholder: 'Pomadas, ceras, aceites para barba, shampoo' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia'] },
    { key: 'parking', type: 'text', required: false,
      label: 'Estacionamiento' },
  ],

  spa: [
    { key: 'treatments', type: 'textarea', required: true,
      label: 'Tratamientos con precios y duracion',
      placeholder: 'Masaje relajante (60 min) - $900\nMasaje deep tissue (60 min) - $1,200\nFacial hidratante (45 min) - $800\nCircuito spa (2h) - $1,500\nExfoliacion corporal (45 min) - $700' },
    { key: 'packages', type: 'textarea', required: false,
      label: 'Paquetes especiales',
      placeholder: 'Paquete relajacion: masaje + facial - $1,500\nDia de spa completo - $3,500' },
    { key: 'couples', type: 'boolean', required: true,
      label: 'Ofrecen tratamientos en pareja?',
      followUp: 'Cuales y a que precio?' },
    { key: 'gift_cards', type: 'boolean', required: true,
      label: 'Manejan tarjetas de regalo?' },
    { key: 'facilities', type: 'multi_select', required: false,
      label: 'Instalaciones',
      options: ['Sauna','Vapor','Jacuzzi','Alberca','Regaderas','Sala de relajacion','Jardin'] },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia','MSI'] },
  ],

  pharmacy: [
    { key: 'delivery', type: 'boolean', required: true,
      label: 'Hacen entregas a domicilio?',
      followUp: 'Zona de cobertura? Costo? Tiempo estimado?' },
    { key: 'prescription_handling', type: 'text', required: true,
      label: 'Como manejan recetas medicas?',
      placeholder: 'Aceptamos recetas fisicas y digitales. Medicamentos controlados requieren receta original.' },
    { key: 'otc_products', type: 'multi_select', required: true,
      label: 'Productos adicionales que manejan',
      options: ['Dermocosmetica','Suplementos','Productos bebe','Higiene personal','Material de curacion','Equipo medico','Vitaminas','Naturistas'] },
    { key: 'insurances', type: 'text', required: false,
      label: 'Convenios con seguros',
      placeholder: 'GNP, AXA, Metlife, descuento INAPAM' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia','Vales de despensa'] },
    { key: 'consultation', type: 'boolean', required: false,
      label: 'Tienen consultorio medico en farmacia?',
      followUp: 'Costo de la consulta?' },
  ],

  school: [
    { key: 'levels', type: 'multi_select', required: true,
      label: 'Niveles educativos',
      options: ['Preescolar / Kinder','Primaria','Secundaria','Preparatoria','Universidad','Posgrado','Cursos / Diplomados'] },
    { key: 'enrollment_process', type: 'textarea', required: true,
      label: 'Proceso de inscripcion',
      placeholder: 'Visita guiada, examen de admision, entrega de documentos, pago de inscripcion' },
    { key: 'tuition', type: 'textarea', required: true,
      label: 'Costos (inscripcion y colegiaturas)',
      placeholder: 'Inscripcion: $5,000\nColegiatura mensual: $3,500\nMaterial anual: $2,000' },
    { key: 'scholarships', type: 'boolean', required: true,
      label: 'Ofrecen becas o descuentos?',
      followUp: 'Que tipos? Requisitos?' },
    { key: 'extracurriculars', type: 'textarea', required: false,
      label: 'Actividades extracurriculares',
      placeholder: 'Futbol, natacion, robotica, musica, ingles avanzado, arte' },
    { key: 'schedule', type: 'text', required: true,
      label: 'Horarios de clase',
      placeholder: 'Matutino 7:30-14:00, Vespertino 14:00-18:30, Tiempo completo 7:30-18:30' },
  ],

  insurance: [
    { key: 'insurance_types', type: 'multi_select', required: true,
      label: 'Tipos de seguro que manejan',
      options: ['Auto','Vida','Gastos medicos mayores','Hogar','Negocio / empresarial','Viaje','Educacion','Responsabilidad civil','Flotilla'] },
    { key: 'carriers', type: 'textarea', required: true,
      label: 'Aseguradoras con las que trabajan',
      placeholder: 'GNP, AXA, Metlife, MAPFRE, Qualitas, HDI, Zurich, Chubb' },
    { key: 'quote_process', type: 'textarea', required: true,
      label: 'Como funciona el proceso de cotizacion?',
      placeholder: 'Cotizacion sin costo por WhatsApp o llamada. Respuesta en menos de 2 horas.' },
    { key: 'claims_support', type: 'boolean', required: true,
      label: 'Apoyan al cliente con el proceso de siniestros?',
      followUp: 'Como funciona el acompanamiento?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago de polizas',
      options: ['Anual','Semestral','Trimestral','Mensual','Tarjeta credito','Domiciliacion','Transferencia'] },
    { key: 'online_service', type: 'boolean', required: false,
      label: 'Atienden de manera remota (todo en linea)?' },
  ],

  mechanic: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Servicio menor - $1,800\nServicio mayor - $4,500\nAfinacion - $2,500\nFrenos (juego) - $3,000\nDiagnostico computarizado - $500\nAlineacion y balanceo - $800' },
    { key: 'brands', type: 'multi_select', required: true,
      label: 'Marcas en las que se especializan',
      options: ['Todas las marcas','Toyota','Honda','Nissan','Volkswagen','Chevrolet','Ford','BMW','Mercedes-Benz','Audi','Mazda','KIA','Hyundai'] },
    { key: 'diagnostic_equipment', type: 'boolean', required: true,
      label: 'Cuentan con equipo de diagnostico computarizado?' },
    { key: 'warranty', type: 'text', required: true,
      label: 'Garantia en servicios',
      placeholder: '6 meses o 10,000 km en mano de obra y refacciones' },
    { key: 'pickup_delivery', type: 'boolean', required: false,
      label: 'Ofrecen servicio de recoleccion y entrega del vehiculo?',
      followUp: 'Zona de cobertura? Costo?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia','MSI'] },
  ],

  accountant: [
    { key: 'services', type: 'multi_select', required: true,
      label: 'Servicios que ofrecen',
      options: ['Contabilidad general','Declaraciones fiscales','Nomina','Auditoria','Asesoria fiscal','Constitucion de empresas','CFDI / facturacion','Impuestos personas fisicas','Impuestos personas morales','Devoluciones SAT'] },
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Precios o modelo de cobro',
      placeholder: 'Declaracion anual PF - $2,000\nContabilidad mensual PYME - desde $3,500\nNomina (por empleado) - $150\nConstitucion empresa - $8,000' },
    { key: 'software', type: 'text', required: false,
      label: 'Software contable que utilizan',
      placeholder: 'CONTPAQi, Aspel, SAT, A3ERP' },
    { key: 'cfdi_support', type: 'boolean', required: true,
      label: 'Apoyan con la emision y gestion de CFDI (facturas)?' },
    { key: 'online_service', type: 'boolean', required: true,
      label: 'Atienden de manera remota?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Transferencia','Tarjeta','Factura deducible'] },
  ],

  florist: [
    { key: 'arrangements', type: 'textarea', required: true,
      label: 'Arreglos y productos con precios',
      placeholder: 'Ramo de rosas (12) - $450\nArreglo cumpleanos - $600\nCentro de mesa - $350\nCorona funebre - $1,200\nBouquet novia - desde $2,500' },
    { key: 'delivery', type: 'boolean', required: true,
      label: 'Hacen entregas a domicilio?',
      followUp: 'Zona de cobertura? Costo de envio?' },
    { key: 'same_day', type: 'boolean', required: true,
      label: 'Ofrecen entrega el mismo dia?' },
    { key: 'events', type: 'boolean', required: true,
      label: 'Hacen decoracion para eventos y bodas?',
      followUp: 'Incluyen montaje? Precio promedio?' },
    { key: 'custom_orders', type: 'boolean', required: true,
      label: 'Aceptan pedidos personalizados?' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta','Transferencia','PayPal'] },
  ],

  optics: [
    { key: 'services_prices', type: 'textarea', required: true,
      label: 'Servicios con precios',
      placeholder: 'Examen de la vista - $200 (gratis con compra de lentes)\nLentes oftalmicos desde - $1,200\nLentes de contacto desde - $600\nLentes de sol graduados desde - $2,000' },
    { key: 'exams', type: 'boolean', required: true,
      label: 'Realizan examen de la vista en sucursal?',
      followUp: 'Costo? Es gratis con compra?' },
    { key: 'lens_types', type: 'multi_select', required: true,
      label: 'Tipos de lentes que manejan',
      options: ['Monofocales','Bifocales','Progresivos','Transitions','Antirreflejante','Filtro luz azul','Lentes de contacto blandos','Lentes de contacto rigidos','Lentes de sol'] },
    { key: 'frame_brands', type: 'textarea', required: false,
      label: 'Marcas de armazones',
      placeholder: 'Ray-Ban, Oakley, Prada, Guess, Carolina Herrera, Tommy Hilfiger' },
    { key: 'insurance', type: 'text', required: false,
      label: 'Convenios con seguros o empresas',
      placeholder: 'GNP, MetLife, vales de optica, convenios empresariales' },
    { key: 'turnaround', type: 'text', required: true,
      label: 'Tiempo de entrega de lentes',
      placeholder: 'Lentes sencillos 3-5 dias, progresivos 7-10 dias' },
    { key: 'payment_methods', type: 'multi_select', required: true,
      label: 'Formas de pago',
      options: ['Efectivo','Tarjeta debito','Tarjeta credito','Transferencia','MSI','Vales de optica'] },
  ],

  gym: [
    { key: 'memberships', type: 'textarea', required: true,
      label: 'Membresias con precios',
      placeholder: 'Mensual - $899\nTrimestral - $2,399\nSemestral - $4,499\nAnual - $7,999' },
    { key: 'classes', type: 'textarea', required: true,
      label: 'Clases disponibles con horarios',
      placeholder: 'CrossFit - L,M,V 7am y 6pm\nYoga - M,J 8am\nSpinning - L-V 7pm' },
    { key: 'free_trial', type: 'boolean', required: true,
      label: 'Ofrecen clase de prueba gratuita?' },
    { key: 'trainers', type: 'boolean', required: false,
      label: 'Entrenamiento personal?',
      followUp: 'Precio por sesion?' },
    { key: 'facilities', type: 'multi_select', required: true,
      label: 'Instalaciones',
      options: ['Pesas','Cardio','Funcional','Crossfit','Alberca','Regaderas','Estacionamiento','Lockers'] },
  ],
};

// Para industrias sin preguntas especificas, usar generico
export const DEFAULT_QUESTIONS: Question[] = [
  { key: 'services_prices', type: 'textarea', required: true,
    label: 'Lista de servicios con precios',
    placeholder: 'Servicio 1 - $XXX\nServicio 2 - $XXX' },
  { key: 'payment_methods', type: 'multi_select', required: true,
    label: 'Formas de pago',
    options: ['Efectivo','Tarjeta','Transferencia','MSI'] },
  { key: 'parking', type: 'text', required: false,
    label: 'Estacionamiento' },
  { key: 'extra_info', type: 'textarea', required: false,
    label: 'Informacion adicional que quieras que tu bot sepa',
    placeholder: 'Cualquier dato relevante...' },
];

export function getQuestions(businessType: string): Question[] {
  return QUESTIONS[businessType] || DEFAULT_QUESTIONS;
}
