import type { VerticalEnum, VerticalMetadata } from '@/lib/verticals/types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const gastronomiaMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  restaurante: {
    vertical: 'restaurante',
    category: 'GASTRONOMIA',
    displayName: 'Restaurante',
    software: [
      { name: 'SoftRestaurant 12', price: '$699-999 MXN/mes+IVA', description: 'POS lider en Mexico, delivery hub, CFDI' },
      { name: 'Poster POS', price: '$530-1,260 MXN/mes', description: 'Cloud POS con IA predictiva' },
      { name: 'Parrot Software', price: '$1,800-2,800 MXN/mes+IVA', description: 'Mejor integracion delivery (UberEats, Rappi)' },
      { name: 'OpenTable Mexico', price: '$2,695-4,495 MXN/mes', description: 'Reservaciones + $12/comensal red' },
      { name: 'Otter (ex Hubster)', price: 'Quote-based', description: 'Agregador de delivery' },
    ],
    apis: [
      'SoftRestaurant REST API (api.softrestaurant.com.mx)',
      'Poster POS API publica',
      'OpenTable API partners',
      'Clip Developer API',
      'Facturapi REST API',
    ],
    topFaqs: [
      'Cual es su horario?',
      'Tienen mesa disponible para X personas?',
      'Pueden compartir el menu?',
      'Cuanto cuesta [platillo]?',
      'Hacen entregas a domicilio?',
      'Tienen opciones vegetarianas/veganas/sin gluten?',
      'Que formas de pago aceptan?',
      'Pueden facturar?',
      'Tienen estacionamiento?',
      'Tienen paquetes para eventos?',
    ],
    neverHallucinate: [
      'PRECIOS de platillos — cualquier error genera confrontacion inmediata',
      'EXISTENCIA de platillos — nunca inventar que tienen algo que no esta en menu',
      'ALERGENOS/INGREDIENTES — error aqui puede ser letal',
      'DISPONIBILIDAD de mesas — consultar sistema real',
      'HORARIO (especialmente festivos) — nunca inventar',
      'ZONAS DE ENTREGA — un envio a zona no cubierta genera enojo',
      'PROMOCIONES — si no estan vigentes, no mencionarlas',
      'METODOS DE PAGO — decir que aceptan MSI cuando no, causa problemas',
    ],
    crisisProtocols: [
      'REACCION ALERGICA en restaurante: 911 INMEDIATAMENTE. Preservar muestra del platillo.',
      'INTOXICACION ALIMENTARIA: Documentar platillo, hora, sintomas. Escalar a gerente. Si son multiples casos, COFEPRIS.',
      'OBJETO EXTRANO en comida: Disculpa inmediata, retirar platillo, documentar, compensar. NUNCA negar.',
      'FALLA DE LUZ: POS offline mode. Monitorear cadena frio (NOM-251). Cash only.',
      'INSPECCION COFEPRIS: Dos testigos requeridos. Verificar DC-3 de manipuladores. Bitacoras de temperatura.',
    ],
    fallbackPhrase,
  },

  taqueria: {
    vertical: 'taqueria',
    category: 'GASTRONOMIA',
    displayName: 'Taqueria',
    software: [
      { name: 'SoftRestaurant Lite', price: '$699 MXN/mes+IVA', description: '2 terminales, delivery' },
      { name: 'Alegra POS', price: '$199 MXN/mes', description: 'POS basico con CFDI' },
      { name: 'Poster POS', price: '$325 MXN/mes', description: 'Inventario por ingrediente' },
      { name: 'Loyverse', price: 'Gratis', description: 'POS basico para micro-operaciones' },
      { name: 'Clip Plus 2', price: '$199-449 MXN', description: 'Terminal de pago sin mensualidad' },
    ],
    apis: [
      'Poster POS API',
      'Clip Developer API',
      'Parrot Software API (delivery)',
    ],
    topFaqs: [
      'Que tacos tienen y a como?',
      'Tienen [suadero/tripa/cabeza/lengua]?',
      'Hasta que hora estan abiertos?',
      'Hacen entregas?',
      'Aceptan tarjeta o solo efectivo?',
      'Venden por kilo?',
      'Tienen salsas picosas?',
      'Me pueden facturar?',
      'Tienen cerveza?',
      'Donde estan ubicados?',
    ],
    neverHallucinate: [
      'PRECIOS — los clientes son hipersensibles, hasta $1 MXN importa',
      'DISPONIBILIDAD DE CARNES — el pastor se acaba TODAS las noches',
      'TIPO DE TORTILLA — maiz vs. harina es critico para el mexicano',
      'SALSAS — no inventar variedad de salsas',
      'CERVEZA — requiere licencia, si no la tienen y dices que si, problema legal',
      'HORARIO — muchos cierran cuando se acaba, no a hora fija',
      'PRECIO POR KILO — es negociable y variable',
    ],
    crisisProtocols: [
      'ROBO de caja: Auditorias POS, procedimiento de cierre, caja fuerte.',
      'INTOXICACION: Documentar. COFEPRIS si multiples casos.',
      'INCIDENTE nocturno (taquerias abren tarde): Protocolo de seguridad, boton de panico.',
    ],
    fallbackPhrase,
  },

  cafeteria: {
    vertical: 'cafeteria',
    category: 'GASTRONOMIA',
    displayName: 'Cafeteria',
    software: [
      { name: 'PoloTab', price: 'Quote-based', description: 'Favorito de specialty coffee CDMX' },
      { name: 'Poster POS', price: '$325 MXN/mes', description: 'Recetas de cafe, inventario' },
      { name: 'Alegra POS', price: '$199-1,299 MXN/mes', description: 'POS cloud + CFDI' },
      { name: 'Puntos de Lealtad', price: 'Custom', description: 'Programa de lealtad mexicano' },
    ],
    apis: [
      'Poster POS API',
      'Alegra API',
      'Clip Developer API',
    ],
    topFaqs: [
      'Cual es la contrasena del WiFi?',
      'Que tienen en el menu de cafes?',
      'Tienen leche de avena/almendra?',
      'Son pet friendly?',
      'Cual es su horario?',
      'Aceptan tarjeta?',
      'Tienen opciones veganas/sin gluten?',
      'Venden cafe en grano?',
      'Pueden facturar?',
      'Tienen enchufes/espacio para trabajar?',
    ],
    neverHallucinate: [
      'PASSWORD DE WIFI — cambia frecuentemente',
      'ORIGEN DEL CAFE — specialty cafes son MUY particulares',
      'LECHES ALTERNATIVAS — disponibilidad y sobrecargo deben ser exactos',
      'CALORIAS/NUTRICION — no inventar',
      'EVENTOS — no inventar horarios de cata o taller',
    ],
    crisisProtocols: [
      'QUEMADURA con cafe caliente: Primeros auxilios basicos, agua fria. Si es grave, 911.',
      'REACCION ALERGICA (leche, nueces): 911 si dificultad respiratoria.',
    ],
    fallbackPhrase,
  },

  panaderia: {
    vertical: 'panaderia',
    category: 'GASTRONOMIA',
    displayName: 'Panaderia',
    software: [
      { name: 'Point POS', price: 'Custom', description: 'Recetas + produccion' },
      { name: 'SICAR', price: '$4,940 MXN', description: 'POS + lealtad' },
      { name: 'Eleventa', price: '$1,499 MXN', description: 'POS lifetime' },
    ],
    apis: [
      'SICAR limited',
      'OlaClick chatbot WhatsApp',
    ],
    topFaqs: [
      'Puedo encargar un pastel personalizado?',
      'Tienen [pan especifico]? Ya salio el pan?',
      'Precios de mayoreo?',
      'A que hora sale el pan caliente?',
      'Cuanto cuesta un pastel de [X]?',
      'Hacen entregas?',
      'Que ingredientes tiene? Sin gluten?',
      'Ya tienen Rosca de Reyes / Pan de Muerto?',
      'Cuanto tiempo de anticipacion necesitan?',
      'Como puedo pagar?',
    ],
    neverHallucinate: [
      'DISPONIBILIDAD de pan — se acaba por hora, no por dia',
      'PRECIO de pasteles personalizados — SIEMPRE requiere cotizacion humana',
      'INGREDIENTES — alergenos criticos',
      'PEDIDOS DE TEMPORADA — fechas y precios cambian anualmente',
      'HORARIO de pan fresco — varia por tipo de pan',
    ],
    crisisProtocols: [
      'HORNO descompuesto: Contactar servicio tecnico. Comunicar retrasos a clientes mayoreo.',
      'PASTEL DE BODA/XV ANOS con error: URGENCIA MAXIMA emocional. Escalar inmediatamente.',
    ],
    fallbackPhrase,
  },

  bar_cantina: {
    vertical: 'bar_cantina',
    category: 'GASTRONOMIA',
    displayName: 'Bar / Cantina',
    software: [
      { name: 'SoftRestaurant 12', price: '$699-999 MXN/mes+IVA', description: 'Control de bar + recetas coctel' },
      { name: 'Poster POS Pro', price: '$1,240 MXN/mes', description: 'Reservaciones + control acceso' },
      { name: 'Bar Controller', price: 'Custom', description: 'Bascula bluetooth para botellas' },
    ],
    apis: [
      'SoftRestaurant REST API',
      'Poster POS API',
    ],
    topFaqs: [
      'A que hora abren/cierran?',
      'Cuanto es el cover?',
      'Hay codigo de vestimenta?',
      'Puedo reservar mesa?',
      'Cuanto cuestan las botellas/VIP?',
      'Que evento hay hoy?',
      'Quien toca hoy?',
      'Tienen happy hour?',
      'Tienen estacionamiento/valet?',
      'Hacen eventos privados?',
    ],
    neverHallucinate: [
      'EVENTOS — artista, fecha, hora equivocados = enojo masivo',
      'COVER — varia por noche, genero, hora de llegada',
      'HORARIO — regulado por ley estatal, Ley Seca en elecciones',
      'HAPPY HOUR — terminos exactos o genera disputas',
      'PRECIOS de botellas — varian por marca y presentacion',
      'CERVEZA/LICOR disponible — marcas especificas deben verificarse',
    ],
    crisisProtocols: [
      'PELEA/VIOLENCIA: Seguridad, CCTV, 911 si necesario.',
      'INTOXICACION ALCOHOLICA: Llamar 911/Cruz Roja. Cortar servicio.',
      'MENOR DE EDAD: Suspender servicio inmediatamente. Documentar. Cooperar con autoridades.',
      'ACOSO: Protocolo de seguridad. Acompanar a victima. Expulsar a agresor.',
    ],
    fallbackPhrase,
  },

  food_truck: {
    vertical: 'food_truck',
    category: 'GASTRONOMIA',
    displayName: 'Food Truck',
    software: [
      { name: 'Clip Plus 2', price: '$199-449 MXN', description: 'Terminal sin mensualidad' },
      { name: 'Clip Pro 2', price: '$2,499 MXN', description: '4G integrado' },
      { name: 'Poster POS Mini', price: '$520 MXN/mes', description: 'POS tablet con offline' },
    ],
    apis: [
      'Clip Developer API',
      'Poster POS API',
    ],
    topFaqs: [
      'Donde estan hoy?',
      'Que horario tienen?',
      'Que tienen en el menu?',
      'Aceptan tarjeta?',
      'Hacen catering?',
      'En que eventos van a estar?',
      'Tienen opciones vegetarianas?',
      'Pueden ir a mi evento?',
      'Cuanto cuesta [platillo]?',
      'Tienen estacionamiento cerca?',
    ],
    neverHallucinate: [
      'UBICACION — la mas critica. NUNCA inventar donde estan. Siempre redirigir a Instagram.',
      'HORARIO — varia por dia, clima, ubicacion',
      'DISPONIBILIDAD de platillos — se agotan rapidamente',
      'EVENTOS — no inventar participacion en festivales',
    ],
    crisisProtocols: [
      'DESCOMPOSTURA del vehiculo: Notificar en redes, reubicar perecederos.',
      'CANCELACION por clima: Notificar inmediatamente en redes.',
      'PERMISO municipal: Tener ubicaciones alternativas permitidas.',
    ],
    fallbackPhrase,
  },
};
