import type { VerticalEnum, VerticalMetadata } from '@/lib/verticals/types';

const fallbackPhrase = 'Permitame verificar esa informacion. Un momento por favor.';

export const retailMetadata: Partial<Record<VerticalEnum, VerticalMetadata>> = {
  floreria: {
    vertical: 'floreria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Floreria',
    software: [
      { name: 'SIFO', price: 'Free trial + license', description: 'POS + delivery tracking perecederos' },
      { name: 'Eleventa', price: '$1,499 MXN lifetime', description: 'POS basico' },
      { name: 'SICAR', price: '$4,940 MXN', description: 'POS + lealtad' },
      { name: 'TiendaNube', price: 'Gratis-$999 MXN/mes', description: 'E-commerce' },
    ],
    apis: [
      'TiendaNube API',
      'Shopify API',
      'Clip Developer API',
    ],
    topFaqs: [
      'A donde entregan?',
      'Hasta que hora para entrega hoy?',
      'Cuanto cuesta un arreglo?',
      'Arreglo personalizado?',
      'Disponibilidad para 14 de febrero/10 de mayo?',
      'Decoracion para eventos/bodas?',
      'Suscripcion semanal?',
      'Como cuido las flores?',
      'Aceptan tarjeta/transferencia?',
      'Que pasa si llegan marchitas?',
    ],
    neverHallucinate: [
      'PRECIOS — fluctuan DIARIO segun Central de Abastos',
      'DISPONIBILIDAD de flores — estacional',
      'ZONA DE ENTREGA — limites exactos',
      'HORA DE CORTE — un pedido despues del corte NO llega hoy',
      'CAPACIDAD en 14 feb/10 mayo — se agotan dias antes',
    ],
    crisisProtocols: [
      'ENTREGA FALLIDA en 14 feb/10 mayo: MAXIMA URGENCIA EMOCIONAL. Activar backup (Rappi, Uber Direct). Reemplazo + disculpa.',
      'FLORES MARCHITAS: Reemplazo en <24h con foto de evidencia. Reembolso si no se puede.',
      'BODA con error en decoracion: Escalar a florista principal INMEDIATAMENTE.',
    ],
    fallbackPhrase,
  },

  tienda_ropa: {
    vertical: 'tienda_ropa',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Tienda de Ropa',
    software: [
      { name: 'Shopify', price: '$780+ MXN/mes', description: '53.2% fashion e-commerce MX' },
      { name: 'TiendaNube', price: 'Gratis-$999 MXN/mes', description: 'Plan gratuito en Mexico' },
      { name: 'SIFO Ropa', price: 'License-based', description: 'POS con talla/color' },
      { name: 'Multicomercio', price: '$1,289+ MXN', description: 'Boutique POS 4 listas de precios' },
    ],
    apis: [
      'Shopify REST + GraphQL API',
      'TiendaNube API',
      'Leadsales WhatsApp CRM API',
    ],
    topFaqs: [
      'Tienen esta prenda en talla X?',
      'Cual es el precio?',
      'Envio a [location]?',
      'Politica de devoluciones?',
      'Nuevas colecciones?',
      'Meses sin intereses?',
      'Tienda fisica?',
      'Hacen apartado?',
      'Catalogo por WhatsApp?',
      'Cuanto tarda el envio?',
    ],
    neverHallucinate: [
      'STOCK por talla/color — cambia constantemente',
      'PROMOCIONES — solo las vigentes',
      'TIEMPOS DE ENVIO — varian por paqueteria y ubicacion',
      'POLITICA DE DEVOLUCION — terminos exactos, PROFECO aplica',
      'MSI — bancos y monto minimo especificos',
      'APARTADO — terminos exactos',
    ],
    crisisProtocols: [
      'PAQUETE EXTRAVIADO: Rastrear con paqueteria. Reenvio o reembolso.',
      'PRODUCTO DEFECTUOSO: Cambio inmediato, envio prepagado de regreso.',
      'QUEJA PROFECO: Escalar a direccion. Cooperar.',
    ],
    fallbackPhrase,
  },

  papeleria: {
    vertical: 'papeleria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Papeleria',
    software: [
      { name: 'SICAR', price: '$4,940+ MXN', description: '120K+ negocios MX — listas escolares' },
      { name: 'Eleventa', price: '$1,499-3,499 MXN lifetime', description: '7,500 productos precargados + offline' },
      { name: 'Aspel CAJA', price: '$905-3,427 MXN', description: 'POS hasta 10 listas de precios' },
    ],
    apis: [
      'SICAR limited',
      'Eleventa limited',
    ],
    topFaqs: [
      'Tienen la lista de utiles de [escuela]?',
      'Cuanto cuesta imprimir/copiar?',
      'Tienen [producto especifico]?',
      'Envios?',
      'Precio de mayoreo?',
      'Imprimen a color?',
      'Hacen engargolado/encuadernado?',
      'Aceptan tarjeta?',
      'Horario?',
      'Papeleria para empresas?',
    ],
    neverHallucinate: [
      'LISTAS DE UTILES — deben coincidir EXACTAMENTE con la lista de la escuela. Lista equivocada = padres furiosos y devoluciones.',
      'PRECIOS de impresion — B&N vs. color, por hoja',
      'STOCK — en back-to-school cambia por hora',
      'PRECIOS de mayoreo — variables por volumen',
    ],
    crisisProtocols: [
      'LISTA EQUIVOCADA entregada: Cambio inmediato sin costo. Disculpa.',
      'IMPRESORA descompuesta en back-to-school: Informar clientes, sugerir alternativas cercanas.',
    ],
    fallbackPhrase,
  },

  ferreteria: {
    vertical: 'ferreteria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Ferreteria',
    software: [
      { name: 'SICAR', price: '$4,940+ MXN', description: 'Busqueda inteligente + sugerencias compatibles' },
      { name: 'ManagementPro', price: '$11,500 MXN kit completo', description: 'Auto-restock' },
      { name: 'Multicomercio', price: '$1,289+ MXN', description: '4 listas precios + venta por pieza/kg/metro' },
    ],
    apis: [
      'SICAR limited',
      'ManagementPro limited',
      'Multicomercio limited',
    ],
    topFaqs: [
      'Tienen [producto]?',
      'Precio de [producto]?',
      'Servicio a domicilio?',
      'Precio de mayoreo?',
      'Cuenta para contratistas?',
      'Que me recomienda para [tarea]?',
      'Aceptan tarjeta?',
      'Facturacion?',
      'Horario?',
      'Hacen cortes de material?',
    ],
    neverHallucinate: [
      'ESPECIFICACIONES TECNICAS — error puede causar falla estructural/electrica',
      'PRECIOS por nivel (4+ niveles) — muy variable',
      'STOCK de 50,000+ SKUs — verificar',
      'COMPATIBILIDAD de productos — no adivinar',
      'MEDIDAS/DIMENSIONES — deben ser exactas',
    ],
    crisisProtocols: [
      'PRODUCTO DEFECTUOSO que causo dano: Documentar, preservar producto. Referir a PROFECO. Seguro de RC.',
      'ACCIDENTE con producto: Primeros auxilios, 911 si grave. Documentar.',
    ],
    fallbackPhrase,
  },

  abarrotes: {
    vertical: 'abarrotes',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Tienda de Abarrotes',
    software: [
      { name: 'Eleventa', price: '$1,299-3,499 MXN lifetime', description: 'Gold standard abarrotes — fiado digital, recargas, caducidades' },
      { name: 'SICAR', price: '$4,940+ MXN', description: 'Monedero electronico' },
      { name: 'Tiendatek', price: 'Custom', description: '50K+ productos precargados, recargas' },
      { name: 'AbarrotesPDV', price: 'GRATIS', description: 'POS basico gratis' },
    ],
    apis: [
      'Eleventa limited',
      'SICAR limited',
      'Sifio API (fiado recovery)',
    ],
    topFaqs: [
      'Tienen [producto]?',
      'A cuanto el [producto]?',
      'Me puede fiar?',
      'Hacen recargas?',
      'Pagan servicios (luz, agua)?',
      'Tienen [marca]?',
      'A que hora abren/cierran?',
      'Aceptan tarjeta?',
      'Venden por mayoreo?',
      'Envio a domicilio?',
    ],
    neverHallucinate: [
      'PRECIOS — cambian semanalmente con proveedores',
      'SALDOS DE FIADO — dato EXTREMADAMENTE sensible. Un error destruye relaciones de decadas.',
      'STOCK de perecederos — cambia diario',
      'CADUCIDADES — implicaciones legales y de salud',
      'RECARGAS — carriers disponibles deben verificarse',
    ],
    crisisProtocols: [
      'PRODUCTO CADUCO vendido: Reembolso inmediato. Si hay dano a salud, COFEPRIS.',
      'DISPUTA DE FIADO: NUNCA tomar partido. Referir a dueno para revision presencial de registros.',
      'ROBO: Contactos de emergencia, cierre temporal si es necesario.',
    ],
    fallbackPhrase,
  },

  libreria: {
    vertical: 'libreria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Libreria',
    software: [
      { name: 'SICAR Librerias', price: '$4,940+ MXN', description: 'Busqueda titulo/autor/editorial' },
      { name: 'INTAC PyME', price: 'Gratis basico', description: 'Apartados + catalogo web' },
      { name: 'Alegra POS', price: '$1,289+ MXN/mes', description: 'POS + REST API' },
    ],
    apis: [
      'Alegra REST API',
      'Google Books API (gratis)',
      'Open Library API (gratis)',
      'INDAUTOR RISBN5.1',
    ],
    topFaqs: [
      'Tienen el libro [titulo]?',
      'Cuanto cuesta?',
      'Pueden conseguir [libro especifico]?',
      'Libros de [autor/tema]?',
      'Hacen envios?',
      'Cuando llega mi pedido especial?',
      'Libros de texto para [escuela]?',
      'Eventos/club de lectura?',
      'Aceptan devoluciones?',
      'Recomendaciones de [genero]?',
    ],
    neverHallucinate: [
      'DISPONIBILIDAD — inventario cambia constantemente',
      'EDICION — edicion equivocada de libro de texto = inutil para el estudiante',
      'TIEMPOS de pedido especial — dependen de editorial',
      'EVENTOS — fechas, ponentes, capacidad verificados',
      'PRECIOS — ley de precio unico aplica 36 meses',
      'AUTOR — no confundir autores con nombres similares',
    ],
    crisisProtocols: [
      'EDICION EQUIVOCADA vendida: Cambio incondicional.',
      'LIBRO PIRATA vendido: Retirar inmediatamente. Riesgo de Ley Federal del Derecho de Autor (penal).',
      'EVENTO cancelado: Notificar a todos los registrados inmediatamente.',
    ],
    fallbackPhrase,
  },

  joyeria: {
    vertical: 'joyeria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Joyeria',
    software: [
      { name: 'SICAR', price: '$4,940+ MXN', description: 'Anti-robo hormiga' },
      { name: 'INTAC Joyeria', price: 'Free trial', description: 'Prevencion de robo' },
      { name: 'Bind ERP', price: '$890+ MXN/mes', description: 'Multi-almacen con API' },
    ],
    apis: [
      'Bind ERP API',
      'SICAR limited',
    ],
    topFaqs: [
      'De que kilates es?',
      'Cuanto cuesta esta cadena/anillo?',
      'Diseno personalizado?',
      'Reparan mi reloj/cadena?',
      'Garantia?',
      'Hacen avaluos?',
      'Meses sin intereses?',
      'Certificado de autenticidad?',
      'Politica de cambios de talla?',
      'Hacen grabado?',
    ],
    neverHallucinate: [
      'PRECIOS de metales preciosos — fluctuan DIARIO',
      'KILATES/CALIDAD — especificaciones exactas requieren verificacion',
      'GARANTIA — terminos exactos',
      'AVALUOS — requieren evaluacion profesional presencial',
      'TIEMPO de entrega custom — varia por complejidad',
      'CERTIFICACIONES — GIA, IGI deben ser verificadas',
    ],
    crisisProtocols: [
      'ROBO/ASALTO: 911 inmediatamente. CCTV. Seguro. Inventario de faltantes.',
      'PIEZA PERDIDA en reparacion: Documentar ingreso. Seguro. Compensacion a valor de mercado.',
      'AVALUO DISPUTADO: Referir a tercero certificado.',
    ],
    fallbackPhrase,
  },

  jugueteria: {
    vertical: 'jugueteria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Jugueteria',
    software: [
      { name: 'ManagementPro', price: '$904+ MXN/ano', description: 'Promociones estacionales + por edad' },
      { name: 'SICAR', price: '$4,940+ MXN', description: 'Sugerencias alternativas inteligentes' },
      { name: 'Eleventa', price: '$1,499 MXN lifetime', description: 'POS basico' },
    ],
    apis: [
      'SICAR limited',
      'Bsale API (Mercado Libre integration)',
    ],
    topFaqs: [
      'Que juguete para nino de X anos?',
      'Tienen [juguete/personaje especifico]?',
      'Cuanto cuesta?',
      'Servicio de envoltura?',
      'Es seguro para bebes?',
      'Politica de cambios?',
      'Envios?',
      'Pinatas/dulceros/decoracion para fiesta?',
      'Precio de mayoreo para dulceros?',
      'Tienen juguetes de Navidad/Dia del Nino?',
    ],
    neverHallucinate: [
      'EDAD RECOMENDADA — tiene implicaciones LEGALES (NOM-015)',
      'SEGURIDAD del producto — nunca afirmar que es seguro sin verificar etiqueta',
      'STOCK — juguetes trending se agotan rapidamente',
      'PRECIOS de temporada — pueden subir',
      'MARCAS disponibles — no inventar que tienen algo que no',
    ],
    crisisProtocols: [
      'RECALL/RETIRO de producto: Remover de venta, notificar compradores (requiere historial POS), seguir instrucciones PROFECO.',
      'LESION por producto: Preservar producto, documentar, referir a medico, reportar a PROFECO.',
    ],
    fallbackPhrase,
  },

  zapateria: {
    vertical: 'zapateria',
    category: 'COMERCIOS_Y_RETAIL',
    displayName: 'Zapateria',
    software: [
      { name: 'SICAR Zapaterias', price: 'Custom pricing', description: 'Inventario talla/color/modelo + lealtad' },
      { name: 'ManagementPro Zapaterias', price: '$96 MXN/mes o $2,199 lifetime', description: '2,000+ reportes + auto-reorder' },
      { name: 'SIFO Zapaterias', price: 'License-based', description: 'Talla/color/modelo + promociones' },
      { name: 'Vendy Moda', price: 'Trial 7 dias', description: 'Multi-sucursal' },
    ],
    apis: [
      'Limited across all. WhatsApp catalogo es la integracion principal.',
    ],
    topFaqs: [
      'Tienen este modelo en talla X?',
      'Precio?',
      'Garantia?',
      'Politica de cambios?',
      'Zapatos ortopedicos?',
      'Como se mi talla?',
      'Envios?',
      'Meses sin intereses?',
      'Cuando llega nueva coleccion?',
      'Tienen para ninos?',
    ],
    neverHallucinate: [
      'DISPONIBILIDAD POR TALLA — el dato #1 mas critico. Media talla importa.',
      'CONVERSION DE TALLAS — varia entre marcas (un 7 Nike no es un 7 Flexi)',
      'GARANTIA — terminos PROFECO aplican',
      'ORTOPEDICO — no hacer claims medicos',
      'STOCK — no afirmar disponibilidad sin verificar',
    ],
    crisisProtocols: [
      'ZAPATO DEFECTUOSO: Cambio inmediato. Si causo lesion, documentar y referir a medico.',
      'TALLA INCORRECTA enviada: Envio prepagado de devolucion + reenvio correcto.',
      'QUEJA PROFECO: Escalar a direccion. Cooperar completamente.',
    ],
    fallbackPhrase,
  },
};
