import Link from 'next/link';
import { MessageSquare, Phone, Zap, Clock, Shield, BarChart3, ChevronRight, Star } from 'lucide-react';
export default function LandingPage() {
  return(<div className="min-h-screen">
    <nav className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto"><h1 className="text-2xl font-bold text-blue-600">atiende.ai</h1><div className="flex items-center gap-4"><Link href="/login" className="text-gray-600 text-sm">Iniciar sesión</Link><Link href="/register" className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700">Prueba gratis</Link></div></nav>
    <section className="text-center px-6 py-20 max-w-4xl mx-auto"><div className="inline-block bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-medium mb-4">🤖 Tu asistente AI en WhatsApp</div><h1 className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight">Tu negocio contesta clientes<br/><span className="text-blue-600">24/7, sin contratar a nadie</span></h1><p className="mt-6 text-lg text-gray-600 max-w-2xl mx-auto">Responde WhatsApp, agenda citas y toma pedidos automáticamente. En español mexicano natural. Listo en 10 minutos.</p><div className="flex gap-3 justify-center mt-8"><Link href="/register" className="bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 flex items-center gap-2">Empezar gratis<ChevronRight className="w-4 h-4"/></Link></div></section>
    <section className="bg-gray-50 px-6 py-16"><div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">{[{icon:MessageSquare,title:'Chat WhatsApp AI',desc:'Responde 24/7. Agenda citas. En español mexicano.'},{icon:Phone,title:'Voz AI',desc:'Contesta llamadas con voz natural.'},{icon:Zap,title:'15 Agents',desc:'Cobrador, reseñas, NPS. Activa con 1 click.'},{icon:Clock,title:'10 minutos',desc:'Sin conocimiento técnico.'},{icon:Shield,title:'Anti-alucinación',desc:'NUNCA inventa precios.'},{icon:BarChart3,title:'Dashboard ROI',desc:'Ve cuánto te ahorra.'}].map(f=>(<div key={f.title} className="bg-white p-6 rounded-xl border"><f.icon className="w-8 h-8 text-blue-600 mb-3"/><h3 className="font-bold mb-2">{f.title}</h3><p className="text-sm text-gray-600">{f.desc}</p></div>))}</div></section>
    <section id="precios" className="px-6 py-16 max-w-5xl mx-auto"><h2 className="text-3xl font-bold text-center mb-10">Planes</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{[{name:'Básico',price:'$499',features:['Chat WhatsApp AI','25 industrias','500 msgs/mes']},{name:'Pro',price:'$999',pop:true,features:['Todo de Básico','2,000 msgs/mes','ROI Calculator','Marketplace agents']},{name:'Premium',price:'$1,499',features:['Todo de Pro','Ilimitado','Voz AI','Soporte prioritario']}].map(p=>(<div key={p.name} className={`rounded-xl border p-6 ${p.pop?'border-blue-500 ring-2 ring-blue-500 bg-blue-50':''}`}>{p.pop&&<span className="bg-blue-600 text-white text-xs font-bold px-2 py-1 rounded-full">Popular</span>}<h3 className="text-xl font-bold mt-2">{p.name}</h3><p className="mt-2"><span className="text-3xl font-bold">{p.price}</span><span className="text-gray-500"> MXN/mes</span></p><ul className="mt-4 space-y-2">{p.features.map(f=><li key={f} className="flex items-center gap-2 text-sm"><Star className="w-3 h-3 text-blue-500"/>{f}</li>)}</ul><Link href="/register" className={`block text-center mt-6 py-2 rounded-lg font-medium ${p.pop?'bg-blue-600 text-white':'bg-gray-100 text-gray-700'}`}>Empezar gratis</Link></div>))}</div><p className="text-center text-gray-400 text-sm mt-6">14 días gratis. Sin tarjeta. Precios + IVA.</p></section>
    <footer className="bg-gray-900 text-gray-400 px-6 py-10"><div className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between"><div><h3 className="text-white font-bold text-lg">atiende.ai</h3><p className="text-sm mt-1">Asistentes AI para negocios mexicanos</p></div><div className="mt-4 md:mt-0 text-sm"><p>Mérida, Yucatán, México</p><p>contacto@atiende.ai</p></div></div></footer></div>);
}
