import type { VerticalEnum, VerticalQuestion } from '../types';

export const bellezaQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  salon_belleza: [
    {
      number: 1,
      text: 'Nombre del salon',
      why: 'Tal como aparece en fachada y redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario por dia',
      why: 'Incluir si sabados medio dia o domingo',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Lista COMPLETA de servicios con precio, duracion y nivel de estilista',
      why: 'Corte dama/caballero/nino, tinte raiz/completo, mechas/balayage/babylights, alisado, permanente, extensiones, peinado, maquillaje, depilacion, tratamientos capilares. PRECIO EXACTO por servicio',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'Los precios son la causa #1 de confrontacion en salones. Con la lista exacta, tu bot evita malentendidos.',
    },
    {
      number: 4,
      text: 'Estilistas y sus especialidades',
      why: 'Nombre, dias que trabajan, especialidad. Si hay niveles (junior, senior, master) con diferentes precios',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Aceptan walk-in o solo cita?',
      why: 'Y que porcentaje es walk-in vs. cita',
      inputType: 'text',
      required: true,
      followUpInsight:
        "El 60% de los mensajes de WhatsApp son '¿Tienen espacio hoy?'. Tu bot respondera al instante.",
    },
    {
      number: 6,
      text: 'Politica de cancelacion y no-show',
      why: 'Anticipacion, penalizacion, deposito',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Anticipo requerido para cita?',
      why: 'Monto o porcentaje. Reembolsable?',
      inputType: 'text',
      required: false,
    },
    {
      number: 8,
      text: 'Productos que venden',
      why: 'Marcas (Kerastase, Wella, L\'Oreal, Olaplex, etc.), tipo, precios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 9,
      text: 'Programa de lealtad',
      why: 'Puntos, descuento por referido, 5ta visita gratis, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Promociones recurrentes',
      why: 'Lunes de descuento, paquetes novia, dia de la madre, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, SPEI, MSI (para servicios premium como alisados)',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 12,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 13,
      text: 'Estacionamiento',
      why: 'Propio o cercano',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Redes sociales',
      why: 'Instagram con portfolio es CRITICO para salones',
      inputType: 'text',
      required: false,
    },
    {
      number: 15,
      text: 'Tono del chatbot',
      why: "Amigable, empoderador, experto. 'Vamos a dejarte increible.'",
      inputType: 'select',
      required: true,
    },
    {
      number: 16,
      text: 'Contacto de escalacion',
      why: 'Duena o estilista senior',
      inputType: 'text',
      required: true,
    },
  ],

  barberia: [
    {
      number: 1,
      text: 'Nombre de la barberia',
      why: 'Como aparece en fachada',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'Muchas barberias abren hasta las 20-21h',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Lista de servicios con precios',
      why: 'Corte clasico, degradado/fade, corte + barba, rasurado navaja, diseno, tratamiento capilar, coloracion. PRECIOS EXACTOS',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El precio del corte es la pregunta #1. Tu bot respondera precios exactos por servicio.',
    },
    {
      number: 4,
      text: 'Barberos y sus especialidades',
      why: 'Nombre, dias, estilo (clasico, moderno, fade master)',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Walk-in vs. cita — proporcion',
      why: '60-70% walk-in es tipico. Como manejan la fila?',
      inputType: 'text',
      required: true,
    },
    {
      number: 6,
      text: 'Tiempo estimado de espera walk-in',
      why: 'Promedio por dia/hora',
      inputType: 'text',
      required: false,
    },
    {
      number: 7,
      text: 'Membresias/suscripciones',
      why: 'Basica ($800/mes: 2 cortes + 1 barba), Premium ($1,200: 3 cortes + 2 barba + tratamiento), VIP ($1,800: ilimitado). DETALLES de cada nivel',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Productos de grooming que venden',
      why: 'Pomada, aceite de barba, shampoo, aftershave. Marcas y precios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 9,
      text: 'Experiencia incluida',
      why: 'Cerveza, cafe, whiskey? Videojuegos? Musica? Es parte del marketing',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Servicio a domicilio o para eventos',
      why: 'Bodas, despedidas, corporativos. Precio',
      inputType: 'text',
      required: false,
    },
    {
      number: 11,
      text: 'Paquetes especiales',
      why: 'Paquete novio, paquete padre-hijo, grooming completo',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 12,
      text: 'Formas de pago',
      why: 'Tarjeta, efectivo, SPEI',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 13,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: "Cool, masculino pero inclusivo. 'Bro' vibes pero profesional",
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Barbero principal o dueno',
      inputType: 'text',
      required: true,
    },
  ],
  spa: [
    {
      number: 1,
      text: 'Nombre del spa',
      why: 'Incluir si es spa de hotel o independiente',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'Muchos spas abren 9-21h',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Menu de tratamientos COMPLETO',
      why: 'Masajes (relajante, descontracturante, hot stones, lomi lomi, shiatsu), faciales (limpieza, hidratacion, anti-age, peeling), corporales (exfoliacion, envoltura, reductivo, drenaje linfatico), temazcal, circuito de hidroterapia, manicure/pedicure spa. PRECIO y DURACION de cada uno',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El menu de tratamientos con precios es lo que mas preguntan. Tu bot lo compartira al instante.',
    },
    {
      number: 4,
      text: 'Paquetes de parejas',
      why: 'Que incluye, precio, duracion',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Paquetes wellness / dia de spa',
      why: 'Full day, half day, que incluye (alberca, sauna, jacuzzi, te, snack)',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 6,
      text: 'Terapeutas — genero y numero',
      why: 'Algunos clientes tienen preferencia de genero. Cuantos terapeutas tienen',
      inputType: 'text',
      required: false,
    },
    {
      number: 7,
      text: 'Contraindicaciones por tratamiento',
      why: 'Embarazo, presion alta, cirugia reciente, marcapaso, varices, cancer. LISTA POR TRATAMIENTO',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 8,
      text: 'Preparacion pre-tratamiento',
      why: 'Que debe/no debe hacer el cliente antes (no comer, llegar 15min antes, etc)',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'Tarjetas de regalo',
      why: 'Disponibles? Montos? Como comprar?',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Productos que venden',
      why: 'Lineas de skincare, aromaterapia, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 11,
      text: 'Circuito de hidroterapia',
      why: 'Incluido? Separado? Que tiene (alberca, sauna, vapor, regaderas sensoriales, jacuzzi)',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 12,
      text: 'Formas de pago',
      why: 'MSI importante para paquetes premium',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 13,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: 'Sereno, relajante, premium. Usar lenguaje de bienestar',
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Coordinadora de spa o gerente',
      inputType: 'text',
      required: true,
    },
  ],
  gimnasio: [
    {
      number: 1,
      text: 'Nombre del gimnasio',
      why: 'Como aparece en fachada',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'L-V, sabado, domingo, festivos',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Planes de membresia COMPLETOS',
      why: 'Mensual, trimestral, semestral, anual. Estudiantil, corporativo, familiar, pareja. PRECIO EXACTO de cada uno',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El precio de la membresia es la pregunta #1. Tu bot respondera planes y precios al instante.',
    },
    {
      number: 4,
      text: 'Que incluye cada plan',
      why: 'Acceso a que areas (pesas, cardio, funcional, alberca, sauna). Diferencias entre planes',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Clases grupales — horario completo',
      why: 'Spinning, yoga, pilates, zumba, crossfit, box, HIIT, funcional. Dia, hora, duracion, instructor',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Entrenamiento personal',
      why: 'Disponible? Precio por sesion, paquetes (4, 8, 12 sesiones). Entrenadores y especialidades',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 7,
      text: 'Pase por dia o clase de prueba',
      why: 'Disponible? Precio? Gratis la primera vez?',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Instalaciones completas',
      why: 'Pesas, cardio, funcional, alberca, sauna, vapor, regaderas, vestidores, lockers, estacionamiento',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 9,
      text: 'Control de acceso',
      why: 'Huella, facial, QR, tarjeta, codigo',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Politica de cancelacion de membresia',
      why: 'Minimo de permanencia? Cargos? Proceso? Congelamiento disponible?',
      inputType: 'text',
      required: true,
    },
    {
      number: 11,
      text: 'Congelamiento de membresia',
      why: 'Permitido? Cuantos meses? Costo?',
      inputType: 'text',
      required: false,
    },
    {
      number: 12,
      text: 'Restricciones de edad',
      why: 'Minima (14, 16, 18?). Requiere acompanante?',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Politica de invitados',
      why: 'Pueden llevar? Costo? Limite por mes?',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Toallas, candados, lockers',
      why: 'Incluidos? Renta? Venta?',
      inputType: 'text',
      required: false,
    },
    {
      number: 15,
      text: 'Formas de pago',
      why: 'Domiciliacion, tarjeta, efectivo, MSI',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 16,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 17,
      text: 'Nutricionista/fisioterapeuta en el gym?',
      why: 'Disponible? Costo adicional?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 18,
      text: 'Tono del chatbot',
      why: 'Motivacional, energetico pero no agresivo. Inclusivo',
      inputType: 'select',
      required: true,
    },
    {
      number: 19,
      text: 'Contacto de escalacion',
      why: 'Gerente o coordinador de ventas',
      inputType: 'text',
      required: true,
    },
  ],
  nail_salon: [
    {
      number: 1,
      text: 'Nombre del salon de unas',
      why: 'Como aparece en fachada/redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'Muchos abren L-S',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Menu COMPLETO de servicios con precios POR TAMANO',
      why: 'Manicure basico ($150-230), gel semipermanente ($180-320), acrilicas S/M/L ($350-450+), relleno (~$530), polygel (~$530), pedicure basico ($180-250), esculturales (~$650). Nail art extra ($30-200)',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'Los precios por tipo de servicio y tamano son la pregunta #1. Tu bot respondera al instante.',
    },
    {
      number: 4,
      text: 'Galeria de disenos',
      why: 'Instagram, Pinterest, catalogo fisico. Link a galeria digital',
      inputType: 'text',
      required: false,
    },
    {
      number: 5,
      text: 'Productos/marcas que usan',
      why: 'OPI, Gelish, Kiara Sky, etc. CRITICO para alergias (acrilatos, formaldehido, tolueno)',
      inputType: 'text',
      required: true,
    },
    {
      number: 6,
      text: 'Nail techs — nombres y especialidades',
      why: 'Quien hace mejor acrilicas, quien es experta en nail art',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 7,
      text: 'Duracion por servicio',
      why: 'Manicure 30-45min, acrilicas 60-90min, etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Walk-in vs. cita',
      why: 'Proporcion y tiempo de espera',
      inputType: 'text',
      required: true,
    },
    {
      number: 9,
      text: 'Protocolos de higiene',
      why: 'Autoclave, herramientas desechables, esterilizacion. Los clientes preguntan',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Politica de cancelacion / no-show',
      why: 'Anticipacion, penalizacion',
      inputType: 'text',
      required: true,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, SPEI',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 12,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 13,
      text: 'Paquetes y lealtad',
      why: '5 rellenos 1 gratis, paquete manos+pies, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: 'Girly, trendy, divertido. Emojis permitidos aqui',
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Duena o nail tech principal',
      inputType: 'text',
      required: true,
    },
  ],
  estetica: [
    {
      number: 1,
      text: 'Nombre de la clinica estetica',
      why: 'Como aparece en registro',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'L-V y sabados es tipico',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Medico/especialista a cargo',
      why: 'Dr./Dra. [nombre]. Cedula. Certificaciones',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tratamientos faciales con precios',
      why: 'Limpieza profunda, hydrafacial, peeling quimico, microdermoabrasion, radiofrecuencia, HIFU, PRP facial, mesoterapia. PRECIO y DURACION',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 5,
      text: 'Tratamientos corporales con precios',
      why: 'Criolipolisis, cavitacion, carboxiterapia, presoterapia, drenaje linfatico, reductivo, masaje modelador. PRECIO y DURACION',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 6,
      text: 'Tratamientos inyectables con precios',
      why: 'Toxina botulinica (botox), acido hialuronico (rellenos), hilos tensores, enzimas. PRECIO POR ZONA/UNIDAD',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 7,
      text: 'Numero de sesiones recomendadas por tratamiento',
      why: 'Paquetes: 4, 6, 8, 10 sesiones. Precio por paquete',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 8,
      text: 'Contraindicaciones POR TRATAMIENTO',
      why: 'Embarazo, lactancia, marcapasos, cancer, anticoagulantes, diabetes descontrolada, infecciones activas. LISTA ESPECIFICA',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 9,
      text: 'Instrucciones pre y post tratamiento',
      why: 'Por cada procedimiento: que hacer y que evitar antes y despues',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 10,
      text: 'Consentimiento informado',
      why: 'Formato escrito obligatorio. Digital o papel?',
      inputType: 'text',
      required: false,
    },
    {
      number: 11,
      text: 'Fotos antes/despues — protocolo LFPDPPP',
      why: 'Consentimiento ESCRITO separado para: historial clinico, marketing/redes, educacion. REVOCABLE en cualquier momento',
      inputType: 'text',
      required: false,
    },
    {
      number: 12,
      text: 'Resultados — que prometen y que no',
      why: "Nunca prometer resultados especificos. Usar 'puede contribuir a mejorar...'",
      inputType: 'text',
      required: true,
    },
    {
      number: 13,
      text: 'Formas de pago',
      why: 'MSI CRITICO para procedimientos de $3,000-30,000+ MXN',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 14,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 15,
      text: 'Tono del chatbot',
      why: 'Profesional-premium pero calido. Sensible con imagen corporal',
      inputType: 'select',
      required: true,
    },
    {
      number: 16,
      text: 'Contacto de escalacion',
      why: 'Medico a cargo para reacciones adversas',
      inputType: 'text',
      required: true,
    },
  ],
};
