import type { VerticalEnum, VerticalQuestion } from '../types';

export const gastronomiaQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  restaurante: [
    {
      number: 1,
      text: 'Nombre del restaurante',
      why: 'Exactamente como aparece en fachada y redes sociales',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion completa con link de Google Maps',
      why: 'Imprescindible para enviar ubicacion por WhatsApp',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario de operacion por dia',
      why: 'Incluir si varia entre servicio de comida y cena',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tipo de cocina',
      why: 'Mexicana, italiana, japonesa, mariscos, fusion, etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 5,
      text: 'Menu COMPLETO con precios',
      why: 'Cada platillo, descripcion breve, precio. Organizado por categoria',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El menu es la base de todo. Los clientes preguntan precios y platillos en el 80% de las conversaciones por WhatsApp.',
    },
    {
      number: 6,
      text: 'Alergenos e ingredientes criticos por platillo',
      why: 'Gluten, lacteos, mariscos, nueces, soya. Obligatorio para seguridad',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Opciones vegetarianas, veganas, sin gluten',
      why: 'Cuales platillos especificamente',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Servicio de reservaciones',
      why: 'Si/No. Capacidad maxima. Anticipacion requerida. Deposito. Politica de no-show',
      inputType: 'text',
      required: true,
    },
    {
      number: 9,
      text: 'Entregas a domicilio',
      why: 'Propio, UberEats, Rappi, DiDi Food. Zonas de cobertura. Minimo de pedido. Costo de envio',
      inputType: 'text',
      required: true,
      followUpInsight:
        'Los restaurantes con delivery responden 3x mas mensajes. El bot puede tomar pedidos automaticamente.',
    },
    {
      number: 10,
      text: 'Servicio para llevar (takeout)',
      why: 'Disponible? Tienen descuento vs. comer ahi?',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, MSI (monto minimo, bancos), propina sugerida',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        "Pregunta top 7 de clientes: 'Aceptan tarjeta?' — tu bot lo respondera al instante.",
    },
    {
      number: 12,
      text: 'Facturacion CFDI',
      why: 'Disponible? Proceso (QR en ticket, solicitar por WhatsApp)',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 13,
      text: 'Estacionamiento',
      why: 'Propio, valet, calle. Costo. Convenio',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Eventos privados',
      why: 'Capacidad, paquetes, presupuesto minimo, menu especial',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 15,
      text: 'Promociones vigentes',
      why: 'Happy hour, 2x1, paquetes familiares, dia de la semana especial',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Programa de lealtad',
      why: 'Puntos, decima comida gratis, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 17,
      text: 'Areas especiales',
      why: 'Terraza, salon privado, barra, area infantil, pet friendly',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 18,
      text: 'WiFi',
      why: 'Disponible? Password?',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'Musica en vivo',
      why: 'Dias, horarios, genero',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Redes sociales',
      why: 'Instagram, Facebook, TripAdvisor',
      inputType: 'text',
      required: false,
    },
    {
      number: 21,
      text: 'Tono del chatbot',
      why: 'Casual-amigable para casual dining, formal para fine dining',
      inputType: 'select',
      required: true,
    },
    {
      number: 22,
      text: 'Contacto de escalacion',
      why: 'Gerente o encargado para quejas o reservaciones grandes',
      inputType: 'text',
      required: true,
    },
  ],

  taqueria: [
    {
      number: 1,
      text: 'Nombre de la taqueria',
      why: 'Tal como aparece en letrero/redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion con referencias',
      why: 'Incluir esquina, cerca de que',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario — y si cierran cuando se acaba el producto',
      why: "'Cerramos cuando se acaba el pastor' es realidad mexicana. El bot debe saber esto",
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'MENU COMPLETO con precios',
      why: 'Cada taco, precio por pieza. Orden de tacos, gringas, quesadillas, volcanes, campechanos, alambres, tortas',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'En taquerias, el precio por taco es la pregunta #1. Con el menu completo, tu bot atiende al instante.',
    },
    {
      number: 5,
      text: 'Tipos de carne disponibles',
      why: 'Pastor, bistec, suadero, longaniza, tripa, cabeza, lengua, chorizo, campechano. Cuales NO tienen',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        "Los clientes siempre preguntan 'Tienen suadero/tripa/lengua?'. Tu bot sabra exactamente que ofrecer.",
    },
    {
      number: 6,
      text: 'Tipo de tortilla',
      why: 'Maiz, harina, ambas. Si cobran extra por harina',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Salsas disponibles',
      why: 'Verde, roja, habanero, guacamole. Cuales son picantes. Si el guacamole tiene costo extra',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Venta por kilo',
      why: 'Disponible? Precio por kilo de cada carne. Minimo de compra',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'Complementos',
      why: 'Frijoles, cebollitas, nopales, queso, cebolla asada. Precios si aplica',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Bebidas',
      why: 'Aguas frescas, refrescos, cerveza (REQUIERE LICENCIA). Precios',
      inputType: 'text',
      required: true,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: '60-80% de taquerias son cash-heavy. Si aceptan tarjeta, especificar',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 12,
      text: 'Delivery',
      why: 'Plataformas? Propio? Zona? Minimo?',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Facturacion CFDI',
      why: 'Muchas taquerias informales no facturan — es valido informar',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: "Casual, directo, rapido. 'Que te ponemos?' vibes",
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Dueno o encargado',
      inputType: 'text',
      required: true,
    },
  ],

  // Sprint 2 stubs
  cafeteria: [],
  panaderia: [],
  bar_cantina: [],
  food_truck: [],
};
