import type { VerticalEnum, VerticalQuestion } from '../types';

export const hospedajeQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  hotel: [
    {
      number: 1,
      text: 'Nombre del hotel',
      why: 'Exacto, incluyendo estrellas/categoria',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y como llegar desde aeropuerto/terminal',
      why: 'Distancia, tiempo, opciones de transporte',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Clasificacion SECTUR',
      why: 'Estrellas. Registro Nacional de Turismo (RNT)',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tipos de habitacion',
      why: 'Nombre, descripcion, capacidad maxima, cama(s), vista, m2, amenidades de cada tipo',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Tarifas por tipo de habitacion',
      why: 'Rack rate y si tienen tarifas dinamicas. Temporada alta vs baja. Rango o referir a motor de reservas',
      inputType: 'textarea',
      required: true,
      followUpInsight:
        'Las tarifas son la pregunta #1 en WhatsApp. Con rangos por temporada, tu bot responde al instante sin inventar precios.',
    },
    {
      number: 6,
      text: 'Check-in y check-out',
      why: 'Horarios. Early check-in / late check-out disponible? Costo?',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Que incluye la tarifa',
      why: 'Desayuno? WiFi? Estacionamiento? Gimnasio? Alberca?',
      inputType: 'textarea',
      required: true,
      followUpInsight:
        "Pregunta #3 de huespedes: '¿El desayuno esta incluido?' — tu bot lo resolvera en segundos.",
    },
    {
      number: 8,
      text: 'Restaurantes y bares del hotel',
      why: 'Nombre, tipo de cocina, horario, dress code, si necesita reservacion',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 9,
      text: 'Amenidades completas',
      why: 'Alberca (horario), gimnasio, spa, business center, salon de eventos, kids club. Horarios de cada uno',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Servicios adicionales',
      why: 'Room service, lavanderia, concierge, tours, transportacion. Precios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Politica de cancelacion',
      why: 'Por canal (directa vs. OTA). Penalizacion. Free cancellation deadline',
      inputType: 'text',
      required: true,
      followUpInsight:
        'La politica de cancelacion es critica. Un error aqui genera disputas y malas resenas.',
    },
    {
      number: 12,
      text: 'Politica de mascotas',
      why: 'Aceptan? Tamano maximo? Costo adicional? Areas permitidas',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Estacionamiento',
      why: 'Incluido o adicional? Cubierto? Valet? Costo',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Eventos/bodas/grupos',
      why: 'Salones, capacidad, paquetes, contacto del coordinador',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 15,
      text: 'Transfer aeropuerto',
      why: 'Ofrecen? Costo? Como reservar? Compartido o privado?',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Formas de pago',
      why: 'Tarjeta obligatoria para garantia? MSI? Tipos de cambio si aplica',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 17,
      text: 'Facturacion CFDI',
      why: 'Proceso. ISH (Impuesto Sobre Hospedaje 2-5% estatal) incluido',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 18,
      text: 'Idiomas del staff',
      why: 'Espanol, ingles, frances, aleman — relevante para hoteles turisticos',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'PMS actual',
      why: 'Para integracion con chatbot — Opera, Cloudbeds, otro?',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Motor de reservas web',
      why: 'URL para que el bot pueda enviar link de reserva directa',
      inputType: 'text',
      required: false,
    },
    {
      number: 21,
      text: 'Tono del chatbot',
      why: 'Formal-elegante para luxury, casual-amigable para boutique',
      inputType: 'select',
      required: true,
    },
    {
      number: 22,
      text: 'Contacto de escalacion',
      why: 'Front desk manager, revenue manager',
      inputType: 'text',
      required: true,
    },
  ],

  // Sprint 1 stubs — full questions coming in future sprints
  hotel_boutique: [],
  motel: [],
  glamping: [],
  bb_hostal: [],
  resort: [],
};
