import type { VerticalEnum, VerticalQuestion } from '../types';

export const saludQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  dental: [
    {
      number: 1,
      text: 'Nombre completo del consultorio o clinica',
      why: 'Exactamente como aparece en tu letrero y RFC',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion completa con referencias',
      why: 'Calle, numero, colonia, CP, ciudad, estado + como llegar',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario de atencion por dia de la semana',
      why: 'Lunes a viernes, sabado, domingo. Incluye si cierras a medio dia',
      inputType: 'text',
      required: true,
      followUpInsight:
        'Con horario de L-V 9-19, el chatbot capturara las consultas de las 19:01 en adelante — que es cuando la gente busca dentista despues del trabajo.',
    },
    {
      number: 4,
      text: 'Dias festivos o periodos de vacaciones',
      why: 'Semana Santa, Navidad, puentes — cuando cierras',
      inputType: 'text',
      required: false,
    },
    {
      number: 5,
      text: 'Nombre del dentista titular y especialidad',
      why: 'Dr./Dra. [nombre], Cirujano Dentista / Ortodoncista / etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 6,
      text: 'Cedula profesional y universidad (opcional — ayuda a que los pacientes verifiquen al doctor en el registro DGP, pero puedes omitirla)',
      why: 'Los pacientes a veces lo preguntan para verificar. Es opcional.',
      inputType: 'text',
      required: false,
    },
    {
      number: 7,
      text: 'Otros dentistas o especialistas en el consultorio',
      why: 'Nombre, especialidad y dias que atienden cada uno',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Lista COMPLETA de tratamientos con precios',
      why: 'Limpieza, resinas, endodoncia, corona, puente, implante, ortodoncia, blanqueamiento, extraccion, radiografia, guardas, etc. PRECIO EXACTO',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'Los precios son la pregunta #1 que hacen los pacientes por WhatsApp. Con esta lista, tu bot respondera al instante.',
    },
    {
      number: 9,
      text: 'Tratamientos que requieren valoracion previa antes de dar precio',
      why: 'Ej: implantes, ortodoncia, protesis — donde el precio depende del caso',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Duracion aproximada de cada tratamiento',
      why: 'Limpieza 40min, endodoncia 60-90min, etc',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Politica de primera cita / valoracion',
      why: 'Tiene costo? Cuanto? Es gratis? Incluye radiografia?',
      inputType: 'text',
      required: true,
    },
    {
      number: 12,
      text: 'Tipos de radiografia disponibles',
      why: 'Periapical, panoramica, cefalometrica. Costo de cada una',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 13,
      text: 'Marcas de materiales que usan',
      why: 'Importante para pacientes con alergias — ej: composites libres de BPA',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 14,
      text: 'Formas de pago aceptadas',
      why: 'Efectivo, tarjeta debito, credito, transferencia SPEI, Mercado Pago, MSI',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        'El 40% de los pacientes preguntan por MSI antes de agendar tratamientos grandes como implantes u ortodoncia.',
    },
    {
      number: 15,
      text: 'Emiten factura CFDI?',
      why: 'Si si, que datos necesitan del paciente (RFC, regimen, uso CFDI, CP)',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 16,
      text: 'Politica de cancelacion y no-show',
      why: 'Con cuanta anticipacion? Cobran penalizacion? Cuanto?',
      inputType: 'text',
      required: true,
    },
    {
      number: 17,
      text: 'Manejan urgencias dentales?',
      why: 'Dolor agudo, diente roto, absceso. Tienen horario de urgencias? Numero directo?',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 18,
      text: 'Esterilizacion y protocolos de higiene',
      why: 'Autoclave, desechables, protocolos COVID remanentes',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 19,
      text: 'Estacionamiento disponible?',
      why: 'Propio, calle, estacionamiento publico cercano. Costo',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Planes de financiamiento o pagos diferidos propios',
      why: 'Aparte de MSI bancarios, ofrecen pagos a meses directos?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 21,
      text: 'Seguro dental — aceptan alguno?',
      why: 'MetLife, GNP Dental, Dentegra, Plan Seguro, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 22,
      text: 'Consentimiento informado — formato digital o papel?',
      why: 'Obligatorio por NOM-013-SSA2-2015',
      inputType: 'text',
      required: false,
    },
    {
      number: 23,
      text: 'Programa de lealtad o referidos',
      why: 'Descuento por referir? Programa de puntos? Descuento familiar?',
      inputType: 'text',
      required: false,
    },
    {
      number: 24,
      text: 'Idiomas que hablan',
      why: 'Espanol, ingles, otro — importante en zonas turisticas',
      inputType: 'text',
      required: false,
    },
    {
      number: 25,
      text: 'Redes sociales y Google Maps link',
      why: 'Instagram, Facebook, Google Business Profile',
      inputType: 'text',
      required: false,
    },
    {
      number: 26,
      text: 'Tono de comunicacion preferido',
      why: 'Formal (usted) o casual (tu)? Profesional-cercano? Solo profesional?',
      inputType: 'select',
      required: true,
    },
    {
      number: 27,
      text: 'Contacto de escalacion para emergencias o quejas',
      why: 'Nombre, telefono y WhatsApp de quien resuelve situaciones criticas',
      inputType: 'text',
      required: true,
    },
    {
      number: 28,
      text: 'Edad minima de pacientes',
      why: 'Atienden ninos? Desde que edad? Tienen odontopediatra?',
      inputType: 'text',
      required: false,
    },
  ],

  // Sprint 2 stubs
  medico: [
    { number: 1, text: 'Nombre del consultorio y del medico titular', why: 'Dr./Dra. [nombre completo] — como quieres que el bot se refiera al doctor.', inputType: 'text', required: true },
    { number: 2, text: 'Especialidad(es) del medico', why: 'Medicina general, medicina interna, familiar, otra. Certificaciones vigentes.', inputType: 'text', required: true },
    { number: 3, text: 'Cedula profesional y cedula de especialidad', why: 'Los pacientes verifican en el registro DGP.', inputType: 'text', required: true },
    { number: 4, text: 'Direccion completa con referencias para llegar', why: 'Incluir piso/consultorio si es edificio medico.', inputType: 'text', required: true },
    { number: 5, text: 'Horario de consulta por dia', why: 'Manana, tarde, ambos. Horario exacto.', inputType: 'text', required: true },
    { number: 6, text: 'Duracion promedio de consulta', why: 'Primera vez vs. seguimiento. Tipicamente 30-45min primera, 20-30min seguimiento.', inputType: 'text', required: true },
    { number: 7, text: 'Precio de consulta — primera vez y seguimiento', why: 'Precio fijo o rango? Hay diferencia entre presencial y teleconsulta?', inputType: 'text', required: true, followUpInsight: 'El precio de consulta es la pregunta #1 que hacen los pacientes por WhatsApp. Tu bot la respondera al instante.' },
    { number: 8, text: 'Teleconsulta disponible?', why: 'Si/No. Por que plataforma (Zoom, Meet, WhatsApp video)? Mismo precio?', inputType: 'boolean', required: true },
    { number: 9, text: 'Servicios adicionales ofrecidos', why: 'Certificados medicos, check-up, vacunacion, curaciones, suturas, EKG, espirometria, etc. Con precios.', inputType: 'textarea', required: true },
    { number: 10, text: 'Padecimientos que NO atienden / refieren a especialista', why: 'Ej: pediatria, ginecologia, cirugia — para que el bot no agende algo que no atienden.', inputType: 'textarea', required: true },
    { number: 11, text: 'Laboratorios con los que trabajan o refieren', why: 'Nombre, ubicacion, si tienen convenio de descuento.', inputType: 'textarea', required: false },
    { number: 12, text: 'Farmacias cercanas o con convenio', why: 'Para que el bot pueda orientar al paciente despues de consulta.', inputType: 'text', required: false },
    { number: 13, text: 'Formas de pago', why: 'Efectivo, tarjeta, transferencia SPEI, MSI.', inputType: 'multiselect', required: true },
    { number: 14, text: 'Emiten factura CFDI?', why: 'Datos requeridos al paciente.', inputType: 'boolean', required: true },
    { number: 15, text: 'Aceptan seguros de gastos medicos mayores?', why: 'Cuales? GNP, AXA, MetLife, Seguros Monterrey, MAPFRE, etc.', inputType: 'text', required: false },
    { number: 16, text: 'Politica de cancelacion', why: 'Anticipacion requerida, penalizacion.', inputType: 'text', required: true },
    { number: 17, text: 'Manejan recetas electronicas?', why: 'Plataforma (Huli, iDoctor). Si no, receta fisica.', inputType: 'boolean', required: false },
    { number: 18, text: 'Atencion de urgencias?', why: 'Tienen horario extendido? Numero de urgencias?', inputType: 'boolean', required: true },
    { number: 19, text: 'Estacionamiento', why: 'Propio o cercano, costo.', inputType: 'text', required: false },
    { number: 20, text: 'Idiomas', why: 'Espanol, ingles, lengua indigena.', inputType: 'text', required: false },
    { number: 21, text: 'Tono del chatbot', why: 'Formal/profesional recomendado para medicos.', inputType: 'select', required: true },
    { number: 22, text: 'Contacto de escalacion', why: 'Numero del doctor o asistente para situaciones urgentes.', inputType: 'text', required: true },
  ],
  nutriologa: [
    { number: 1, text: 'Nombre de la nutriologa/nutriologo y consultorio', why: 'Lic. Nut. [nombre] — como aparece en cedula profesional', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional DGP', why: 'Verificable en registros publicos', inputType: 'text', required: true },
    { number: 3, text: 'Especialidades o enfoques', why: 'Nutricion clinica, deportiva, pediatrica, bariatrica, renal, oncologica, materno-infantil, vegetariana/vegana', inputType: 'text', required: true },
    { number: 4, text: 'Direccion y si atienden a domicilio o en linea', why: 'Consultorio fijo, a domicilio, teleconsulta, o combinacion', inputType: 'text', required: true },
    { number: 5, text: 'Horario de atencion por dia', why: 'Incluir si sabados o domingos', inputType: 'text', required: true },
    { number: 6, text: 'Precio de primera consulta vs. seguimiento', why: 'Primera consulta (tipicamente mas cara, incluye valoracion completa), seguimiento, plan alimentario', inputType: 'text', required: true, followUpInsight: 'El precio de la consulta de nutricion es la pregunta #1. Tu bot la respondera al instante.' },
    { number: 7, text: 'Que incluye cada tipo de consulta', why: 'Primera: historia clinica + antropometria + plan + educacion. Seguimiento: mediciones + ajuste plan', inputType: 'textarea', required: true },
    { number: 8, text: 'Paquetes o planes disponibles', why: 'Ej: Plan 3 meses (1 primera + 5 seguimientos) = $X. Plan mensual = $Y', inputType: 'textarea', required: false },
    { number: 9, text: 'Herramientas de medicion que usan', why: 'Bascula de bioimpedancia, plicometro, cinta, InBody. El paciente pregunta', inputType: 'text', required: false },
    { number: 10, text: 'Condiciones que atienden vs. refieren', why: 'Diabetes, hipertension, enfermedad renal, TCA — que atienden y que refieren a medico', inputType: 'textarea', required: true },
    { number: 11, text: 'Trastornos de conducta alimentaria — protocolo', why: 'Si detectan anorexia/bulimia, refieren a equipo multidisciplinario? A quien?', inputType: 'textarea', required: true },
    { number: 12, text: 'Trabajan con laboratorios?', why: 'Estudios de sangre que solicitan frecuentemente. Convenios', inputType: 'text', required: false },
    { number: 13, text: 'Entrega de plan alimentario — formato', why: 'PDF, app, impreso, WhatsApp. En cuanto tiempo despues de consulta', inputType: 'text', required: false },
    { number: 14, text: 'Formas de pago y facturacion', why: 'Efectivo, tarjeta, SPEI, MSI. CFDI disponible?', inputType: 'multiselect', required: true },
    { number: 15, text: 'Teleconsulta disponible?', why: 'Plataforma, precio, que necesita el paciente tener (bascula, cinta)', inputType: 'boolean', required: true },
    { number: 16, text: 'Politica de cancelacion', why: 'Anticipacion, penalizacion', inputType: 'text', required: true },
    { number: 17, text: 'Redes sociales', why: 'Instagram es clave para nutriologas — recetas, tips, testimoniales', inputType: 'text', required: false },
    { number: 18, text: 'Tono de comunicacion', why: 'Motivacional, empatico, sin juicio. Nunca critico con el peso', inputType: 'select', required: true },
    { number: 19, text: 'Contacto de escalacion', why: 'Para urgencias nutricionales o pacientes en crisis con TCA', inputType: 'text', required: true },
  ],
  psicologo: [
    { number: 1, text: 'Nombre del psicologo y consultorio', why: 'Lic./Mtro./Dr. [nombre] — titulo academico correcto', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional y cedula de especialidad', why: 'DGP verificable', inputType: 'text', required: true },
    { number: 3, text: 'Enfoque terapeutico', why: 'Cognitivo-conductual, psicodinamico, humanista, gestalt, sistemico, EMDR, infantil, de pareja, familiar', inputType: 'text', required: true },
    { number: 4, text: 'Poblacion que atiende', why: 'Adultos, adolescentes, ninos, parejas, familias. Rango de edad', inputType: 'text', required: true },
    { number: 5, text: 'Problematicas que atiende vs. refiere', why: 'Ansiedad, depresion, duelo, TCA, adicciones, TDAH, autismo, violencia — que atiende y que refiere a psiquiatra', inputType: 'textarea', required: true },
    { number: 6, text: 'Direccion del consultorio', why: 'O si es exclusivamente en linea', inputType: 'text', required: true },
    { number: 7, text: 'Horario de atencion por dia', why: 'Incluir si atiende fines de semana', inputType: 'text', required: true },
    { number: 8, text: 'Duracion de sesion', why: 'Tipicamente 50-60 minutos. Primera sesion diferente?', inputType: 'text', required: true },
    { number: 9, text: 'Precio por sesion — individual, pareja, familiar', why: 'Primera sesion vs. subsecuentes. Paquetes disponibles', inputType: 'text', required: true, followUpInsight: 'El precio de la terapia es lo primero que preguntan. Tu bot respondera con claridad y empatia.' },
    { number: 10, text: 'Paquetes de sesiones', why: 'Ej: 4 sesiones = $X, 8 sesiones = $Y', inputType: 'textarea', required: false },
    { number: 11, text: 'Modalidad — presencial, en linea, hibrida', why: 'Plataforma para teleconsulta. Requisitos de privacidad', inputType: 'text', required: true },
    { number: 12, text: 'Frecuencia recomendada de sesiones', why: 'Semanal, quincenal — para que el bot oriente', inputType: 'text', required: false },
    { number: 13, text: 'Formas de pago', why: 'Efectivo, tarjeta, SPEI. MSI? CFDI?', inputType: 'multiselect', required: true },
    { number: 14, text: 'Seguros que aceptan', why: 'GNP, AXA, MAPFRE, etc. que cubren psicologia', inputType: 'text', required: false },
    { number: 15, text: 'Confidencialidad — que decirle al paciente', why: 'Todo es confidencial excepto riesgo de danarse a si mismo o a otros', inputType: 'textarea', required: true },
    { number: 16, text: 'Politica de cancelacion', why: '24-48 horas de anticipacion tipicamente', inputType: 'text', required: true },
    { number: 17, text: 'Protocolo de crisis — ideacion suicida', why: 'Numero de emergencia, Linea de la Vida, protocolo interno', inputType: 'textarea', required: true },
    { number: 18, text: 'Idiomas', why: 'Espanol, ingles', inputType: 'text', required: false },
    { number: 19, text: 'Tono del chatbot', why: 'Empatico, calido, sin juicio. Nunca clinico/frio', inputType: 'select', required: true },
    { number: 20, text: 'Contacto de escalacion', why: 'Para crisis o pacientes en riesgo', inputType: 'text', required: true },
  ],
  dermatologo: [
    { number: 1, text: 'Nombre del dermatologo y consultorio', why: 'Dr./Dra. [nombre], Dermatologo certificado por Consejo Mexicano de Dermatologia', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional y de especialidad', why: 'DGP verificable', inputType: 'text', required: true },
    { number: 3, text: 'Subespecialidades', why: 'Dermatologia cosmetica, oncologica, pediatrica, cirugia dermatologica, tricologia', inputType: 'text', required: true },
    { number: 4, text: 'Direccion y horario', why: 'Por dia de la semana', inputType: 'text', required: true },
    { number: 5, text: 'Lista de consultas y procedimientos con precios', why: 'Consulta general, dermatoscopia, crioterapia, biopsia, electrocauterio, peelings, laser, toxina botulinica, rellenos, PRP, mesoterapia. PRECIO EXACTO', inputType: 'price_list', required: true },
    { number: 6, text: 'Procedimientos que requieren valoracion antes de cotizar', why: 'Laser, cirugia, tratamientos complejos', inputType: 'textarea', required: true },
    { number: 7, text: 'Equipos/tecnologia disponible', why: 'Dermatoscopio digital, laser CO2, IPL, radiofrecuencia — los pacientes preguntan', inputType: 'textarea', required: false },
    { number: 8, text: 'Marcas de productos que usan/recomiendan', why: 'La Roche-Posay, Avene, CeraVe, SkinCeuticals, etc. Venden productos en consultorio?', inputType: 'textarea', required: false },
    { number: 9, text: 'Condiciones que atienden vs. refieren', why: 'Acne, rosacea, dermatitis, psoriasis, vitiligo, verrugas, hongos, melanoma — que refieren a cirujano/oncologo', inputType: 'textarea', required: true },
    { number: 10, text: 'Fotos clinicas — consentimiento', why: 'Toman fotos antes/despues? Formato de consentimiento? LFPDPPP aplica como datos sensibles de salud', inputType: 'text', required: false },
    { number: 11, text: 'Formas de pago y MSI', why: 'Especialmente importante para procedimientos cosmeticos de alto costo', inputType: 'multiselect', required: true },
    { number: 12, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 13, text: 'Seguros que aceptan', why: 'Especificar si cubren dermatologia cosmetica (generalmente no)', inputType: 'text', required: false },
    { number: 14, text: 'Teleconsulta disponible?', why: 'Para seguimiento. Primera consulta casi siempre presencial', inputType: 'boolean', required: false },
    { number: 15, text: 'Politica de cancelacion', why: 'Anticipacion requerida', inputType: 'text', required: true },
    { number: 16, text: 'Tono del chatbot', why: 'Profesional pero cercano. Sensible con temas de apariencia', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'Para reacciones adversas o urgencias', inputType: 'text', required: true },
  ],
  ginecologo: [
    { number: 1, text: 'Nombre del ginecologo/a', why: 'Dr./Dra. [nombre], Ginecologia y Obstetricia', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional y de especialidad', why: 'Certificacion por Consejo Mexicano de Ginecologia y Obstetricia', inputType: 'text', required: true },
    { number: 3, text: 'Subespecialidades', why: 'Oncologia ginecologica, reproduccion asistida, uroginecologia, perinatologia, colposcopia', inputType: 'text', required: true },
    { number: 4, text: 'Consultorio y hospital donde atiende', why: 'Puede tener consultorio y operar en hospital diferente. Nombre de ambos', inputType: 'text', required: true },
    { number: 5, text: 'Horario de consulta', why: 'Por dia de la semana. Diferente para urgencias', inputType: 'text', required: true },
    { number: 6, text: 'Precio de consulta — primera vez y seguimiento', why: 'Incluye ultrasonido? Cual es el costo por separado?', inputType: 'text', required: true },
    { number: 7, text: 'Servicios disponibles en consultorio', why: 'Ultrasonido (abdominal, transvaginal), Papanicolaou, colposcopia, colocacion DIU, implante, monitoreo fetal. Con precios', inputType: 'textarea', required: true },
    { number: 8, text: 'Paquetes de control prenatal', why: 'Cuantas consultas, que estudios incluye, precio total', inputType: 'textarea', required: false },
    { number: 9, text: 'Paquete de parto/cesarea', why: 'Honorarios medicos, hospital, anestesiologo, pediatra. Precio desglosado o global', inputType: 'textarea', required: false },
    { number: 10, text: 'Hospitales con convenio', why: 'Nombre, ubicacion, telefono de admision', inputType: 'textarea', required: false },
    { number: 11, text: 'Atienden embarazo de alto riesgo?', why: 'O refieren a perinatologia?', inputType: 'boolean', required: true },
    { number: 12, text: 'Metodos anticonceptivos que colocan', why: 'DIU (cobre, Mirena), implante subdermico, pastillas, inyecciones. Precios', inputType: 'textarea', required: true },
    { number: 13, text: 'Estudios que solicitan frecuentemente', why: 'Papanicolaou, mastografia, perfil hormonal, cultivos. Laboratorios con convenio', inputType: 'textarea', required: false },
    { number: 14, text: 'Teleconsulta — para que tipo de consultas', why: 'Seguimiento, resultados, orientacion. NO para urgencias', inputType: 'boolean', required: false },
    { number: 15, text: 'Formas de pago', why: 'MSI es critico aqui — partos pueden costar $50,000-200,000+ MXN', inputType: 'multiselect', required: true },
    { number: 16, text: 'Seguros que aceptan', why: 'Especialmente para parto — cuales hospitales y seguros', inputType: 'text', required: false },
    { number: 17, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 18, text: 'Linea de urgencias obstetricas', why: 'Numero directo del doctor para trabajo de parto, sangrado, etc', inputType: 'text', required: true },
    { number: 19, text: 'Tono del chatbot', why: 'Empatico, profesional, sensible. Temas delicados (perdida gestacional, infertilidad)', inputType: 'select', required: true },
    { number: 20, text: 'Contacto de escalacion', why: 'Urgencias obstetricas — SIEMPRE escalar a humano', inputType: 'text', required: true },
  ],
  pediatra: [
    { number: 1, text: 'Nombre del pediatra', why: 'Dr./Dra. [nombre], Pediatra / Neonatologo / Pediatra Infectologo / etc', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional y de especialidad', why: 'Certificacion Consejo Mexicano de Pediatria', inputType: 'text', required: true },
    { number: 3, text: 'Rango de edad que atiende', why: 'Recien nacidos, lactantes, preescolares, escolares, adolescentes. Hasta que edad?', inputType: 'text', required: true },
    { number: 4, text: 'Consultorio y hospital donde atiende', why: 'Consultorio privado + hospital para urgencias', inputType: 'text', required: true },
    { number: 5, text: 'Horario de consulta por dia', why: 'Incluir disponibilidad sabados', inputType: 'text', required: true },
    { number: 6, text: 'Precio consulta — primera vez, seguimiento, urgencia', why: 'Desglosar cada tipo', inputType: 'text', required: true },
    { number: 7, text: 'Servicios en consultorio', why: 'Vacunacion, nebulizaciones, tamiz neonatal, desarrollo, circuncision. Precios', inputType: 'textarea', required: true },
    { number: 8, text: 'Esquema de vacunacion — cuales aplican y precios', why: 'Vacunas del cuadro basico vs. opcionales (rotavirus, varicela, hepatitis A, influenza). Precios individuales', inputType: 'textarea', required: true },
    { number: 9, text: 'Control del nino sano — que incluye y frecuencia', why: 'Periodicidad recomendada, que evaluan en cada visita', inputType: 'textarea', required: false },
    { number: 10, text: 'Urgencias pediatricas — protocolo', why: 'Numero directo, horario, si atienden en hospital', inputType: 'text', required: true },
    { number: 11, text: 'Estudios que solicitan frecuentemente', why: 'BH, EGO, coprologico. Laboratorios con convenio', inputType: 'text', required: false },
    { number: 12, text: 'Teleconsulta disponible?', why: 'Para que tipo de consultas. Que NO atienden por video', inputType: 'boolean', required: false },
    { number: 13, text: 'Formas de pago', why: 'Incluyendo MSI para paquetes de vacunacion', inputType: 'multiselect', required: true },
    { number: 14, text: 'Seguros aceptados', why: 'Cuales y para que tipo de consulta', inputType: 'text', required: false },
    { number: 15, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 16, text: 'Tono del chatbot', why: 'Calido, cercano, orientado a papas primerizos. Nunca alarmista', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'CRITICO — urgencias pediatricas deben llegar al doctor en minutos', inputType: 'text', required: true },
  ],
  oftalmologo: [
    { number: 1, text: 'Nombre del oftalmologo y clinica', why: 'Dr./Dra. [nombre], Oftalmologo', inputType: 'text', required: true },
    { number: 2, text: 'Cedula profesional y de especialidad', why: 'Consejo Mexicano de Oftalmologia', inputType: 'text', required: true },
    { number: 3, text: 'Subespecialidades', why: 'Retina, glaucoma, cornea, oculoplastica, pediatrica, neuro-oftalmologia', inputType: 'text', required: true },
    { number: 4, text: 'Consultorio y/o clinica', why: 'Si tienen quirofano propio o refieren a hospital', inputType: 'text', required: true },
    { number: 5, text: 'Horario de atencion', why: 'Por dia de la semana', inputType: 'text', required: true },
    { number: 6, text: 'Precio de consulta — primera vez y seguimiento', why: 'Desglosado', inputType: 'text', required: true },
    { number: 7, text: 'Estudios disponibles en consultorio', why: 'Agudeza visual, tonometria, fondo de ojo, campimetria, OCT, topografia corneal, paquimetria. Precios', inputType: 'textarea', required: true },
    { number: 8, text: 'Cirugias que realizan', why: 'Catarata (facoemulsificacion), LASIK/PRK, pterigion, chalazion, inyecciones intravitreas. Precios o rango', inputType: 'textarea', required: true },
    { number: 9, text: 'Optica integrada?', why: 'Venden lentes, armazones, lentes de contacto? Marcas y rango de precios', inputType: 'text', required: false },
    { number: 10, text: 'Graduacion incluida en consulta?', why: 'O tiene costo adicional?', inputType: 'boolean', required: true },
    { number: 11, text: 'Formas de pago', why: 'MSI es critico para cirugias ($15,000-60,000+ MXN)', inputType: 'multiselect', required: true },
    { number: 12, text: 'Seguros aceptados', why: 'Cuales y para que procedimientos', inputType: 'text', required: false },
    { number: 13, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 14, text: 'Urgencias oftalmologicas', why: 'Atienden? Numero directo? Traumatismo ocular, cuerpo extrano, perdida subita de vision', inputType: 'text', required: true },
    { number: 15, text: 'Tono del chatbot', why: 'Profesional, claro. Muchos pacientes adultos mayores — lenguaje simple', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Para urgencias y cirugias', inputType: 'text', required: true },
  ],
  farmacia: [
    { number: 1, text: 'Nombre de la farmacia', why: 'Como aparece en letrero y RFC', inputType: 'text', required: true },
    { number: 2, text: 'Direccion completa', why: 'Con referencias', inputType: 'text', required: true },
    { number: 3, text: 'Horario de atencion', why: 'Muchas farmacias son 24 horas o hasta las 22:00', inputType: 'text', required: true },
    { number: 4, text: 'Licencia sanitaria COFEPRIS', why: 'Obligatoria para operar', inputType: 'text', required: false },
    { number: 5, text: 'Tipo de farmacia', why: 'Independiente, franquicia (Farmacias del Ahorro, Guadalajara, Benavides), generico', inputType: 'text', required: true },
    { number: 6, text: 'Servicios adicionales', why: 'Inyecciones, toma de presion, glucometria, pruebas rapidas (COVID, embarazo), servicio a domicilio', inputType: 'textarea', required: true },
    { number: 7, text: 'Venta de medicamentos controlados?', why: 'Receta medica retenida obligatoria. Cuales manejan', inputType: 'boolean', required: true },
    { number: 8, text: 'Servicio a domicilio', why: 'Zona de cobertura, costo, horario, tiempo de entrega', inputType: 'text', required: false },
    { number: 9, text: 'Formas de pago', why: 'Efectivo, tarjeta, vales de despensa', inputType: 'multiselect', required: true },
    { number: 10, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 11, text: 'Programa de lealtad', why: 'Puntos, descuentos frecuentes', inputType: 'text', required: false },
    { number: 12, text: 'Tono del chatbot', why: 'Servicial, rapido. Enfocado en disponibilidad y precios', inputType: 'select', required: true },
    { number: 13, text: 'Contacto de escalacion', why: 'Farmaceutico para consultas tecnicas', inputType: 'text', required: true },
  ],
  veterinaria: [
    { number: 1, text: 'Nombre de la clinica veterinaria', why: 'Como aparece en letrero/RFC', inputType: 'text', required: true },
    { number: 2, text: 'Nombre del medico veterinario titular', why: 'MVZ [nombre completo]', inputType: 'text', required: true },
    { number: 3, text: 'Cedula profesional', why: 'CPMVZ verificable', inputType: 'text', required: true },
    { number: 4, text: 'Especialidades', why: 'Medicina general, cirugia, ortopedia, dermatologia, cardiologia, oftalmologia, exoticos', inputType: 'text', required: true },
    { number: 5, text: 'Especies que atienden', why: 'Perros, gatos, aves, reptiles, roedores, conejos, exoticos', inputType: 'multiselect', required: true },
    { number: 6, text: 'Direccion y horario', why: 'Por dia. Horario de urgencias diferente?', inputType: 'text', required: true },
    { number: 7, text: 'Precio de consulta por especie', why: 'Perro/gato vs. exotico. Primera vez vs. seguimiento', inputType: 'text', required: true },
    { number: 8, text: 'Servicios disponibles', why: 'Vacunacion, desparasitacion, esterilizacion, cirugia, rayos X, ultrasonido, laboratorio, dental, estetica (bano, corte), hospedaje, guarderia. PRECIOS de cada uno', inputType: 'price_list', required: true },
    { number: 9, text: 'Esquema de vacunacion canino y felino con precios', why: 'Puppy/kitten, refuerzos anuales, antirrabica. Precio individual', inputType: 'textarea', required: true },
    { number: 10, text: 'Cirugias que realizan', why: 'Esterilizacion, tumores, ortopedia, cesarea, urgencias. Precios o rango', inputType: 'textarea', required: true },
    { number: 11, text: 'Paquetes de prevencion', why: 'Control anual, paquete cachorro, paquete senior. Que incluye y precio', inputType: 'textarea', required: false },
    { number: 12, text: 'Servicio de urgencias 24/7?', why: 'Si/No. Numero directo. Costo de urgencia', inputType: 'boolean', required: true },
    { number: 13, text: 'Servicio de estetica/bano', why: 'Precios por tamano (chico, mediano, grande, gigante). Incluye que', inputType: 'textarea', required: false },
    { number: 14, text: 'Hospedaje/pension', why: 'Precio por noche/dia. Que incluye. Requisitos (vacunas al dia)', inputType: 'text', required: false },
    { number: 15, text: 'Tienda de mascotas integrada?', why: 'Alimento, accesorios, marcas que manejan', inputType: 'boolean', required: false },
    { number: 16, text: 'Formas de pago', why: 'Efectivo, tarjeta, SPEI, MSI para cirugias', inputType: 'multiselect', required: true },
    { number: 17, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: false },
    { number: 18, text: 'Servicio a domicilio veterinario?', why: 'Vacunacion, eutanasia humanitaria, consulta. Costo', inputType: 'text', required: false },
    { number: 19, text: 'Tono del chatbot', why: 'Calido, empatico. Los duenos consideran mascotas como familia', inputType: 'select', required: true },
    { number: 20, text: 'Contacto de escalacion', why: 'CRITICO para urgencias — mordeduras, atropellos, envenenamientos', inputType: 'text', required: true },
  ],
};
