import type { VerticalEnum, VerticalQuestion } from '../types';

export const saludQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  dental: [
    {
      number: 1,
      text: 'Nombre completo del consultorio o clinica',
      why: 'Exactamente como aparece en tu letrero y RFC',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion completa con referencias',
      why: 'Calle, numero, colonia, CP, ciudad, estado + como llegar',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario de atencion por dia de la semana',
      why: 'Lunes a viernes, sabado, domingo. Incluye si cierras a medio dia',
      inputType: 'text',
      required: true,
      followUpInsight:
        'Con horario de L-V 9-19, el chatbot capturara las consultas de las 19:01 en adelante — que es cuando la gente busca dentista despues del trabajo.',
    },
    {
      number: 4,
      text: 'Dias festivos o periodos de vacaciones',
      why: 'Semana Santa, Navidad, puentes — cuando cierras',
      inputType: 'text',
      required: false,
    },
    {
      number: 5,
      text: 'Nombre del dentista titular y especialidad',
      why: 'Dr./Dra. [nombre], Cirujano Dentista / Ortodoncista / etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 6,
      text: 'Cedula profesional y universidad',
      why: 'Numero de cedula DGP — los pacientes lo preguntan para verificar',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Otros dentistas o especialistas en el consultorio',
      why: 'Nombre, especialidad y dias que atienden cada uno',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Lista COMPLETA de tratamientos con precios',
      why: 'Limpieza, resinas, endodoncia, corona, puente, implante, ortodoncia, blanqueamiento, extraccion, radiografia, guardas, etc. PRECIO EXACTO',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'Los precios son la pregunta #1 que hacen los pacientes por WhatsApp. Con esta lista, tu bot respondera al instante.',
    },
    {
      number: 9,
      text: 'Tratamientos que requieren valoracion previa antes de dar precio',
      why: 'Ej: implantes, ortodoncia, protesis — donde el precio depende del caso',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Duracion aproximada de cada tratamiento',
      why: 'Limpieza 40min, endodoncia 60-90min, etc',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Politica de primera cita / valoracion',
      why: 'Tiene costo? Cuanto? Es gratis? Incluye radiografia?',
      inputType: 'text',
      required: true,
    },
    {
      number: 12,
      text: 'Tipos de radiografia disponibles',
      why: 'Periapical, panoramica, cefalometrica. Costo de cada una',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 13,
      text: 'Marcas de materiales que usan',
      why: 'Importante para pacientes con alergias — ej: composites libres de BPA',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 14,
      text: 'Formas de pago aceptadas',
      why: 'Efectivo, tarjeta debito, credito, transferencia SPEI, Mercado Pago, MSI',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        'El 40% de los pacientes preguntan por MSI antes de agendar tratamientos grandes como implantes u ortodoncia.',
    },
    {
      number: 15,
      text: 'Emiten factura CFDI?',
      why: 'Si si, que datos necesitan del paciente (RFC, regimen, uso CFDI, CP)',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 16,
      text: 'Politica de cancelacion y no-show',
      why: 'Con cuanta anticipacion? Cobran penalizacion? Cuanto?',
      inputType: 'text',
      required: true,
    },
    {
      number: 17,
      text: 'Manejan urgencias dentales?',
      why: 'Dolor agudo, diente roto, absceso. Tienen horario de urgencias? Numero directo?',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 18,
      text: 'Esterilizacion y protocolos de higiene',
      why: 'Autoclave, desechables, protocolos COVID remanentes',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 19,
      text: 'Estacionamiento disponible?',
      why: 'Propio, calle, estacionamiento publico cercano. Costo',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Planes de financiamiento o pagos diferidos propios',
      why: 'Aparte de MSI bancarios, ofrecen pagos a meses directos?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 21,
      text: 'Seguro dental — aceptan alguno?',
      why: 'MetLife, GNP Dental, Dentegra, Plan Seguro, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 22,
      text: 'Consentimiento informado — formato digital o papel?',
      why: 'Obligatorio por NOM-013-SSA2-2015',
      inputType: 'text',
      required: false,
    },
    {
      number: 23,
      text: 'Programa de lealtad o referidos',
      why: 'Descuento por referir? Programa de puntos? Descuento familiar?',
      inputType: 'text',
      required: false,
    },
    {
      number: 24,
      text: 'Idiomas que hablan',
      why: 'Espanol, ingles, otro — importante en zonas turisticas',
      inputType: 'text',
      required: false,
    },
    {
      number: 25,
      text: 'Redes sociales y Google Maps link',
      why: 'Instagram, Facebook, Google Business Profile',
      inputType: 'text',
      required: false,
    },
    {
      number: 26,
      text: 'Tono de comunicacion preferido',
      why: 'Formal (usted) o casual (tu)? Profesional-cercano? Solo profesional?',
      inputType: 'select',
      required: true,
    },
    {
      number: 27,
      text: 'Contacto de escalacion para emergencias o quejas',
      why: 'Nombre, telefono y WhatsApp de quien resuelve situaciones criticas',
      inputType: 'text',
      required: true,
    },
    {
      number: 28,
      text: 'Edad minima de pacientes',
      why: 'Atienden ninos? Desde que edad? Tienen odontopediatra?',
      inputType: 'text',
      required: false,
    },
  ],

  // Sprint 2 stubs
  medico: [],
  nutriologa: [],
  psicologo: [],
  dermatologo: [],
  ginecologo: [],
  pediatra: [],
  oftalmologo: [],
  farmacia: [],
  veterinaria: [],
};
