import type { VerticalEnum, VerticalQuestion } from '../types';

export const serviciosQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  // 6 verticales / 109 preguntas — Source: PDF pages 114-131
  contable_legal: [
    { number: 1, text: 'Nombre del despacho contable/legal', why: 'Razon social completa', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'L-V tipico. Sabados?', inputType: 'text', required: true },
    { number: 3, text: 'Servicios ofrecidos', why: 'Contabilidad general, fiscal (declaraciones mensuales/anuales), nomina, auditoria, asesoria legal, laboral, corporativo, IMSS/INFONAVIT, constitucion de sociedades, propiedad intelectual', inputType: 'textarea', required: true },
    { number: 4, text: 'Regimenes fiscales que atienden', why: 'RESICO, General de Ley, Asalariados, Personas Morales, AC, SC. Cuales dominan', inputType: 'textarea', required: true },
    { number: 5, text: 'Tipo de clientes', why: 'Personas fisicas, morales, startups, PyMEs, corporativos, freelancers. Industrias principales', inputType: 'textarea', required: true },
    { number: 6, text: 'Numero aproximado de clientes activos', why: 'Para dimensionar capacidad', inputType: 'number', required: true },
    { number: 7, text: 'Modelo de cobro', why: 'Mensualidad fija por contabilidad ($X/mes por cliente), por servicio (declaracion anual $X), por hora (consultoria legal $X/hr). PRECIOS EXACTOS o rangos', inputType: 'price_list', required: true, followUpInsight: 'Los clientes preguntan precio antes que nada. Tu bot dara respuestas exactas en segundos.' },
    { number: 8, text: 'Paquetes de servicios', why: "Ej: 'Paquete PyME: contabilidad + nomina + declaraciones = $X/mes'. Desglosar cada paquete", inputType: 'textarea', required: false },
    { number: 9, text: 'Software que usan', why: 'CONTPAQi, Aspel, Bind, otro. Version', inputType: 'text', required: true },
    { number: 10, text: 'Declaraciones que presentan', why: 'ISR provisional, ISR anual, IVA mensual, DIOT, informativas, nominas. Fechas limite', inputType: 'textarea', required: true },
    { number: 11, text: 'Atencion de carta invitacion/auditoria SAT', why: 'Experiencia? Proceso? Costo?', inputType: 'textarea', required: true },
    { number: 12, text: 'Firma electronica y CSD', why: 'Tramitan? Renuevan? Costo?', inputType: 'text', required: false },
    { number: 13, text: 'Facturacion CFDI del despacho', why: 'Para sus propios servicios', inputType: 'text', required: true },
    { number: 14, text: 'Formas de pago que aceptan', why: 'Transferencia SPEI (predominante), tarjeta, efectivo', inputType: 'text', required: true },
    { number: 15, text: 'Horario de atencion y canales', why: 'WhatsApp es critico — clientes envian documentos por WhatsApp', inputType: 'text', required: true },
    { number: 16, text: 'Tono del chatbot', why: 'Profesional, confiable, tranquilizador. Los clientes llegan con estres fiscal', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'Socio/contador principal para auditorias o temas legales complejos', inputType: 'text', required: true },
  ],
  seguros: [
    { number: 1, text: 'Nombre de la agencia/agente', why: 'Persona fisica con actividad empresarial o agencia', inputType: 'text', required: true },
    { number: 2, text: 'Cedula CNSF', why: 'Numero de agente autorizado', inputType: 'text', required: true },
    { number: 3, text: 'Tipo de agente', why: 'Persona fisica, apoderado, promotoria, corredor', inputType: 'select', required: true },
    { number: 4, text: 'Aseguradoras que representan', why: 'Lista completa: Qualitas, GNP, AXA, Chubb, HDI, Mapfre, Zurich, Atlas, Banorte Seguros, MetLife, etc', inputType: 'multiselect', required: true },
    { number: 5, text: 'Lineas de seguro que venden', why: 'Auto (la principal en Mexico), vida, gastos medicos mayores (GMM), hogar, empresarial, responsabilidad civil, fianzas, viaje. RANKEAR por volumen de ventas', inputType: 'multiselect', required: true },
    { number: 6, text: 'Productos estrella', why: 'Los que mas venden. Para enfoque del chatbot', inputType: 'textarea', required: true, followUpInsight: 'Tu bot enfocara la conversacion en lo que mas vendes — mas conversiones.' },
    { number: 7, text: 'Numero aproximado de polizas activas', why: 'Para dimensionar', inputType: 'number', required: true },
    { number: 8, text: 'Proceso de cotizacion', why: 'Multicotizador que usan? Datos que necesitan del cliente para cotizar (auto: marca, modelo, ano, CP, edad conductor, uso)', inputType: 'textarea', required: true },
    { number: 9, text: 'Proceso de contratacion', why: 'Online? Presencial? Documentos requeridos', inputType: 'textarea', required: true },
    { number: 10, text: 'Proceso de siniestro — por linea', why: 'Auto: que datos pedir, numeros de emergencia de cada aseguradora. GMM: proceso de admision hospitalaria', inputType: 'textarea', required: true },
    { number: 11, text: 'Numeros de emergencia de aseguradoras', why: 'HDI: 800-667-3144, Chubb: 800-223-2001, Qualitas: 800-800-2000, GNP: 55-5227-3999. LISTA COMPLETA', inputType: 'textarea', required: true },
    { number: 12, text: 'Formas de pago de primas', why: 'Anual, semestral, trimestral, mensual. Tarjeta, SPEI, domiciliacion', inputType: 'text', required: true },
    { number: 13, text: 'Facturacion CFDI', why: 'Del agente para su comision. De la aseguradora para la prima', inputType: 'text', required: true },
    { number: 14, text: 'Horario de atencion', why: 'Para consultas normales vs. siniestros (24/7 via aseguradoras)', inputType: 'text', required: true },
    { number: 15, text: 'Tono del chatbot', why: "Confiable, protector, empatico. 'Estamos para protegerte.'", inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Agente titular para siniestros complejos o reclamaciones', inputType: 'text', required: true },
  ],
  taller_mecanico: [
    { number: 1, text: 'Nombre del taller', why: 'Como aparece en fachada y RFC', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'L-V, sabados medio dia es tipico', inputType: 'text', required: true },
    { number: 3, text: 'Especialidades del taller', why: 'Mecanica general, frenos, suspension, electrico, motor, transmision, hojalateria y pintura, A/C, alineacion y balanceo, diagnostico computarizado, inyeccion, clutch, escape', inputType: 'multiselect', required: true },
    { number: 4, text: 'Marcas/tipos de vehiculo que atienden', why: 'Todas? Solo una marca (agencia)? Americanos, japoneses, europeos? Diesel? Motos? Camiones?', inputType: 'textarea', required: true },
    { number: 5, text: 'Numero de bahias/rampas', why: 'Para calcular capacidad', inputType: 'number', required: true },
    { number: 6, text: 'Mecanicos — cuantos y especialidades', why: 'Cada mecanico puede tener diferente especialidad', inputType: 'textarea', required: true },
    { number: 7, text: 'Servicios con precios fijos', why: 'Cambio de aceite ($X-Y segun tipo), afinacion menor/mayor ($X), frenos (pastillas + mano obra $X), alineacion y balanceo ($X). PRECIOS EXACTOS o rangos', inputType: 'price_list', required: true, followUpInsight: 'PROFECO sanciono 197 de 409 talleres por precios opacos. Tu bot dara presupuestos transparentes.' },
    { number: 8, text: 'Servicios que requieren diagnostico antes de cotizar', why: 'Motor, transmision, electrico, pintura, hojalateria', inputType: 'textarea', required: true },
    { number: 9, text: 'Tipo de refacciones', why: 'Originales, genericas, reconstruidas. Politica del taller', inputType: 'text', required: true },
    { number: 10, text: 'Garantia en mano de obra y refacciones', why: 'PROFECO establece minimo 90 dias. Cual es su politica?', inputType: 'text', required: true },
    { number: 11, text: 'Presupuesto por escrito — proceso', why: 'PROFECO lo exige ANTES de reparar. Formato? Digital o papel?', inputType: 'text', required: true },
    { number: 12, text: 'Diagnostico con escaner', why: 'Disponible? Marcas de scanner (Launch, Autel). Costo: $600-800 MXN tipico', inputType: 'text', required: false },
    { number: 13, text: 'Servicio de grua', why: 'Propio o convenio? Costo? Zona de cobertura', inputType: 'text', required: false },
    { number: 14, text: 'Trabajan con aseguradoras?', why: 'Cuales? Son taller autorizado de alguna?', inputType: 'textarea', required: false },
    { number: 15, text: 'Atienden flotillas/empresas?', why: 'Cuentas corporativas? Credito? Facturacion', inputType: 'text', required: false },
    { number: 16, text: 'Formas de pago', why: 'Efectivo, tarjeta, SPEI, MSI para reparaciones grandes', inputType: 'text', required: true },
    { number: 17, text: 'Facturacion CFDI', why: 'Disponible? Regimen fiscal del taller', inputType: 'text', required: true },
    { number: 18, text: 'Tono del chatbot', why: 'Directo, honesto, tecnico pero entendible. Confianza es TODO en un taller', inputType: 'select', required: true },
    { number: 19, text: 'Contacto de escalacion', why: 'Mecanico jefe o dueno para diagnosticos complejos', inputType: 'text', required: true },
  ],
  escuela: [
    { number: 1, text: 'Nombre de la institucion', why: 'Nombre oficial completo', inputType: 'text', required: true },
    { number: 2, text: 'CCT (Clave de Centro de Trabajo)', why: 'Identificador SEP unico', inputType: 'text', required: true },
    { number: 3, text: 'Niveles que ofrece', why: 'Preescolar, primaria, secundaria, preparatoria, universidad', inputType: 'multiselect', required: true },
    { number: 4, text: 'RVOE / Incorporacion a la SEP', why: 'Numero RVOE por cada programa. Sin RVOE los estudios no tienen validez oficial. NUNCA inventar este numero', inputType: 'textarea', required: true },
    { number: 5, text: 'Direccion(es) y horario', why: 'Por nivel si tienen campus separados', inputType: 'textarea', required: true },
    { number: 6, text: 'Cuotas COMPLETAS por nivel', why: 'Inscripcion, reinscripcion, colegiatura mensual, seguro escolar, material didactico, plataformas digitales. PRECIO EXACTO de cada concepto por nivel', inputType: 'price_list', required: true, followUpInsight: 'PROFECO sanciona escuelas que esconden cuotas. Tu bot sera 100% transparente.' },
    { number: 7, text: 'Calendario de pagos', why: 'Fechas limite de pago. Recargo por morosidad (monto y a partir de que dia)', inputType: 'textarea', required: true },
    { number: 8, text: 'Descuento por pronto pago', why: 'Porcentaje, deadline, condiciones', inputType: 'text', required: false },
    { number: 9, text: 'Becas disponibles', why: 'Tipos (academica, deportiva, hermanos, necesidad). Porcentaje de descuento. Requisitos', inputType: 'textarea', required: false },
    { number: 10, text: 'Formas de pago de colegiaturas', why: 'Domiciliacion bancaria, SPEI, tarjeta, OXXO, Kueski Pay, ventanilla. Link de pago en linea?', inputType: 'text', required: true },
    { number: 11, text: 'Periodos de inscripcion', why: 'Fechas exactas. Documentos requeridos (CURP, acta nacimiento, boleta anterior, carta buena conducta, fotos, examen medico)', inputType: 'textarea', required: true },
    { number: 12, text: 'Calendario escolar', why: '190-200 dias de clase. Vacaciones (Semana Santa, julio-agosto, Navidad). Puentes. Dias de consejo tecnico', inputType: 'textarea', required: true },
    { number: 13, text: 'Actividades extracurriculares', why: 'Deportes, artes, idiomas, robotica, musica. Dias, horario, costo adicional', inputType: 'textarea', required: false },
    { number: 14, text: 'Transporte escolar', why: 'Disponible? Rutas? Costo? Proveedor', inputType: 'text', required: false },
    { number: 15, text: 'Uniforme — donde adquirirlo', why: 'PROFECO: NO pueden obligar a comprar en proveedor unico. Especificaciones y donde conseguirlo', inputType: 'textarea', required: true },
    { number: 16, text: 'Lista de utiles', why: 'La proporcionan? Cuando? Por grado', inputType: 'text', required: true },
    { number: 17, text: 'Plataforma de comunicacion con padres', why: 'App, web, WhatsApp, correo. Para calificaciones, avisos, comunicados', inputType: 'text', required: true },
    { number: 18, text: 'Politica de faltas/retardos', why: 'Limite de faltas, justificacion, consecuencias', inputType: 'textarea', required: true },
    { number: 19, text: 'Facturacion CFDI', why: 'De colegiaturas. Uso CFDI = D10 (Pagos por servicios educativos)', inputType: 'text', required: true },
    { number: 20, text: 'Tono del chatbot', why: 'Institucional pero calido. Padres confian a sus hijos — el tono debe transmitir seguridad', inputType: 'select', required: true },
    { number: 21, text: 'Contacto de escalacion', why: 'Direccion academica, coordinacion de nivel, administracion', inputType: 'text', required: true },
  ],
  agencia_digital: [
    { number: 1, text: 'Nombre de la agencia', why: 'Marca comercial', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Muchas agencias son remote-first', inputType: 'text', required: true },
    { number: 3, text: 'Servicios que ofrecen', why: 'SEO, SEM (Google Ads, Meta Ads), social media management, web development, branding, content marketing, email marketing, inbound, e-commerce, PR digital. Rankear por ingreso', inputType: 'multiselect', required: true },
    { number: 4, text: 'Paquetes y precios', why: 'Ej: Paquete Social Media $8,000-15,000/mes (X posts, X stories, community management). Paquete 360 $25,000-100,000/mes. Sitio web $15,000-150,000 proyecto. DETALLAR cada paquete', inputType: 'price_list', required: true, followUpInsight: 'Los leads filtran por precio en el primer mensaje. Tu bot calificara mejor las oportunidades.' },
    { number: 5, text: 'Compromiso minimo', why: '3, 6, 12 meses? Clausula de cancelacion anticipada?', inputType: 'text', required: true },
    { number: 6, text: 'Tamano del equipo y roles', why: 'Disenadores, developers, copywriters, media buyers, strategists, account managers', inputType: 'textarea', required: true },
    { number: 7, text: 'Clientes actuales — cuantos y de que industrias', why: 'Para dimensionar capacidad', inputType: 'textarea', required: true },
    { number: 8, text: 'Proceso de venta', why: 'Como llegan los leads? Llamada discovery? Propuesta? Timeline?', inputType: 'textarea', required: true },
    { number: 9, text: 'Reportes — frecuencia y formato', why: 'Mensual, quincenal, semanal. Que metricas incluyen (clicks, CTR, ROAS, leads, conversiones)', inputType: 'textarea', required: true },
    { number: 10, text: 'Herramientas que usan', why: "Para que el bot pueda responder 'con que plataformas trabajan'", inputType: 'multiselect', required: true },
    { number: 11, text: 'Quien es dueno de las cuentas de ads?', why: 'SIEMPRE el cliente. Aclarar esto es diferenciador', inputType: 'text', required: true },
    { number: 12, text: 'Manejo de crisis en redes sociales', why: 'Protocolo. Tiempo de respuesta', inputType: 'textarea', required: false },
    { number: 13, text: 'Facturacion CFDI', why: 'Mensual. IVA 16% incluido. Formas de pago aceptadas', inputType: 'text', required: true },
    { number: 14, text: 'Tono del chatbot', why: "Creativo, experto, moderno. 'Hacemos que tu marca destaque.'", inputType: 'select', required: true },
    { number: 15, text: 'Contacto de escalacion', why: 'Director de cuentas o CEO', inputType: 'text', required: true },
  ],
  fotografo: [
    { number: 1, text: 'Nombre del fotografo/estudio', why: 'Marca personal o estudio', inputType: 'text', required: true },
    { number: 2, text: 'Ubicacion base y area de servicio', why: 'Ciudad base. Viajan? A donde? Costo de viaticos?', inputType: 'textarea', required: true },
    { number: 3, text: 'Especialidad', why: 'Bodas, quinceaneras, bautizos, retratos familiares, maternidad/newborn, producto, eventos corporativos, inmobiliaria, gastronomia. RANKEAR', inputType: 'multiselect', required: true },
    { number: 4, text: 'Paquetes por tipo de sesion con precios', why: 'BODA: Paquete basico (6h, 1 fotografo, X fotos editadas, galeria online = $30,000-50,000), Paquete premium (10h, 2 fotografos, album, drone = $50,000-80,000+). RETRATO: Sesion 1h, X fotos editadas = $2,500-5,000. PRODUCTO: por foto o por hora. DETALLAR CADA UNO', inputType: 'price_list', required: true, followUpInsight: 'El 80% de los leads abandonan por no recibir cotizacion rapida. Tu bot respondera al instante.' },
    { number: 5, text: 'Que incluye cada paquete', why: 'Horas de cobertura, numero de fotos editadas, segundo fotografo, drone, album, prints, galeria online. Que es extra y su costo', inputType: 'textarea', required: true },
    { number: 6, text: 'Estilo fotografico', why: 'Candid/documental, editorial, fine art, clasico/posado. El cliente NECESITA saber esto', inputType: 'select', required: true },
    { number: 7, text: 'Tiempo de entrega de galerias', why: 'Sesiones: 1-5 dias habiles. Bodas: 2-4 semanas. Establecer expectativa clara', inputType: 'text', required: true },
    { number: 8, text: 'Formato de entrega', why: 'Galeria online (Pixieset, ShootProof, Pic-Time), USB, WeTransfer, Google Drive. Resolucion (web + alta)', inputType: 'text', required: true },
    { number: 9, text: 'Politica de anticipo', why: 'Porcentaje (30-50% tipico). Reembolsable? En que condiciones?', inputType: 'text', required: true },
    { number: 10, text: 'Politica de cancelacion/reprogramacion', why: 'Anticipacion requerida. Penalizacion. Fuerza mayor', inputType: 'textarea', required: true },
    { number: 11, text: 'Disponibilidad — como funciona', why: 'Calendario. Cuantas sesiones/bodas toman por fin de semana?', inputType: 'textarea', required: true },
    { number: 12, text: 'Pico de temporada', why: 'Bodas: marzo-junio, septiembre-noviembre. XV: todo el ano con picos', inputType: 'text', required: false },
    { number: 13, text: 'Equipo', why: 'Solo o con equipo (segundo fotografo, asistente, videografo). Disponibilidad', inputType: 'text', required: true },
    { number: 14, text: 'Video tambien?', why: 'Ofrecen video ademas de foto? Paquetes combinados?', inputType: 'text', required: false },
    { number: 15, text: 'Impresiones/albumes', why: 'Ofrecen? Proveedores? Precios? Tiempo de produccion', inputType: 'textarea', required: false },
    { number: 16, text: 'Contrato — manejan?', why: 'Digital o fisico? Que clausulas (propiedad intelectual, uso de imagen, cancelacion)', inputType: 'text', required: true },
    { number: 17, text: 'Formas de pago', why: 'SPEI, tarjeta, efectivo. MSI (3 meses comun para bodas). Pago completo antes de entrega', inputType: 'text', required: true },
    { number: 18, text: 'Facturacion CFDI', why: 'Regimen fiscal. NOTA: Art. 93 Fr. XXIX LISR: ingreso por derechos de autor (obras fotograficas) exento hasta ~$792,561 MXN/ano', inputType: 'text', required: true },
    { number: 19, text: 'Redes sociales / portfolio', why: 'Instagram (CRITICO), website, Behance. Link directo a portfolio', inputType: 'text', required: true },
    { number: 20, text: 'Tono del chatbot', why: "Artistico, cercano, apasionado. 'Vamos a crear recuerdos que duren para siempre.'", inputType: 'select', required: true },
    { number: 21, text: 'Contacto de escalacion', why: 'Fotografo directamente para cotizaciones personalizadas y bodas', inputType: 'text', required: true },
  ],
};
