import type { VerticalEnum, VerticalQuestion } from '../types';

export const serviciosQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  contable_legal: [
    { number: 1, text: 'Nombre del despacho y titular(es)', why: 'Razon social y nombre comercial. Lic./CP/Mtro. de los socios.', inputType: 'text', required: true },
    { number: 2, text: 'Cedulas profesionales', why: 'CP y/o abogado. DGP verificable. Es la base de credibilidad.', inputType: 'text', required: true },
    { number: 3, text: 'Tipos de servicio que ofrecen', why: 'Contabilidad general, fiscal, nominas, auditoria, defensa fiscal, mercantil, civil, laboral, corporativo.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Tipo de cliente que atienden', why: 'Persona fisica con/sin actividad, RESICO, RIF, PM, extranjeros con ingresos en MX.', inputType: 'multiselect', required: true },
    { number: 5, text: 'Honorarios — iguala mensual contable', why: 'Por rango de movimientos/empleados. Cuanto incluye (declaraciones, conciliaciones, asesoria).', inputType: 'price_list', required: true, followUpInsight: 'El precio de la iguala es la pregunta #1 que llega por WhatsApp. Tu bot la responde al instante con el rango correcto.' },
    { number: 6, text: 'Servicios por evento — precios', why: 'Alta SAT, declaracion anual PF, declaracion anual PM, devolucion de saldo a favor, regularizacion, opinion de cumplimiento.', inputType: 'price_list', required: true },
    { number: 7, text: 'Servicios legales — honorarios', why: 'Contratos, demandas, juicios, defensa fiscal. Por evento, por hora, o cuota litis.', inputType: 'textarea', required: false },
    { number: 8, text: 'Direccion, horario y modalidad', why: 'Presencial, hibrido, 100% remoto. Horario de atencion al publico.', inputType: 'textarea', required: true },
    { number: 9, text: 'Software contable que usan', why: 'CONTPAQi, Aspel COI/SAE, Bind, Odoo. Determina como reciben info del cliente.', inputType: 'select', required: true },
    { number: 10, text: 'Como reciben documentos del cliente', why: 'WhatsApp, correo, drive, portal. Frecuencia (diario, semanal, mensual). Fecha limite.', inputType: 'textarea', required: true },
    { number: 11, text: 'Formas de pago de honorarios', why: 'Transferencia, deposito, tarjeta, MSI. Adelantado o vencido.', inputType: 'multiselect', required: true },
    { number: 12, text: 'Politica de morosidad', why: 'Que pasa si el cliente no paga la iguala. Suspension de servicio. Cuando.', inputType: 'textarea', required: true },
    { number: 13, text: 'Confidencialidad', why: 'Manejo de datos fiscales. LFPDPPP. NDA si aplica.', inputType: 'textarea', required: true },
    { number: 14, text: 'Que NO hacen', why: 'Para no agendar lo equivocado. Ej: penal, familiar, notarial, peritajes.', inputType: 'textarea', required: true },
    { number: 15, text: 'Tono del chatbot', why: 'Profesional, claro, sin jerga fiscal. Los duenos de negocio quieren respuestas concretas.', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Socio o titular para auditorias SAT, embargos, e.firma comprometida — escalar en minutos.', inputType: 'text', required: true },
  ],
  seguros: [
    { number: 1, text: 'Nombre del agente o agencia', why: 'Como aparece en cedula CNSF y como quieren ser referidos.', inputType: 'text', required: true },
    { number: 2, text: 'Cedula CNSF (Comision Nacional de Seguros y Fianzas)', why: 'Obligatoria para operar. Verificable. Sin cedula no hay venta legal.', inputType: 'text', required: true },
    { number: 3, text: 'Aseguradoras que representan', why: 'GNP, AXA, MAPFRE, Qualitas, HDI, ANA, Chubb, MetLife, Allianz, Atlas, BBVA, Banorte, Inbursa.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Ramos que manejan', why: 'Auto, GMM, vida, hogar, empresarial, fianzas, daños, viaje, mascotas, accidentes personales.', inputType: 'multiselect', required: true },
    { number: 5, text: 'Direccion y horario', why: 'Oficina fisica si aplica. Atencion remota.', inputType: 'textarea', required: true },
    { number: 6, text: 'Proceso de cotizacion — auto', why: 'Datos minimos requeridos (marca, modelo, ano, CP, edad conductor). Tiempo de respuesta.', inputType: 'textarea', required: true },
    { number: 7, text: 'Proceso de cotizacion — GMM', why: 'Datos requeridos (edad, suma asegurada, deducible, padecimientos). Periodos de espera.', inputType: 'textarea', required: true },
    { number: 8, text: 'Comparativos entre aseguradoras', why: 'Hacen tabla comparativa? En cuanto tiempo? Gratis o con costo.', inputType: 'boolean', required: false },
    { number: 9, text: 'Formas de pago de la prima', why: 'Anual, semestral, trimestral, mensual. Tarjeta, transferencia, domiciliacion. Recargos por fraccionamiento.', inputType: 'multiselect', required: true },
    { number: 10, text: 'Renovacion automatica', why: 'Como manejan renovaciones. Avisan al cliente cuando.', inputType: 'textarea', required: true },
    { number: 11, text: 'Reporte de siniestro — protocolo', why: 'PASO A PASO claro. Numero de emergencia de cada aseguradora. Que datos pedir primero. CRITICO — el bot debe canalizar bien.', inputType: 'textarea', required: true, followUpInsight: 'Los siniestros llegan a cualquier hora. Tu bot puede dar el numero correcto al instante y guiar al asegurado.' },
    { number: 12, text: 'Tiempos de pago de siniestro', why: 'Por aseguradora y tipo. NUNCA prometer plazos sin verificar.', inputType: 'textarea', required: true },
    { number: 13, text: 'Quejas CONDUSEF — postura', why: 'Como orientan al cliente. NUNCA obstruir. Plazos legales.', inputType: 'textarea', required: true },
    { number: 14, text: 'Servicios adicionales', why: 'Auto sustituto, asistencia vial, asistencia legal, segunda opinion medica — que aseguradoras lo incluyen.', inputType: 'textarea', required: false },
    { number: 15, text: 'Documentos que debe entregar el cliente', why: 'Para emision: INE, CP, datos del bien. Para siniestro: parte de policia, fotos, etc.', inputType: 'textarea', required: true },
    { number: 16, text: 'Tono del chatbot', why: 'Profesional, claro, empatico. Especial cuidado con vida y siniestros.', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'CRITICO para siniestros mayores, fallecimientos, fraudes. Numero directo del agente.', inputType: 'text', required: true },
  ],
  taller_mecanico: [
    { number: 1, text: 'Nombre del taller', why: 'Como aparece en letrero/RFC.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion completa con referencias', why: 'Muchos talleres estan en zonas dificiles de ubicar. Estacionamiento.', inputType: 'textarea', required: true },
    { number: 3, text: 'Horario de atencion', why: 'Por dia. Si abren sabados/domingos. Hora limite para recibir vehiculos.', inputType: 'textarea', required: true },
    { number: 4, text: 'Marcas/modelos que atienden', why: 'Multimarca, especializado (VW, Nissan, Ford, japonesas, europeas, americanas). Restricciones.', inputType: 'multiselect', required: true },
    { number: 5, text: 'Servicios que ofrecen', why: 'Afinacion, frenos, suspension, transmision, motor, electrico, hojalateria, pintura, alineacion, balanceo, A/C, diagnostico computarizado, verificacion.', inputType: 'multiselect', required: true },
    { number: 6, text: 'Lista de precios — servicios comunes', why: 'Afinacion (chico, mediano, grande), cambio de balatas, cambio de aceite, alineacion, balanceo, escaneo. PRECIO EXACTO o rango.', inputType: 'price_list', required: true, followUpInsight: 'El precio de afinacion y frenos es la pregunta #1 por WhatsApp. Tu bot la responde al instante y agenda.' },
    { number: 7, text: 'Servicios que requieren diagnostico antes de cotizar', why: 'Motor, transmision, electrico complejo. CRITICO — el bot NUNCA debe diagnosticar por chat.', inputType: 'textarea', required: true },
    { number: 8, text: 'Refacciones — originales, alternativas o ambas', why: 'Politica. El cliente puede llevar sus propias refacciones? Garantia cambia?', inputType: 'textarea', required: true },
    { number: 9, text: 'Garantia', why: 'En mano de obra y refacciones. PROFECO obliga garantia minima. Por escrito.', inputType: 'textarea', required: true },
    { number: 10, text: 'Tiempo estimado de servicios comunes', why: 'Afinacion, frenos, alineacion. Cuando el cliente puede pasar por su auto.', inputType: 'textarea', required: true },
    { number: 11, text: 'Servicio de grua', why: 'Propio o convenio. Costo. Zona de cobertura.', inputType: 'textarea', required: false },
    { number: 12, text: 'Auto sustituto o transporte', why: 'Para servicios largos. Disponible? Costo?', inputType: 'boolean', required: false },
    { number: 13, text: 'Formas de pago', why: 'Efectivo, tarjeta, transferencia, MSI. Anticipo para reparaciones grandes.', inputType: 'multiselect', required: true },
    { number: 14, text: 'Facturacion CFDI', why: 'Disponible. Datos requeridos.', inputType: 'boolean', required: true },
    { number: 15, text: 'Politica de presupuesto autorizado', why: 'PROFECO: NO se puede cobrar mas del presupuesto sin autorizacion ESCRITA del cliente. Como lo manejan.', inputType: 'textarea', required: true },
    { number: 16, text: 'Tono del chatbot', why: 'Cercano, claro, sin jerga mecanica. Generar confianza — el sector tiene mala reputacion.', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'Dueno o jefe de taller para disputas, danos al vehiculo, urgencias.', inputType: 'text', required: true },
  ],
  escuela: [
    { number: 1, text: 'Nombre oficial de la escuela', why: 'Razon social y nombre comercial. Como aparece en RVOE.', inputType: 'text', required: true },
    { number: 2, text: 'Niveles educativos que ofrecen', why: 'Maternal, preescolar, primaria, secundaria, preparatoria/bachillerato, universidad.', inputType: 'multiselect', required: true },
    { number: 3, text: 'Numero(s) de RVOE / incorporacion SEP/UNAM/IPN', why: 'CRITICO — inventar un RVOE es potencialmente ilegal. Por nivel educativo. Verificable en SIRESOE.', inputType: 'textarea', required: true },
    { number: 4, text: 'Direccion(es) y horario escolar', why: 'Por nivel. Hora de entrada y salida. Si hay turnos.', inputType: 'textarea', required: true },
    { number: 5, text: 'Colegiaturas — monto por nivel', why: 'Inscripcion + colegiatura mensual + cuantos meses. PROFECO: el costo total debe ser claro.', inputType: 'price_list', required: true, followUpInsight: 'El costo de la colegiatura es la pregunta #1. Tu bot responde con el monto exacto y agenda visita.' },
    { number: 6, text: 'Cuotas adicionales obligatorias', why: 'Sociedad de padres, materiales, seguro escolar, plataforma digital. PROFECO obliga a desglosar.', inputType: 'textarea', required: true },
    { number: 7, text: 'Becas disponibles', why: 'Tipo (academica, deportiva, hermanos, economica), porcentajes, requisitos. NO inventar.', inputType: 'textarea', required: true },
    { number: 8, text: 'Proceso de admision', why: 'Documentos, examen, entrevista, fechas limite. Por nivel.', inputType: 'textarea', required: true },
    { number: 9, text: 'Calendario escolar', why: 'Inicio, fin, vacaciones, suspensiones. Alineado con SEP o calendario propio.', inputType: 'textarea', required: true },
    { number: 10, text: 'Servicios extra', why: 'Transporte (rutas, costo), comedor, after-school, talleres, deportes, ingles, idiomas adicionales.', inputType: 'textarea', required: false },
    { number: 11, text: 'Uniformes', why: 'Donde se compran. Costo aproximado. Diario, gala, deportivo.', inputType: 'textarea', required: false },
    { number: 12, text: 'Lista de utiles', why: 'Donde se obtiene. Cuando se publica. Aproximadamente cuanto cuesta.', inputType: 'textarea', required: false },
    { number: 13, text: 'Plataforma digital de padres', why: 'Como consultan calificaciones, tareas, comunicados. Plataforma usada.', inputType: 'textarea', required: false },
    { number: 14, text: 'Formas de pago de colegiatura', why: 'Efectivo, transferencia, tarjeta, domiciliacion, MSI. Recargos por pago tarde. Descuento por pronto pago.', inputType: 'multiselect', required: true },
    { number: 15, text: 'Politica de pago atrasado', why: 'PROFECO: NO se puede retener boletas/constancias por adeudo. Como manejan recordatorios.', inputType: 'textarea', required: true },
    { number: 16, text: 'Modelo educativo', why: 'Tradicional, montessori, constructivista, bilingue, religioso. Diferenciador clave.', inputType: 'textarea', required: true },
    { number: 17, text: 'Idiomas que ensenan', why: 'Ingles (horas/semana, certificacion), frances, mandarin, otros.', inputType: 'textarea', required: false },
    { number: 18, text: 'Tono del chatbot', why: 'Calido, profesional, orientado a papas. Sensible con temas de seguridad.', inputType: 'select', required: true },
    { number: 19, text: 'Contacto de escalacion', why: 'Direccion para emergencias de seguridad, bullying, disputas de pago. CRITICO.', inputType: 'text', required: true },
  ],
  agencia_digital: [
    { number: 1, text: 'Nombre de la agencia', why: 'Nombre comercial. Razon social si es diferente.', inputType: 'text', required: true },
    { number: 2, text: 'Servicios principales', why: 'SEO, SEM, social media, branding, diseno web, e-commerce, contenido, video, email marketing, growth, performance.', inputType: 'multiselect', required: true },
    { number: 3, text: 'Tipo de cliente ideal', why: 'PYME, enterprise, ecommerce, B2B, B2C, sector especifico. Para no agendar fuera de fit.', inputType: 'textarea', required: true },
    { number: 4, text: 'Ticket minimo / inversion minima', why: 'Por proyecto y por iguala mensual. Sirve de filtro.', inputType: 'text', required: true },
    { number: 5, text: 'Modelos de cobro', why: 'Iguala mensual (retainer), por proyecto, por hora, performance-based. Detalles.', inputType: 'textarea', required: true },
    { number: 6, text: 'Rangos de precio por servicio', why: 'SEO ($X-Y/mes), Ads management (% del spend o fee), social media ($X-Y/mes), web ($X-Y por proyecto).', inputType: 'price_list', required: true, followUpInsight: 'El precio aproximado es la primera pregunta. Tu bot da rangos claros y filtra prospects.' },
    { number: 7, text: 'Compromiso minimo', why: '3, 6, 12 meses. Penalizacion por terminacion anticipada.', inputType: 'text', required: true },
    { number: 8, text: 'Entregables y reportes', why: 'Frecuencia (semanal, quincenal, mensual). Plataforma (AgencyAnalytics, Looker Studio, custom). Que metricas.', inputType: 'textarea', required: true },
    { number: 9, text: 'KPIs por servicio', why: 'SEO: trafico organico, posiciones. Ads: CPA, ROAS. Social: engagement, reach. Para alinear expectativas.', inputType: 'textarea', required: true },
    { number: 10, text: 'Casos de exito / portfolio', why: 'Donde se pueden ver. Sectores trabajados. Resultados publicos.', inputType: 'textarea', required: false },
    { number: 11, text: 'Equipo y punto de contacto', why: 'Account manager dedicado o pool. Quien atiende al cliente. Tamano del equipo por proyecto.', inputType: 'textarea', required: true },
    { number: 12, text: 'Proceso de onboarding', why: 'Discovery, kickoff, accesos, primera entrega. Tiempo desde firma a primer entregable.', inputType: 'textarea', required: true },
    { number: 13, text: 'Propiedad de cuentas y assets', why: 'Quien es dueno de Ads accounts, Analytics, redes, sitio web. CRITICO — debe ser el cliente.', inputType: 'textarea', required: true },
    { number: 14, text: 'Formas de pago', why: 'Transferencia, tarjeta, MSI, Stripe link. Anticipo, contra entrega, vencido.', inputType: 'multiselect', required: true },
    { number: 15, text: 'Facturacion CFDI', why: 'Disponible. Datos requeridos.', inputType: 'boolean', required: true },
    { number: 16, text: 'Politica de revisiones y cambios', why: 'Cuantas rondas incluye, costo de adicionales. Para diseno y contenido.', inputType: 'textarea', required: true },
    { number: 17, text: 'Tono del chatbot', why: 'Profesional, ágil, data-driven. Demostrar dominio sin jerga excesiva.', inputType: 'select', required: true },
    { number: 18, text: 'Contacto de escalacion', why: 'Director o gerente para crisis en redes, ROAS bajo, disputas de contrato.', inputType: 'text', required: true },
  ],
  fotografo: [
    { number: 1, text: 'Nombre del fotografo o estudio', why: 'Marca. Como aparece en redes y portfolio.', inputType: 'text', required: true },
    { number: 2, text: 'Especialidades', why: 'Boda, retrato, familia, newborn, embarazo, XV, graduacion, producto, comida, real estate, evento corporativo, headshots.', inputType: 'multiselect', required: true },
    { number: 3, text: 'Estilo fotografico', why: 'Documental, posado, fine art, lifestyle, editorial. Que NO hacen tambien.', inputType: 'textarea', required: true },
    { number: 4, text: 'Zona de cobertura', why: 'Ciudad, area metropolitana. Cobran traslado fuera. Disponible para destination weddings.', inputType: 'textarea', required: true },
    { number: 5, text: 'Paquetes con precios', why: 'Por especialidad. Cada paquete: duracion, # fotos editadas, entregables, extras. PRECIO EXACTO.', inputType: 'price_list', required: true, followUpInsight: 'Los precios de paquetes son la pregunta #1. Tu bot los responde al instante con detalle.' },
    { number: 6, text: 'Disponibilidad y proceso de reserva', why: 'Como verifican calendario. Cuanto anticipo. Que datos necesitan para apartar fecha. NUNCA confirmar sin verificar — doble booking es catastrofe.', inputType: 'textarea', required: true },
    { number: 7, text: 'Anticipo para apartar fecha', why: '% del paquete. Reembolsable o no. Plazo para liquidar.', inputType: 'text', required: true },
    { number: 8, text: 'Tiempo de entrega de fotos', why: 'Sneak peek, galeria completa. Para sesiones cortas y para bodas. NUNCA prometer menos.', inputType: 'textarea', required: true },
    { number: 9, text: '# de fotos editadas por paquete', why: 'Cifra exacta. Politica de fotos extras.', inputType: 'textarea', required: true },
    { number: 10, text: 'Forma de entrega', why: 'Galeria online (Pixieset, ShootProof), USB, drive, impresas, album. Vigencia de la galeria.', inputType: 'textarea', required: true },
    { number: 11, text: 'Album impreso / productos fisicos', why: 'Disponible. Precios. Tiempos. Marcas que usan.', inputType: 'textarea', required: false },
    { number: 12, text: 'Segundo fotografo / asistente', why: 'Disponible para bodas y eventos grandes. Costo extra.', inputType: 'textarea', required: false },
    { number: 13, text: 'Politica de cancelacion / reagendamiento', why: 'Cuanto se devuelve. Plazos. Por clima u otras causas.', inputType: 'textarea', required: true },
    { number: 14, text: 'Derechos de uso de las fotos', why: 'Quien es dueno. Uso comercial vs personal. Quien puede publicar en redes. CRITICO para producto y corporativo.', inputType: 'textarea', required: true },
    { number: 15, text: 'Formas de pago', why: 'Transferencia, tarjeta, MSI, Stripe link. Anticipo + liquidacion.', inputType: 'multiselect', required: true },
    { number: 16, text: 'Facturacion CFDI', why: 'Disponible. Datos requeridos.', inputType: 'boolean', required: true },
    { number: 17, text: 'Plan B para clima / imprevistos', why: 'Sesiones outdoor. Ubicacion alterna. Reagendamiento.', inputType: 'textarea', required: false },
    { number: 18, text: 'Tono del chatbot', why: 'Calido, creativo, profesional. Bodas son emocionales — empatia clave.', inputType: 'select', required: true },
    { number: 19, text: 'Contacto de escalacion', why: 'Para clientes insatisfechos, falla de equipo, doble booking. Numero directo.', inputType: 'text', required: true },
  ],
};
