import type { VerticalEnum, VerticalQuestion } from '@/lib/verticals/types';

export const gastronomiaQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  restaurante: [
    {
      number: 1,
      text: 'Nombre del restaurante',
      why: 'Exactamente como aparece en fachada y redes sociales',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion completa con link de Google Maps',
      why: 'Imprescindible para enviar ubicacion por WhatsApp',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario de operacion por dia',
      why: 'Incluir si varia entre servicio de comida y cena',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tipo de cocina',
      why: 'Mexicana, italiana, japonesa, mariscos, fusion, etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 5,
      text: 'Menu COMPLETO con precios',
      why: 'Cada platillo, descripcion breve, precio. Organizado por categoria',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El menu es la base de todo. Los clientes preguntan precios y platillos en el 80% de las conversaciones por WhatsApp.',
    },
    {
      number: 6,
      text: 'Alergenos e ingredientes criticos por platillo',
      why: 'Gluten, lacteos, mariscos, nueces, soya. Obligatorio para seguridad',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Opciones vegetarianas, veganas, sin gluten',
      why: 'Cuales platillos especificamente',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Servicio de reservaciones',
      why: 'Si/No. Capacidad maxima. Anticipacion requerida. Deposito. Politica de no-show',
      inputType: 'text',
      required: true,
    },
    {
      number: 9,
      text: 'Entregas a domicilio',
      why: 'Propio, UberEats, Rappi, DiDi Food. Zonas de cobertura. Minimo de pedido. Costo de envio',
      inputType: 'text',
      required: true,
      followUpInsight:
        'Los restaurantes con delivery responden 3x mas mensajes. El bot puede tomar pedidos automaticamente.',
    },
    {
      number: 10,
      text: 'Servicio para llevar (takeout)',
      why: 'Disponible? Tienen descuento vs. comer ahi?',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, MSI (monto minimo, bancos), propina sugerida',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        "Pregunta top 7 de clientes: 'Aceptan tarjeta?' — tu bot lo respondera al instante.",
    },
    {
      number: 12,
      text: 'Facturacion CFDI',
      why: 'Disponible? Proceso (QR en ticket, solicitar por WhatsApp)',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 13,
      text: 'Estacionamiento',
      why: 'Propio, valet, calle. Costo. Convenio',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Eventos privados',
      why: 'Capacidad, paquetes, presupuesto minimo, menu especial',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 15,
      text: 'Promociones vigentes',
      why: 'Happy hour, 2x1, paquetes familiares, dia de la semana especial',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Programa de lealtad',
      why: 'Puntos, decima comida gratis, etc',
      inputType: 'text',
      required: false,
    },
    {
      number: 17,
      text: 'Areas especiales',
      why: 'Terraza, salon privado, barra, area infantil, pet friendly',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 18,
      text: 'WiFi',
      why: 'Disponible? Password?',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'Musica en vivo',
      why: 'Dias, horarios, genero',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Redes sociales',
      why: 'Instagram, Facebook, TripAdvisor',
      inputType: 'text',
      required: false,
    },
    {
      number: 21,
      text: 'Tono del chatbot',
      why: 'Casual-amigable para casual dining, formal para fine dining',
      inputType: 'select',
      required: true,
    },
    {
      number: 22,
      text: 'Contacto de escalacion',
      why: 'Gerente o encargado para quejas o reservaciones grandes',
      inputType: 'text',
      required: true,
    },
  ],

  taqueria: [
    {
      number: 1,
      text: 'Nombre de la taqueria',
      why: 'Tal como aparece en letrero/redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion con referencias',
      why: 'Incluir esquina, cerca de que',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario — y si cierran cuando se acaba el producto',
      why: "'Cerramos cuando se acaba el pastor' es realidad mexicana. El bot debe saber esto",
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'MENU COMPLETO con precios',
      why: 'Cada taco, precio por pieza. Orden de tacos, gringas, quesadillas, volcanes, campechanos, alambres, tortas',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'En taquerias, el precio por taco es la pregunta #1. Con el menu completo, tu bot atiende al instante.',
    },
    {
      number: 5,
      text: 'Tipos de carne disponibles',
      why: 'Pastor, bistec, suadero, longaniza, tripa, cabeza, lengua, chorizo, campechano. Cuales NO tienen',
      inputType: 'multiselect',
      required: true,
      followUpInsight:
        "Los clientes siempre preguntan 'Tienen suadero/tripa/lengua?'. Tu bot sabra exactamente que ofrecer.",
    },
    {
      number: 6,
      text: 'Tipo de tortilla',
      why: 'Maiz, harina, ambas. Si cobran extra por harina',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Salsas disponibles',
      why: 'Verde, roja, habanero, guacamole. Cuales son picantes. Si el guacamole tiene costo extra',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Venta por kilo',
      why: 'Disponible? Precio por kilo de cada carne. Minimo de compra',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'Complementos',
      why: 'Frijoles, cebollitas, nopales, queso, cebolla asada. Precios si aplica',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Bebidas',
      why: 'Aguas frescas, refrescos, cerveza (REQUIERE LICENCIA). Precios',
      inputType: 'text',
      required: true,
    },
    {
      number: 11,
      text: 'Formas de pago',
      why: '60-80% de taquerias son cash-heavy. Si aceptan tarjeta, especificar',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 12,
      text: 'Delivery',
      why: 'Plataformas? Propio? Zona? Minimo?',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Facturacion CFDI',
      why: 'Muchas taquerias informales no facturan — es valido informar',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: "Casual, directo, rapido. 'Que te ponemos?' vibes",
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Dueno o encargado',
      inputType: 'text',
      required: true,
    },
  ],

  // Sprint 2 stubs
  cafeteria: [
    {
      number: 1,
      text: 'Nombre de la cafeteria',
      why: 'Tal como aparece en letrero/redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario por dia',
      why: 'Muchos cafes abren temprano (7AM) y cierran temprano (6-8PM)',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Menu de cafes con precios',
      why: 'Americano, latte, cappuccino, mocha, espresso, cold brew, matcha, chai, te. Por tamano si aplica',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'El menu de cafes es lo que mas preguntan. Tu bot respondera precios y opciones al instante.',
    },
    {
      number: 4,
      text: 'Leches alternativas disponibles',
      why: 'Avena, almendra, soy, coco, deslactosada. Costo extra? Cuanto?',
      inputType: 'text',
      required: true,
    },
    {
      number: 5,
      text: 'Menu de alimentos',
      why: 'Pasteles, galletas, sandwiches, desayunos, brunch. Precios',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Opciones veganas y sin gluten',
      why: 'Cuales especificamente',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 7,
      text: 'Venta de cafe en grano/molido',
      why: 'Origen, tostado, precio por presentacion (250g, 500g, 1kg)',
      inputType: 'text',
      required: false,
    },
    {
      number: 8,
      text: 'Metodo de preparacion que ofrecen',
      why: 'Espresso, pour over, chemex, aeropress, french press, sifon',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'WiFi',
      why: 'Disponible? Password? Limite de tiempo?',
      inputType: 'text',
      required: true,
      followUpInsight:
        'La contrasena del WiFi es la pregunta #1 en cafeterias. Tu bot la dara en 2 segundos.',
    },
    {
      number: 10,
      text: 'Enchufes disponibles?',
      why: 'Para laptops — la pregunta #1 de freelancers',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 11,
      text: 'Pet friendly?',
      why: 'Interior, exterior, con agua/premios?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 12,
      text: 'Programa de lealtad',
      why: 'Tarjeta de sellos, app, puntos',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, QR, SPEI',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 14,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 15,
      text: 'Tono del chatbot',
      why: 'Casual-cool. La cultura del specialty coffee en Mexico es informal',
      inputType: 'select',
      required: true,
    },
    {
      number: 16,
      text: 'Redes sociales',
      why: 'Instagram es CRITICO para cafeterias',
      inputType: 'text',
      required: false,
    },
    {
      number: 17,
      text: 'Contacto de escalacion',
      why: 'Barista en jefe o dueno',
      inputType: 'text',
      required: true,
    },
  ],
  panaderia: [
    {
      number: 1,
      text: 'Nombre de la panaderia',
      why: 'Como aparece en fachada',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y horario',
      why: 'A que hora sale el pan caliente? Esto lo preguntan MUCHO',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Catalogo de pan con precios',
      why: 'Pan dulce (pieza y por charola), pan salado, pasteles, galletas. Precios individuales y por docena/charola',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 4,
      text: 'Pasteles personalizados — proceso',
      why: 'Sabores, tamanos, rellenos, decoracion. Se necesita cotizacion especial? Tiempo de anticipacion',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Precios de pasteles por tamano',
      why: '10 personas, 20, 30, 50, 100. Rango o fijo. Que incluye decoracion',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Pan de temporada',
      why: 'Rosca de Reyes (enero), Pan de Muerto (octubre-noviembre). Fechas de venta y precios',
      inputType: 'text',
      required: false,
    },
    {
      number: 7,
      text: 'Venta de mayoreo',
      why: 'Para tiendas, cafeterias, eventos. Precios diferenciados? Minimo de compra',
      inputType: 'text',
      required: false,
    },
    {
      number: 8,
      text: 'Pedidos especiales — anticipacion',
      why: 'Con cuantos dias de anticipacion? Deposito requerido?',
      inputType: 'text',
      required: true,
    },
    {
      number: 9,
      text: 'Servicio a domicilio',
      why: 'Zona, costo, minimo de pedido',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Horarios de pan fresco',
      why: 'A que hora sale cada tipo de pan — CRITICO para clientes',
      inputType: 'text',
      required: true,
      followUpInsight:
        "Los clientes SIEMPRE preguntan 'a que hora sale el pan caliente'. Tu bot respondera horarios exactos.",
    },
    {
      number: 11,
      text: 'Ingredientes/alergenos',
      why: 'Trigo, huevo, leche, nueces — todo el pan tiene alergenos',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 12,
      text: 'Formas de pago',
      why: 'Efectivo dominante en panaderias. Tarjeta disponible?',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 13,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 14,
      text: 'Tono del chatbot',
      why: "Calido, familiar. 'La panaderia del barrio' vibes",
      inputType: 'select',
      required: true,
    },
    {
      number: 15,
      text: 'Contacto de escalacion',
      why: 'Dueno o encargado para pedidos grandes y pasteles',
      inputType: 'text',
      required: true,
    },
  ],
  bar_cantina: [
    {
      number: 1,
      text: 'Nombre del bar/cantina',
      why: 'Como aparece en fachada',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion',
      why: 'Con referencias para Uber/taxi',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Horario por dia',
      why: 'CDMX bares: 11AM-2:30AM tipicamente. Varia por municipio',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tipo de establecimiento',
      why: 'Bar, cantina, rooftop, sports bar, mezcaleria, cocteleria, club nocturno',
      inputType: 'text',
      required: true,
    },
    {
      number: 5,
      text: 'Menu de bebidas con precios',
      why: 'Cervezas (marca, presentacion, precio), cocteles, destilados, vinos. Servicio de botella con precios',
      inputType: 'price_list',
      required: true,
      followUpInsight:
        'Los precios de bebidas son la pregunta #1 de clientes por WhatsApp. Tu bot los tendra listos.',
    },
    {
      number: 6,
      text: 'Menu de comida',
      why: "Si aplica — cantinas ofrecen 'botanita' incluida con consumo",
      inputType: 'textarea',
      required: false,
    },
    {
      number: 7,
      text: 'Cover / entrada',
      why: 'Costo? Varia por noche/genero? Incluye consumo?',
      inputType: 'text',
      required: false,
    },
    {
      number: 8,
      text: 'Codigo de vestimenta',
      why: 'Si aplica',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'Reservaciones de mesa/VIP',
      why: 'Disponible? Consumo minimo? Como reservar',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Eventos y musica en vivo',
      why: 'Programacion semanal. DJs, bandas, karaoke, trivia. DIAS EXACTOS',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Happy hour',
      why: 'Horario exacto, que incluye, restricciones',
      inputType: 'text',
      required: false,
    },
    {
      number: 12,
      text: 'Edad minima y verificacion',
      why: '18 anos obligatorio. INE/IFE, pasaporte',
      inputType: 'text',
      required: true,
    },
    {
      number: 13,
      text: 'Estacionamiento / valet',
      why: 'Disponible? Costo? Convenio',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Formas de pago',
      why: 'Tarjeta, efectivo, MSI para botella service',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 15,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 16,
      text: 'Eventos privados',
      why: 'Capacidad, paquetes, consumo minimo',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 17,
      text: 'Tono del chatbot',
      why: 'Cool, directo, vibes del lugar. No corporativo',
      inputType: 'select',
      required: true,
    },
    {
      number: 18,
      text: 'Contacto de escalacion',
      why: 'Gerente nocturno',
      inputType: 'text',
      required: true,
    },
  ],
  food_truck: [
    {
      number: 1,
      text: 'Nombre del food truck',
      why: 'Tal como aparece en vehiculo/redes',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Tipo de comida',
      why: 'Tacos, hamburguesas, hot dogs, sushi, etc',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Ubicaciones habituales',
      why: 'Fija, rotativa, por dia. ESTA ES LA INFO MAS CRITICA — donde me encuentran hoy?',
      inputType: 'text',
      required: true,
      followUpInsight:
        'La ubicacion es la pregunta #1 de food trucks. Tu bot redirigira a tus stories de Instagram para ubicacion en tiempo real.',
    },
    {
      number: 4,
      text: 'Horario por dia/ubicacion',
      why: 'Varia con ubicacion. Si es irregular, como lo anuncian (IG stories)',
      inputType: 'text',
      required: true,
    },
    {
      number: 5,
      text: 'Menu COMPLETO con precios',
      why: 'Menu tipicamente reducido vs. restaurante — listar todo',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 6,
      text: 'Instagram/redes para ubicacion diaria',
      why: 'El bot debe redirigir a IG para ubicacion en tiempo real',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Participacion en eventos/festivales',
      why: 'Cuales, cuando, si el menu cambia',
      inputType: 'text',
      required: false,
    },
    {
      number: 8,
      text: 'Catering/eventos privados',
      why: 'Disponible? Minimo de personas? Precio por persona?',
      inputType: 'text',
      required: false,
    },
    {
      number: 9,
      text: 'Formas de pago',
      why: 'Clip es el estandar. Efectivo tambien?',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 10,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 11,
      text: 'Tono del chatbot',
      why: 'Casual, divertido, streetfood vibes',
      inputType: 'select',
      required: true,
    },
    {
      number: 12,
      text: 'Contacto',
      why: 'Numero directo del dueno/operador',
      inputType: 'text',
      required: true,
    },
  ],
};
