import type { VerticalEnum, VerticalQuestion } from '@/lib/verticals/types';

export const hospedajeQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  hotel: [
    {
      number: 1,
      text: 'Nombre del hotel',
      why: 'Exacto, incluyendo estrellas/categoria',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y como llegar desde aeropuerto/terminal',
      why: 'Distancia, tiempo, opciones de transporte',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Clasificacion SECTUR',
      why: 'Estrellas. Registro Nacional de Turismo (RNT)',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'Tipos de habitacion',
      why: 'Nombre, descripcion, capacidad maxima, cama(s), vista, m2, amenidades de cada tipo',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Tarifas por tipo de habitacion',
      why: 'Rack rate y si tienen tarifas dinamicas. Temporada alta vs baja. Rango o referir a motor de reservas',
      inputType: 'textarea',
      required: true,
      followUpInsight:
        'Las tarifas son la pregunta #1 en WhatsApp. Con rangos por temporada, tu bot responde al instante sin inventar precios.',
    },
    {
      number: 6,
      text: 'Check-in y check-out',
      why: 'Horarios. Early check-in / late check-out disponible? Costo?',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Que incluye la tarifa',
      why: 'Desayuno? WiFi? Estacionamiento? Gimnasio? Alberca?',
      inputType: 'textarea',
      required: true,
      followUpInsight:
        "Pregunta #3 de huespedes: '¿El desayuno esta incluido?' — tu bot lo resolvera en segundos.",
    },
    {
      number: 8,
      text: 'Restaurantes y bares del hotel',
      why: 'Nombre, tipo de cocina, horario, dress code, si necesita reservacion',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 9,
      text: 'Amenidades completas',
      why: 'Alberca (horario), gimnasio, spa, business center, salon de eventos, kids club. Horarios de cada uno',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Servicios adicionales',
      why: 'Room service, lavanderia, concierge, tours, transportacion. Precios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Politica de cancelacion',
      why: 'Por canal (directa vs. OTA). Penalizacion. Free cancellation deadline',
      inputType: 'text',
      required: true,
      followUpInsight:
        'La politica de cancelacion es critica. Un error aqui genera disputas y malas resenas.',
    },
    {
      number: 12,
      text: 'Politica de mascotas',
      why: 'Aceptan? Tamano maximo? Costo adicional? Areas permitidas',
      inputType: 'text',
      required: false,
    },
    {
      number: 13,
      text: 'Estacionamiento',
      why: 'Incluido o adicional? Cubierto? Valet? Costo',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Eventos/bodas/grupos',
      why: 'Salones, capacidad, paquetes, contacto del coordinador',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 15,
      text: 'Transfer aeropuerto',
      why: 'Ofrecen? Costo? Como reservar? Compartido o privado?',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Formas de pago',
      why: 'Tarjeta obligatoria para garantia? MSI? Tipos de cambio si aplica',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 17,
      text: 'Facturacion CFDI',
      why: 'Proceso. ISH (Impuesto Sobre Hospedaje 2-5% estatal) incluido',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 18,
      text: 'Idiomas del staff',
      why: 'Espanol, ingles, frances, aleman — relevante para hoteles turisticos',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'PMS actual',
      why: 'Para integracion con chatbot — Opera, Cloudbeds, otro?',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Motor de reservas web',
      why: 'URL para que el bot pueda enviar link de reserva directa',
      inputType: 'text',
      required: false,
    },
    {
      number: 21,
      text: 'Tono del chatbot',
      why: 'Formal-elegante para luxury, casual-amigable para boutique',
      inputType: 'select',
      required: true,
    },
    {
      number: 22,
      text: 'Contacto de escalacion',
      why: 'Front desk manager, revenue manager',
      inputType: 'text',
      required: true,
    },
  ],

  // Sprint 1 stubs — full questions coming in future sprints
  hotel_boutique: [
    {
      number: 1,
      text: 'Nombre del hotel boutique',
      why: 'Nombre unico/artesanal',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Historia o concepto del hotel',
      why: 'Lo que lo hace especial — arquitectura, diseno, historia. El bot debe poder contar la historia',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 3,
      text: 'Numero de habitaciones',
      why: 'Tipicamente 5-30 para boutique',
      inputType: 'text',
      required: true,
    },
    {
      number: 4,
      text: 'CADA habitacion con descripcion unica',
      why: 'Nombre, decoracion, tamano, vista, cama, amenidades unicas. Los huespedes eligen habitacion especifica',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Tarifa por habitacion por temporada',
      why: 'Alta, baja, Semana Santa, Navidad, eventos locales',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Experiencia del huesped de inicio a fin',
      why: 'Bienvenida (drink, amenity), turndown service, desayuno, detalles especiales',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Desayuno — que incluye, donde, horario',
      why: 'Incluido en tarifa? Tipo (continental, mexicano, gourmet)',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Amenidades unicas',
      why: 'Terraza privada, jacuzzi, jardin, biblioteca, galeria, spa, yoga',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 9,
      text: 'Recomendaciones locales aprobadas',
      why: 'Restaurantes, tours, actividades — SOLO las que el hotel recomienda oficialmente',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 10,
      text: 'Paquetes especiales',
      why: 'Romantico, aniversario, luna de miel, wellness. Que incluye cada uno',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Target market',
      why: 'Parejas, familias, corporativo, wellness — para tono del bot',
      inputType: 'text',
      required: false,
    },
    {
      number: 12,
      text: 'Reservacion directa vs. OTAs',
      why: 'URL del motor de reservas. Incentivo por reserva directa (upgrade, amenity)',
      inputType: 'text',
      required: true,
    },
    {
      number: 13,
      text: 'Formas de pago',
      why: 'MSI importante para tarifas premium',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 14,
      text: 'Facturacion CFDI',
      why: 'Incluir ISH',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 15,
      text: 'Idiomas',
      why: 'Ingles es casi obligatorio en boutique turistico',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Tono del chatbot',
      why: 'Personalizado, calido, exclusivo. Como un concierge privado',
      inputType: 'select',
      required: true,
    },
    {
      number: 17,
      text: 'Contacto de escalacion',
      why: 'Dueno o gerente general — en boutiques suele ser el mismo',
      inputType: 'text',
      required: true,
    },
  ],
  motel: [
    {
      number: 1,
      text: 'Nombre del motel',
      why: 'Como aparece en fachada',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion',
      why: 'Discrecion es importante — no dar en redes publicas',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Tipos de habitacion',
      why: 'Estandar, jacuzzi, suite, tematica. Descripcion de cada una',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 4,
      text: 'Tarifas por modalidad',
      why: 'Por hora (2h, 4h, 6h), por noche, cronometro. PRECIO EXACTO de cada modalidad por tipo de habitacion',
      inputType: 'price_list',
      required: true,
    },
    {
      number: 5,
      text: 'Amenidades por tipo de habitacion',
      why: 'Que incluye: jacuzzi, regadera, TV, clima, minibar, espejo, etc',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Proceso de check-in',
      why: 'Drive-in automatico? Recepcion? Minimo contacto?',
      inputType: 'text',
      required: true,
    },
    {
      number: 7,
      text: 'Estacionamiento',
      why: 'Privado/cubierto por habitacion? Capacidad',
      inputType: 'text',
      required: true,
    },
    {
      number: 8,
      text: 'Formas de pago',
      why: 'Efectivo, tarjeta, SPEI. Muchos moteles son cash-heavy',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 9,
      text: 'Facturacion CFDI',
      why: 'Disponible? Discrecion en factura (uso de CFDI generico)',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 10,
      text: 'Servicio de habitacion',
      why: 'Room service, minibar, articulos de higiene. Precios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 11,
      text: 'Programa de cliente frecuente',
      why: 'Descuentos por visitas, tarjeta VIP',
      inputType: 'text',
      required: false,
    },
    {
      number: 12,
      text: 'Tono del chatbot',
      why: 'Profesional, discreto. Sin juicio. Informativo',
      inputType: 'select',
      required: true,
    },
    {
      number: 13,
      text: 'Contacto de escalacion',
      why: 'Administrador nocturno',
      inputType: 'text',
      required: true,
    },
  ],
  glamping: [
    {
      number: 1,
      text: 'Nombre del glamping',
      why: 'Nombre del proyecto/marca',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Ubicacion EXACTA con coordenadas',
      why: 'Muchos glampings no tienen direccion postal. Google Maps pin es OBLIGATORIO',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Como llegar — instrucciones detalladas',
      why: 'Desde ciudad mas cercana. Se necesita 4x4? Ultimo tramo de terraceria?',
      inputType: 'textarea',
      required: true,
      followUpInsight: "'Como llego?' es la pregunta #1 de glamping. Tu bot dara instrucciones detalladas.",
    },
    {
      number: 4,
      text: 'Tipos de unidades',
      why: 'Domos, cabanas, treehouses, yurts, bubble tents, safari tents. Descripcion de CADA unidad',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Capacidad por unidad',
      why: 'Personas maximas, camas, configuracion',
      inputType: 'text',
      required: true,
    },
    {
      number: 6,
      text: 'Amenidades por unidad',
      why: 'Bano privado? Agua caliente? Electricidad? Calefaccion? WiFi? Cada unidad puede ser diferente',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Tarifas por unidad y temporada',
      why: 'Alta, baja, festivos, puentes. Minimo de noches',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 8,
      text: 'Que incluye la tarifa',
      why: 'Desayuno, cena, actividades, fogata, s\'mores',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 9,
      text: 'Actividades disponibles',
      why: 'Senderismo, tirolesa, kayak, observacion de estrellas, yoga, meditacion. Cuales incluidas, cuales con costo extra. ESTACIONALIDAD',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Comidas — como funcionan',
      why: 'Incluidas? Menu? Restricciones dieteticas? Pueden cocinar los huespedes?',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 11,
      text: 'Politica de clima',
      why: 'Que pasa si llueve/tormenta? Cancelacion? Reubicacion? Seguro?',
      inputType: 'text',
      required: true,
    },
    {
      number: 12,
      text: 'Conectividad',
      why: 'WiFi disponible? Senal celular? Esto es FEATURE, no bug — \'desconexion digital\'',
      inputType: 'text',
      required: true,
    },
    {
      number: 13,
      text: 'Politica de cancelacion',
      why: 'Anticipacion, reembolso, reprogramacion por clima',
      inputType: 'text',
      required: true,
    },
    {
      number: 14,
      text: 'Check-in/check-out',
      why: 'Horarios. Recepcion o autocheck-in?',
      inputType: 'text',
      required: true,
    },
    {
      number: 15,
      text: 'Distancia a hospital/emergencias mas cercano',
      why: 'CRITICO para seguridad',
      inputType: 'text',
      required: true,
    },
    {
      number: 16,
      text: 'Mascotas',
      why: 'Aceptan? Restricciones? Areas permitidas',
      inputType: 'text',
      required: false,
    },
    {
      number: 17,
      text: 'Eco-certificaciones',
      why: 'Distintivo S, EarthCheck, SEMARNAT',
      inputType: 'text',
      required: false,
    },
    {
      number: 18,
      text: 'Formas de pago',
      why: 'Transferencia SPEI es comun. Tarjeta? MSI?',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 19,
      text: 'Facturacion CFDI',
      why: 'Disponible?',
      inputType: 'boolean',
      required: false,
    },
    {
      number: 20,
      text: 'Tono del chatbot',
      why: 'Inspiracional, naturaleza, aventura. Serenidad',
      inputType: 'select',
      required: true,
    },
    {
      number: 21,
      text: 'Contacto de escalacion',
      why: 'Administrador del sitio',
      inputType: 'text',
      required: true,
    },
  ],
  bb_hostal: [
    {
      number: 1,
      text: 'Nombre del hostal/B&B',
      why: 'Como aparece en Hostelworld/Booking',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Direccion y como llegar',
      why: 'Transporte publico cercano es clave para backpackers',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Tipos de alojamiento',
      why: 'Dormitorio compartido (mixto, solo mujeres, solo hombres), habitacion privada, suite. Camas por dormitorio',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 4,
      text: 'Tarifas por tipo',
      why: 'Por cama en dorm, por habitacion privada. Temporada alta/baja',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Que incluye',
      why: 'Desayuno? Sabanas? Toallas? Locker? WiFi? Uso de cocina?',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Areas comunes',
      why: 'Cocina, sala, terraza, jardin, rooftop, coworking. Horarios',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Eventos/actividades',
      why: 'Bar crawl, tour gratuito, cena comunitaria, clase de cocina, yoga. Dias y horarios',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Lockers/seguridad',
      why: 'Incluidos? Necesitan su propio candado? Venden candados?',
      inputType: 'text',
      required: true,
    },
    {
      number: 9,
      text: 'Servicio de lavanderia',
      why: 'Disponible? Costo? Maquinas autoservicio?',
      inputType: 'text',
      required: false,
    },
    {
      number: 10,
      text: 'Cocina compartida',
      why: 'Horario, reglas, que incluye (sal, aceite, etc)',
      inputType: 'text',
      required: true,
    },
    {
      number: 11,
      text: 'Ambiente/vibe',
      why: 'Party hostel, chill, social, work-friendly',
      inputType: 'text',
      required: true,
    },
    {
      number: 12,
      text: 'Tours/experiencias',
      why: 'Que ofrecen directamente o via partnerships',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 13,
      text: 'Equipaje — deposito',
      why: 'Antes de check-in, despues de check-out. Gratuito?',
      inputType: 'text',
      required: false,
    },
    {
      number: 14,
      text: 'Politica de cancelacion',
      why: 'Free cancellation? Hasta cuando?',
      inputType: 'text',
      required: true,
    },
    {
      number: 15,
      text: 'Descuentos por estancia larga',
      why: 'Semanal, mensual',
      inputType: 'text',
      required: false,
    },
    {
      number: 16,
      text: 'Formas de pago',
      why: 'Cash, tarjeta. Booking.com prepago es comun',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 17,
      text: 'Idiomas',
      why: 'Ingles obligatorio en hostales turisticos',
      inputType: 'text',
      required: true,
    },
    {
      number: 18,
      text: 'Quiet hours',
      why: 'Horario de silencio (tipicamente 11PM-7AM)',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'Tono del chatbot',
      why: 'Cool, social, backpacker-friendly. No corporativo',
      inputType: 'select',
      required: true,
    },
    {
      number: 20,
      text: 'Contacto de escalacion',
      why: 'Recepcionista o dueno',
      inputType: 'text',
      required: true,
    },
  ],
  resort: [
    {
      number: 1,
      text: 'Nombre del resort',
      why: 'Nombre completo con marca (ej: \'Grand Palladium Costa Mujeres\')',
      inputType: 'text',
      required: true,
    },
    {
      number: 2,
      text: 'Ubicacion y como llegar desde aeropuerto',
      why: 'Distancia, tiempo, transfer disponible',
      inputType: 'text',
      required: true,
    },
    {
      number: 3,
      text: 'Que incluye el all-inclusive',
      why: 'ESTO ES LO MAS PREGUNTADO. Desglose: comidas, bebidas (domesticas vs. premium), actividades, shows, gym, albercas, deportes acuaticos. Que NO incluye',
      inputType: 'textarea',
      required: true,
      followUpInsight: "'Que incluye el all-inclusive?' es la pregunta #1. Tu bot detallara todo al instante.",
    },
    {
      number: 4,
      text: 'Tipos de habitacion',
      why: 'Estandar, superior, suite, presidential. Diferencias, capacidad, amenidades',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 5,
      text: 'Tarifas por tipo y temporada',
      why: 'Si el bot puede dar rango o debe referir',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 6,
      text: 'Restaurantes',
      why: 'Nombre, cocina, horario, dress code, necesita reservacion? Incluido en AI?',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 7,
      text: 'Bares',
      why: 'Nombre, ubicacion, horario, tipo de bebidas. Pool bar, lobby bar, beach bar',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 8,
      text: 'Spa',
      why: 'Tratamientos, precios (NO incluidos en AI tipicamente), como reservar',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 9,
      text: 'Actividades y entretenimiento',
      why: 'Deportes acuaticos, gym, yoga, shows nocturnos, kids club, teens club. Horarios',
      inputType: 'textarea',
      required: true,
    },
    {
      number: 10,
      text: 'Kids club / teens club',
      why: 'Edades, horario, que incluye, supervision',
      inputType: 'text',
      required: false,
    },
    {
      number: 11,
      text: 'Bodas y eventos',
      why: 'Paquetes, capacidad, coordinador. Precios o proceso de cotizacion',
      inputType: 'textarea',
      required: false,
    },
    {
      number: 12,
      text: 'Politica de cancelacion',
      why: 'Por canal. Penalizacion',
      inputType: 'text',
      required: true,
    },
    {
      number: 13,
      text: 'Transfer aeropuerto',
      why: 'Incluido? Costo? Compartido/privado?',
      inputType: 'text',
      required: true,
    },
    {
      number: 14,
      text: 'Wristband/pulsera RFID',
      why: 'Como funciona? Para que sirve? Pago, acceso, identificacion',
      inputType: 'text',
      required: false,
    },
    {
      number: 15,
      text: 'Moneda aceptada',
      why: 'MXN, USD, EUR. Tipo de cambio? Propinas en que moneda?',
      inputType: 'text',
      required: true,
    },
    {
      number: 16,
      text: 'Formas de pago',
      why: 'MSI critico para resorts ($50,000-200,000+ MXN)',
      inputType: 'multiselect',
      required: true,
    },
    {
      number: 17,
      text: 'Facturacion CFDI',
      why: 'Con ISH',
      inputType: 'boolean',
      required: true,
    },
    {
      number: 18,
      text: 'PMS actual',
      why: 'Para integracion',
      inputType: 'text',
      required: false,
    },
    {
      number: 19,
      text: 'Idiomas del staff',
      why: 'Espanol, ingles, frances, aleman, ruso',
      inputType: 'text',
      required: false,
    },
    {
      number: 20,
      text: 'Tono del chatbot',
      why: 'Aspiracional, luxury, pero accesible. \'Tu paraiso te espera.\'',
      inputType: 'select',
      required: true,
    },
    {
      number: 21,
      text: 'Contacto de escalacion',
      why: 'Revenue manager, wedding coordinator, GM',
      inputType: 'text',
      required: true,
    },
  ],
};
