import type { VerticalEnum, VerticalQuestion } from '@/lib/verticals/types';

export const retailQuestions: Partial<Record<VerticalEnum, VerticalQuestion[]>> = {
  floreria: [
    { number: 1, text: 'Nombre de la floreria', why: 'Como aparece en fachada/redes.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Incluir horario especial para 14 feb y 10 mayo.', inputType: 'textarea', required: true },
    { number: 3, text: 'Catalogo de arreglos con precios', why: 'Ramo clasico, arreglo de mesa, corona funebre, decoracion evento, sueltas (por tallo). PRECIOS. Cuales son fijos y cuales dependen del mercado.', inputType: 'price_list', required: true },
    { number: 4, text: 'Flores de temporada', why: 'Que flores no siempre estan disponibles. Tulipanes, peonias, hortensias = estacionales.', inputType: 'textarea', required: true },
    { number: 5, text: 'Arreglos personalizados', why: 'Proceso de cotizacion. Tiempo de anticipacion. Precio minimo.', inputType: 'textarea', required: true },
    { number: 6, text: 'Zona de entrega', why: 'Colonias/municipios que cubren. Costo de envio por zona. Envio gratuito a partir de $X?', inputType: 'textarea', required: true },
    { number: 7, text: 'Corte de hora para entrega mismo dia', why: 'Tipicamente 12-2PM. CRITICO — si el bot dice \'si entregamos hoy\' despues del corte, problema.', inputType: 'text', required: true },
    { number: 8, text: 'Servicio para eventos/bodas', why: 'Decoracion, centros de mesa, bouquet de novia. Proceso de cotizacion.', inputType: 'textarea', required: false },
    { number: 9, text: 'Suscripcion semanal/mensual de flores', why: 'Disponible? Precios? Frecuencia?', inputType: 'textarea', required: false },
    { number: 10, text: 'Tarjeta/mensaje incluido?', why: 'Gratis con arreglo? Limite de caracteres?', inputType: 'text', required: true },
    { number: 11, text: 'Precios especiales 14 feb y 10 mayo', why: 'Cuanto suben? Hay sobrecargo?', inputType: 'textarea', required: true },
    { number: 12, text: 'Garantia/reemplazo', why: 'Si llegan marchitas, que pasa? Plazo para reclamar? Con foto?', inputType: 'textarea', required: true },
    { number: 13, text: 'Formas de pago', why: 'SPEI creciendo mucho. Tarjeta. MSI para eventos.', inputType: 'multiselect', required: true },
    { number: 14, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 15, text: 'Tono del chatbot', why: 'Romantico, emotivo, celebratorio. \'Hagamos de este momento algo especial.\'', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Florista principal para pedidos complejos.', inputType: 'text', required: true },
  ],
  tienda_ropa: [
    { number: 1, text: 'Nombre de la tienda/boutique', why: 'Marca.', inputType: 'text', required: true },
    { number: 2, text: 'Tienda fisica y/o online', why: 'Direcciones. URL de tienda online.', inputType: 'textarea', required: true },
    { number: 3, text: 'Horario', why: 'Tienda fisica.', inputType: 'text', required: true },
    { number: 4, text: 'Tipo de ropa', why: 'Dama, caballero, ninos, unisex. Casual, formal, deportiva, tallas extras.', inputType: 'multiselect', required: true },
    { number: 5, text: 'Rango de precios', why: 'Desde $X hasta $Y. Promedio.', inputType: 'text', required: true },
    { number: 6, text: 'Catalogo — como lo comparten', why: 'WhatsApp catalogo, Instagram, link a tienda online, PDF.', inputType: 'select', required: true },
    { number: 7, text: 'Tallas disponibles', why: 'Sistema (MX, US, EU). Que tallas manejan. Guia de tallas?', inputType: 'textarea', required: true },
    { number: 8, text: 'Politica de devoluciones/cambios', why: 'Plazo (7, 15, 30 dias). Condiciones (etiqueta, sin uso). Reembolso o solo cambio/nota de credito. PROFECO aplica.', inputType: 'textarea', required: true },
    { number: 9, text: 'Apartado (layaway)', why: 'Disponible? Porcentaje de enganche? Tiempo limite para liquidar? Que pasa si no liquida?', inputType: 'textarea', required: false },
    { number: 10, text: 'Envios', why: 'Paqueterias (Fedex, Estafeta, DHL, 99 Minutos). Costo. Envio gratis a partir de $X? Tiempo de entrega.', inputType: 'textarea', required: true },
    { number: 11, text: 'Nuevas colecciones — frecuencia', why: 'Cada cuando llega mercancia nueva?', inputType: 'text', required: false },
    { number: 12, text: 'Promociones/rebajas', why: 'Temporadas de descuento, outlet permanente, descuento por apertura.', inputType: 'textarea', required: false },
    { number: 13, text: 'Formas de pago', why: 'Tarjeta, OXXO pay, SPEI, MSI (monto minimo, bancos), Kueski Pay, Mercado Pago.', inputType: 'multiselect', required: true },
    { number: 14, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 15, text: 'Redes sociales', why: 'Instagram CRITICO para moda.', inputType: 'text', required: true },
    { number: 16, text: 'Tono del chatbot', why: 'Trendy, aspiracional, cercano. Depende del target (luxury vs. fast fashion).', inputType: 'select', required: true },
    { number: 17, text: 'Contacto de escalacion', why: 'Duena/encargada para pedidos especiales.', inputType: 'text', required: true },
  ],
  papeleria: [
    { number: 1, text: 'Nombre de la papeleria', why: 'Como aparece en fachada.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Horario extendido en back-to-school (agosto-septiembre).', inputType: 'textarea', required: true },
    { number: 3, text: 'Servicios adicionales', why: 'Impresiones (B&N; y color, precio por hoja), copias, engargolado, encuadernado, enmicado, plotter, escaneo. PRECIOS de cada uno.', inputType: 'price_list', required: true },
    { number: 4, text: 'Listas de utiles escolares', why: 'Manejan listas de escuelas especificas? Cuales escuelas? Tienen paquetes armados? Precios de paquete vs. individual.', inputType: 'textarea', required: true },
    { number: 5, text: 'Venta de mayoreo/institucional', why: 'Para empresas, escuelas, oficinas. Precios diferenciados? Facturacion requerida.', inputType: 'textarea', required: false },
    { number: 6, text: 'Categorias principales', why: 'Cuadernos, lapices, plumas, colores, mochilas, calculadoras, tecnologia (USB, audifonos), oficina, arte, papeles especiales.', inputType: 'multiselect', required: true },
    { number: 7, text: 'Marcas principales', why: 'Scribe, Norma, Pelikan, Stabilo, etc.', inputType: 'textarea', required: true },
    { number: 8, text: 'Servicio de impresion — capacidades', why: 'Tamano maximo, color/B&N;, doble cara, papel especial (fotografico, opalina).', inputType: 'textarea', required: true },
    { number: 9, text: 'Formas de pago', why: 'Efectivo predominante. Tarjeta? SPEI?', inputType: 'multiselect', required: true },
    { number: 10, text: 'Facturacion CFDI', why: 'Critico para ventas institucionales.', inputType: 'boolean', required: true },
    { number: 11, text: 'Tono del chatbot', why: 'Servicial, rapido, practico. Mamas buscando utiles necesitan eficiencia.', inputType: 'select', required: true },
    { number: 12, text: 'Contacto de escalacion', why: 'Dueno para mayoreo/institucional.', inputType: 'text', required: true },
  ],
  ferreteria: [
    { number: 1, text: 'Nombre de la ferreteria/tlapaleria', why: 'Como aparece en fachada.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'L-S tipico. Domingos?', inputType: 'textarea', required: true },
    { number: 3, text: 'Categorias principales', why: 'Herramientas (manuales, electricas), plomeria, electricidad, pintura, cerrajeria, jardineria, construccion, tornilleria, adhesivos, seguridad.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Marcas principales', why: 'Truper, Pretul, DeWalt, Makita, Bosch, Comex/Berel/Sherwin-Williams para pintura.', inputType: 'textarea', required: true },
    { number: 5, text: 'Precios de mayoreo — estructura', why: 'Publico, menudeo, medio mayoreo, mayoreo. Minimos por nivel.', inputType: 'textarea', required: true },
    { number: 6, text: 'Cuentas de contratistas/profesionales', why: 'Credito? Limite? Descuentos especiales?', inputType: 'textarea', required: false },
    { number: 7, text: 'Asesoria tecnica disponible?', why: 'Personal capacitado que puede recomendar productos para tareas especificas.', inputType: 'boolean', required: true },
    { number: 8, text: 'Servicio de corte de material', why: 'Madera, vidrio, lamina, tuberia. Costo? Medidas?', inputType: 'textarea', required: false },
    { number: 9, text: 'Servicio a domicilio', why: 'Para materiales pesados (cemento, varilla, arena). Zona, costo, minimo.', inputType: 'textarea', required: false },
    { number: 10, text: 'Formas de pago', why: 'Tarjeta, efectivo, SPEI. MSI para herramientas electricas.', inputType: 'multiselect', required: true },
    { number: 11, text: 'Facturacion CFDI', why: 'CRITICO para contratistas/empresas.', inputType: 'boolean', required: true },
    { number: 12, text: 'Tono del chatbot', why: 'Directo, tecnico pero accesible. \'Dime que necesitas hacer y te digo que llevar.\'', inputType: 'select', required: true },
    { number: 13, text: 'Contacto de escalacion', why: 'Ferretero experto para consultas tecnicas complejas.', inputType: 'text', required: true },
  ],
  abarrotes: [
    { number: 1, text: 'Nombre de la tienda', why: 'Muchas no tienen nombre formal — \'Abarrotes Don Pedro\', \'La Esquina\', etc.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion', why: 'Colonia/calle/esquina. En muchos barrios todos saben cual es.', inputType: 'text', required: true },
    { number: 3, text: 'Horario', why: 'Muchas abren 7AM-10PM, 7 dias.', inputType: 'text', required: true },
    { number: 4, text: 'Productos principales', why: 'Abarrotes, bebidas, lacteos, pan, frutas/verduras, limpieza, cuidado personal, dulces, botanas.', inputType: 'multiselect', required: true },
    { number: 5, text: 'Servicios adicionales', why: 'Recargas telefonicas, pago de servicios (luz, agua, gas), envio de dinero. Comisiones que ganan.', inputType: 'multiselect', required: false },
    { number: 6, text: 'Fiado/credito a clientes', why: 'Manejan libreta de fiado? Digital o papel? Limite? Politica de cobro.', inputType: 'textarea', required: true },
    { number: 7, text: 'Servicio a domicilio', why: 'En la colonia? Gratis o con costo? Minimo?', inputType: 'textarea', required: false },
    { number: 8, text: 'Formas de pago', why: 'Efectivo es 60-80%. Clip? Mercado Pago QR? SPEI?', inputType: 'multiselect', required: true },
    { number: 9, text: 'Facturacion CFDI', why: 'Muchas tienditas no facturan — es valido informar.', inputType: 'boolean', required: true },
    { number: 10, text: 'Horario', why: 'Abren los 365 dias?', inputType: 'text', required: true },
    { number: 11, text: 'Tono del chatbot', why: 'De barrio, familiar, cercano. \'Que le damos, vecino?\'', inputType: 'select', required: true },
    { number: 12, text: 'Contacto de escalacion', why: 'Dueno directamente.', inputType: 'text', required: true },
  ],
  libreria: [
    { number: 1, text: 'Nombre de la libreria', why: 'Como aparece en fachada.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Incluir si abren domingos.', inputType: 'textarea', required: true },
    { number: 3, text: 'Especialidades', why: 'General, infantil, academica, arte, comics/manga, usados, antiguos.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Como buscar disponibilidad', why: 'Por titulo, autor, editorial, ISBN, tema.', inputType: 'textarea', required: true },
    { number: 5, text: 'Pedidos especiales', why: 'Pueden conseguir libros que no tienen? Tiempo? Costo de anticipo?', inputType: 'textarea', required: true },
    { number: 6, text: 'Libros de texto escolares', why: 'Manejan listas de escuelas? Cuales?', inputType: 'textarea', required: false },
    { number: 7, text: 'Eventos', why: 'Presentaciones de libros, clubs de lectura, cuentacuentos, firmas de autor. Calendario.', inputType: 'textarea', required: false },
    { number: 8, text: 'Envios', why: 'Paqueteria? Costo? Envio gratis a partir de $X?', inputType: 'textarea', required: false },
    { number: 9, text: 'Politica de devoluciones', why: 'Libros tipicamente no se devuelven excepto defecto. Politica exacta.', inputType: 'textarea', required: true },
    { number: 10, text: 'Ley de precio unico', why: 'Los libros nuevos tienen precio fijo 36 meses. No pueden dar descuento en nuevos.', inputType: 'text', required: true },
    { number: 11, text: 'Compra/venta de libros usados', why: 'Compran libros? A que porcentaje del precio? Que condiciones?', inputType: 'textarea', required: false },
    { number: 12, text: 'Formas de pago', why: 'Efectivo, tarjeta, SPEI. Los libros son EXENTOS de IVA para librerias.', inputType: 'multiselect', required: true },
    { number: 13, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 14, text: 'Tono del chatbot', why: 'Culto pero cercano. Apasionado por la lectura. Recomendaciones con personalidad.', inputType: 'select', required: true },
    { number: 15, text: 'Contacto de escalacion', why: 'Librero experto o dueno.', inputType: 'text', required: true },
  ],
  joyeria: [
    { number: 1, text: 'Nombre de la joyeria', why: 'Nombre de la marca/tienda.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Incluir si estan en plaza/centro comercial.', inputType: 'textarea', required: true },
    { number: 3, text: 'Tipo de joyeria', why: 'Oro (10K, 14K, 18K, 24K), plata (.925), acero, fantasia, piedras preciosas, relojeria.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Rango de precios', why: 'Desde $X hasta $Y. Piezas estrella.', inputType: 'text', required: true },
    { number: 5, text: 'Diseno personalizado', why: 'Ofrecen? Proceso? Tiempo (2-6 semanas tipico)? Costo base?', inputType: 'textarea', required: false },
    { number: 6, text: 'Reparaciones', why: 'Que reparan (cadenas, ajuste talla, pulido, cambio de pila reloj). Precios. Tiempo.', inputType: 'textarea', required: false },
    { number: 7, text: 'Avaluos', why: 'Ofrecen? Certificaciones (GIA, IGI)? Costo?', inputType: 'textarea', required: false },
    { number: 8, text: 'Garantia', why: 'Cuanto tiempo? Que cubre? Que excluye?', inputType: 'textarea', required: true },
    { number: 9, text: 'Grabado', why: 'Disponible? Costo? Tiempo?', inputType: 'textarea', required: false },
    { number: 10, text: 'Certificados de autenticidad', why: 'Proporcionan? Para que piezas?', inputType: 'textarea', required: true },
    { number: 11, text: 'Empenio o compra de oro', why: 'Compran oro? A que porcentaje? Documentacion requerida (INE).', inputType: 'textarea', required: false },
    { number: 12, text: 'Formas de pago', why: 'MSI es CRITICO — anillos de compromiso pueden costar $20,000-200,000+ MXN.', inputType: 'multiselect', required: true },
    { number: 13, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 14, text: 'Seguro de joyas', why: 'Ofrecen o recomiendan?', inputType: 'boolean', required: false },
    { number: 15, text: 'Tono del chatbot', why: 'Elegante, exclusivo pero accesible. \'Encontremos la pieza perfecta.\'', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Joyero experto o dueno para piezas de alto valor.', inputType: 'text', required: true },
  ],
  jugueteria: [
    { number: 1, text: 'Nombre de la jugueteria', why: 'Como aparece en fachada.', inputType: 'text', required: true },
    { number: 2, text: 'Direccion y horario', why: 'Horario extendido en Navidad, Reyes, Dia del Nino.', inputType: 'textarea', required: true },
    { number: 3, text: 'Categorias por edad', why: '0-2 anos, 3-5, 6-8, 9-12, 13+, adultos (juegos de mesa).', inputType: 'multiselect', required: true },
    { number: 4, text: 'Marcas principales', why: 'Mattel, Hasbro, LEGO, Fisher-Price, Hot Wheels, Barbie, etc.', inputType: 'textarea', required: true },
    { number: 5, text: 'Rango de precios', why: 'Desde $X hasta $Y.', inputType: 'text', required: true },
    { number: 6, text: 'Servicio de envoltura de regalo', why: 'Disponible? Costo? Gratis a partir de $X?', inputType: 'textarea', required: false },
    { number: 7, text: 'Cumpleaneros — paquetes/dulceros', why: 'Pinatas, dulceros, sorpresas, decoracion. Precios por paquete o individual.', inputType: 'textarea', required: false },
    { number: 8, text: 'Juguetes educativos/STEM', why: 'Categoria especial?', inputType: 'boolean', required: false },
    { number: 9, text: 'Seguridad — NOM-015-SCFI-2007', why: 'Rango de edad en etiquetas. Advertencias en espanol.', inputType: 'textarea', required: true },
    { number: 10, text: 'Envios', why: 'Disponible? Paqueteria? Costo?', inputType: 'textarea', required: false },
    { number: 11, text: 'Politica de cambios/devoluciones', why: 'Plazo, condiciones, con ticket.', inputType: 'textarea', required: true },
    { number: 12, text: 'Temporadas pico y horarios especiales', why: 'Dia del Nino (30 abril), Navidad, Dia de Reyes (6 enero). Horarios extendidos.', inputType: 'textarea', required: true },
    { number: 13, text: 'Formas de pago', why: 'Tarjeta, efectivo, MSI (clave en Navidad/Reyes).', inputType: 'multiselect', required: true },
    { number: 14, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 15, text: 'Tono del chatbot', why: 'Divertido, familiar, magico. \'Que le brilla los ojos a tu peque?\'', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Dueno o encargado.', inputType: 'text', required: true },
  ],
  zapateria: [
    { number: 1, text: 'Nombre de la zapateria', why: 'Marca propia o multimarca?', inputType: 'text', required: true },
    { number: 2, text: 'Direccion(es) y horario', why: 'Multi-sucursal? Plaza comercial?', inputType: 'textarea', required: true },
    { number: 3, text: 'Tipo de calzado', why: 'Dama, caballero, ninos, deportivo, casual, formal, botas, sandalias, industrial/seguridad, ortopedico.', inputType: 'multiselect', required: true },
    { number: 4, text: 'Marcas que manejan', why: 'Nike, Adidas, Flexi, Andrea, Price Shoes, Capa de Ozono, etc. O marca propia.', inputType: 'textarea', required: true },
    { number: 5, text: 'Rango de precios', why: 'Desde $X hasta $Y.', inputType: 'text', required: true },
    { number: 6, text: 'Sistema de tallas', why: 'MX, US, EU, CM. Guia de conversion? Tabla de medidas?', inputType: 'textarea', required: true },
    { number: 7, text: 'Politica de cambios/devoluciones', why: 'Plazo. Condiciones (sin uso, caja original). Reembolso o solo cambio. PROFECO regula esto.', inputType: 'textarea', required: true },
    { number: 8, text: 'Garantia', why: 'PROFECO establece minimo. Que cubren y que no.', inputType: 'textarea', required: true },
    { number: 9, text: 'Calzado ortopedico/especializado', why: 'Disponible? Requiere receta? Marcas?', inputType: 'textarea', required: false },
    { number: 10, text: 'Catalogo online/WhatsApp', why: 'Comparten fotos por WhatsApp? Link a tienda online?', inputType: 'select', required: true },
    { number: 11, text: 'Apartado', why: 'Disponible? Enganche? Plazo?', inputType: 'textarea', required: false },
    { number: 12, text: 'Envios', why: 'Para tienda online. Paqueteria, costo, tiempo.', inputType: 'textarea', required: false },
    { number: 13, text: 'Formas de pago', why: 'Tarjeta, efectivo, MSI, Kueski Pay, Mercado Pago.', inputType: 'multiselect', required: true },
    { number: 14, text: 'Facturacion CFDI', why: 'Disponible?', inputType: 'boolean', required: true },
    { number: 15, text: 'Tono del chatbot', why: 'Depende del segmento. Deportivo: energetico. Fashion: trendy. Familiar: practico.', inputType: 'select', required: true },
    { number: 16, text: 'Contacto de escalacion', why: 'Encargado de sucursal o dueno.', inputType: 'text', required: true },
  ],
};
